### ISSUE TITLE
The library uses MD5 hashing algorithm, i need to change it to SHA512, any idea where to change it?

### ISSUE THREAD

**Issue by mashad6** [RonRadtke/react-native-blob-util#102]
Hi ! Thank you for reporting an issue, but we would like to remind you, we have a trouble shooting page in our wiki. 
You may want to take a look on that page or find issues tagged "trouble shooting" :p 

* please provide the version of installed library and RN project.
* a sample code snippet/repository is very helpful to spotting the problem.
* issues which have been tagged as 'needs feedback', will be closed after 2 weeks if receive no feedbacks.
* issues lack of detailed information will be closed without any feedback

**Comment by RonRadtke** [comment]
https://github.com/RonRadtke/react-native-blob-util/blob/e73e2791890fa02066ac89fb4cfaad7cfb47772c/android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilFS.java#L906

In general we do support that, so you just need to specify the algorithm correctly whe calling the hash function
