### ISSUE TITLE
`ReactNativeBlobUtil.fs.mv` not working on Android.

### ISSUE THREAD

**Issue by AdrianKuta** [RonRadtke/react-native-blob-util#105]
# Hi everyone 👋 

![GitHub last commit](https://img.shields.io/badge/version-0.13.18-blue)
Tested on: _Android 9, Android 11_ and _Android 12_

## ReactNativeBlobUtil.fs.mv

I'm trying to rename image file on android by using `ReactNativeBlobUtil.fs.mv` method, but I'm getting error:

> **❗Error:** Source file at path `file:///data/user/0/com.metime.womanup/cache/ReactNative-snapshot-image4984740432931102882.png` does not exist

<img src="https://user-images.githubusercontent.com/46381935/151415750-279063fe-4a74-46ca-b1b4-3ea5eda11965.png" alt="image" width="500">

Of course, the first thing I done after, was listing all files in dirs:

<img src="https://user-images.githubusercontent.com/46381935/151418257-d21c60f5-1bc8-4349-9fe2-86c391250968.png" alt="image" width="500">

and the file exist.

## Code sample

```typescript
const uri = await captureRef(imageRef, {
  format: 'png',
});
// Rename file to display properly in share dialog
const tempPath = uri.substr(0, uri.lastIndexOf('/'));
const newPath = `${ReactNativeBlobUtil.fs.dirs.CacheDir}/Podsumowanie treningu.png`;
console.log(
  uri,
  await ReactNativeBlobUtil.fs.exists(uri)
);
await ReactNativeBlobUtil.fs.mv(uri, newPath);
```

`console.log` output:
```
file:///data/user/0/com.metime.womanup/cache/ReactNative-snapshot-image4984740432931102882.png true
```

## ReactNativeBlobUtil.fs.cp

I think it maybe a bug in library, because `ReactNativeBlobUtil.fs.cp` for the same file is working.

```typescript
const uri = await captureRef(imageRef, {
  format: 'png',
});
// Rename file to display properly in share dialog
const tempPath = uri.substr(0, uri.lastIndexOf('/'));
const newPath = `${ReactNativeBlobUtil.fs.dirs.CacheDir}/Podsumowanie treningu.png`;
console.log(
  uri,
  await ReactNativeBlobUtil.fs.exists(uri)
);
await ReactNativeBlobUtil.fs.cp(uri, newPath);
await ReactNativeBlobUtil.fs.unlink(uri);
```

**Comment by RonRadtke** [comment]
Fixed in https://github.com/RonRadtke/react-native-blob-util/pull/124/commits
