### ISSUE TITLE
saving a file to another folder

### ISSUE THREAD

**Issue by kudiluv** [RonRadtke/react-native-blob-util#106]
How could I save the downloaded file to the folder specified by the user? I can't copy the file because it doesn't exist.
Here is my code:
```
const onDownload = async () => {
    ReactNativeBlobUtil.config({
      addAndroidDownloads: {
        useDownloadManager: true,
        notification: true,
        mime: 'application/pdf',
        title: fileName,
        mediaScannable: true,
      },
    })
      .fetch('GET', `${API_URL}/results/${testId}/pdf`)
      .then(async resp => {
        const path = await selectDirectory();
        await ReactNativeBlobUtil.fs.cp(resp.path(), `${path}/${fileName}`);
      });
  };
```

**Comment by RonRadtke** [comment]
What is the value of res.path()?

**Comment by afilp** [comment]
Maybe this issue is also related to our other discussion?
https://github.com/RonRadtke/react-native-blob-util/issues/62

Also, that is `selectDirectory()`? Your own function? I would be interested to know if something like that exists.
