### ISSUE TITLE
Progress total return -1, while there received value is normal.

### ISSUE THREAD

**Issue by gwijaya94** [RonRadtke/react-native-blob-util#107]
Hi, recently I used this library for dependencies for react-native-pdf
I get the download progress value with received/total, hopefully get the value between 0 - 0.99, 
then the value show with negative value for example -610292. (received: 610292, total: -1).
Code:
<img width="437" alt="Screen Shot 2022-01-31 at 11 14 38" src="https://user-images.githubusercontent.com/65438712/151738070-11b05e25-6397-4175-8489-f05ab1d62d57.png">

Here's the result:
<img width="193" alt="Screen Shot 2022-01-31 at 11 13 35" src="https://user-images.githubusercontent.com/65438712/151738005-022233db-bc82-4d7a-a453-161f64fedee1.png">

Note: trusty false because I have certificate for ssl pinning.

react-native: 0.66.1
react-native-blob-util: 0.13.18

device tested:
- Android : Google Pixel 4a
- iOS : Iphone 7, Simulator iPhone 12 Pro

any idea what happens with the total? does it need additional config?

**Comment by gwijaya94** [comment]
Thank you dor the reply @RonRadtke.
Is by accessing the link on browser manually not enough? Cause I try the link and it shows the pdf, so i think the link is not the problem. 
I will try another link or test it on another project.
Will let you know as soon as try it.

**Comment by RonRadtke** [comment]
No, not necessarily. It is enough to verify that it works as a download, but not for the content header length. The download itself should work without too.

**Comment by gwijaya94** [comment]
@RonRadtke, I've tried another link and apparently it works. 
Thank you for the info about contentLength, I have no idea at all.
I've consulted with my server-side team to solve this problem.

**Comment by damianfilipek81** [comment]
@gwijaya94 how did you manage to enable ssl certificate pinning?
