### ISSUE TITLE
iOS: previewDocument or openDocument only works at the first download, not at next downloads

### ISSUE THREAD

**Issue by afilp** [RonRadtke/react-native-blob-util#108]
* please provide the version of installed library and RN project.
  
```
      "react-native": "0.66.2",
    "react-native-blob-util": "^0.13.18",
```

In iOS, after I download a PDF, I use either the `previewDocument ` or the `openDocument`, like that:

```
if (Platform.OS === 'ios') {
            ReactNativeBlobUtil.ios.previewDocument(res.path());
          }
```

However, it only works the first time during the entire app's session. 

It does not appear the next time I download a document, whether it is the same document or other documents. Is this a bug I assume? Have you noticed this behavior? I do not know why this happens.

**Comment by afilp** [comment]
I had to use `react-native-share`, which somewhat "solved" the problem, but it would be nice to be able to open the pdf directly.

**Comment by RonRadtke** [comment]
I know, but first I have to find the cause for the issue.
So if you can help find it, it would be great.
Everything is helpful, error messages, if the code is fully executed, where the code breaks exactly, ...
