### ISSUE TITLE
Some iOS users crash with `SIGABRT: Failed to grow buffer `

### ISSUE THREAD

**Issue by afilp** [RonRadtke/react-native-blob-util#114]
* please provide the version of installed library and RN project.
  
```
      "react-native": "0.66.2",
    "react-native-blob-util": "^0.13.18",
```

We have reports from iOS users, that when they start uploading photos/videos (with a single endpoint call) the app crashes.

This is what we get in crash report:

`SIGABRT: Failed to grow buffer `

Any ideas if this is a bug (seems a low memory issues?) or we can change something for these crashes not to occur?

**Comment by RonRadtke** [comment]
Do you have a line of code for it?
It is some kind of problem with the memory allocation, yes.
But it could  be a wrong length for the data or sth like that.

**Comment by afilp** [comment]
Sorry @RonRadtke, the crash report did not give me the line number of the JS.

**Comment by afilp** [comment]
If I see that error again I will let you know, meanwhile we get reported that users tried to upload for example 34 photos in a direct upload and it managed to download some and then crashed.

Will it help memory-wise to split the single large upload of all files into separate uploads? (one per 2 files for example?)

**Comment by afilp** [comment]
@RonRadtke I have more info on this now:

```+[ReactNativeBlobUtilReqBuilder buildMultipartRequest:taskId:method:url:headers:form:onComplete:]
ReactNativeBlobUtilReqBuilder.m, line 63
```

See also screenshot:

![image](https://user-images.githubusercontent.com/7850073/154290449-540b232b-dca8-4f53-bc50-2051a5cc8a0a.png)

**Comment by aramhovsepyan** [comment]
Same problem. We've tried some other libraries as well, which end up in the same exception.
The problem is reproducible with large files (900MB) on iOS.

**Comment by RonRadtke** [comment]
I assume that the app can't allocate as much memory as it would have to and thus fails.
So the only option would be some way of streaming the file in chunks I think.

**Comment by azyd3** [comment]
> So the only option would be some way of streaming the file in chunks I think. - How can we do it?
