### ISSUE TITLE
ReferenceError: base64 is not defined

### ISSUE THREAD

**Issue by oguzozturk** [RonRadtke/react-native-blob-util#116]
* the version of installed library 0.13.18 and RN project 0.63.4

* When send a request, api returns response base64 data type. Library catch response data type but can not convert base64 data type to json format.

ReactNativeBlobUtilBlobResponse.js
/**
 * Convert result to JSON object.
 * @return {object} Parsed javascript object.
 */
this.json = (): any => {
    switch (this.type) {
        **case 'base64':
            return JSON.parse(base64.decode(this.data));**
        case 'path':
            return fs.readFile(this.data, 'utf8')
                .then((text) => Promise.resolve(JSON.parse(text)));
        default:
            return JSON.parse(this.data);
    }
};

P.S.
In local project, after import base-64 library which is included in package.json file as "base-64": "1.0.0" inside node_modules/react-native-blob-util/class/ReactNativeBlobUtilBlobResponse.js path, it worked.

Could you help me about this problem?

**Comment by RonRadtke** [comment]
You have to have base64 installed. It is a dependency of the library. Without it won't work. It is listed in the package.json, so if you installed the library correctly it should work without any issues.
So no, I don't really have an idea why you're running in these problems. Sounds like the abse64 lib is not installed correctly.
