### ISSUE TITLE
[iOS] Copy file to top-level in Files.app

### ISSUE THREAD

**Issue by artdevgame** [RonRadtke/react-native-blob-util#119]
Hello 👋🏻 

I'm unsure if I'm missing some obvious documentation, please point it out if I have.

I'm trying to copy a file from my apps cache dir to the top-level of Files.app:
```
...
const source = mediaPath;
const destination = `${dirs.DocumentDir}/${fileName}`;

await ReactNativeBlobUtil.fs.cp(source, destination);
```

However, this copies the file to the apps documents dir instead.

I have the following keys set in my Info.plist:
- UIFileSharingEnabled
- UISupportsDocumentBrowser

So the file is available when running on device, but not in the simulator. When I delete the app (and all data), it removes the files I copied too.

How can I download to the general Documents dir?

**Comment by RonRadtke** [comment]
That's not possible.
Please check here: https://github.com/RonRadtke/react-native-blob-util/issues/62#issuecomment-1024041198
I wrote some explanation about that in this thread.
