### ISSUE TITLE
hash() function gives "no such file" error while readFile() succeeds with same uri.

### ISSUE THREAD

**Issue by andra961** [RonRadtke/react-native-blob-util#120]
Here's the code:

```
      const fileDetails = await DocumentPicker.pick({
        // Provide which type of file you want user to pick
        type: [DocumentPicker.types.allFiles],
      });
      setSelectedFile(fileDetails)
      let fileContentBlobUtil = await RNFetchBlob.fs.readFile(fileDetails[0].uri, 'base64')
      let fileHashBlobUtil = await RNFetchBlob.fs.hash(fileDetails[0].uri, 'sha256')
```
readFile() return the base64 encoding of the file correctly, while the hash() function using same identical uri (provided by document picker) gives following error: 

[Error: No such file 'content://com.google.android.apps.docs.storage/document/acc%3D1%3Bdoc%3Dencoded%3DTGhH_d6AtnqwiD39DnZwrQ0kCTtqjiY6UYhHLISr6DLSSsqJONKGKvfjlSdVqkT2']

Any idea of why this happens?

**Comment by RonRadtke** [comment]
Might be that there is missing a normalizePath call which would resolve the URI. 
You could try to add
``resolved = ReactNativeBlobUtilUtils.normalizePath(path);```
here: https://github.com/RonRadtke/react-native-blob-util/blob/1512092440b73ff4316a055af0366cfbfd9845b2/android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilFS.java#L780

**Comment by onlyling** [comment]
> Might be that there is missing a normalizePath call which would resolve the URI. You could try to add ``resolved = ReactNativeBlobUtilUtils.normalizePath(path);``` before that line:
> 
> https://github.com/RonRadtke/react-native-blob-util/blob/1512092440b73ff4316a055af0366cfbfd9845b2/android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilFS.java#L780

can fix the problem.

#124

**Comment by RonRadtke** [comment]
@onlyling of course. Did you test if it resolves your issue?

**Comment by onlyling** [comment]
> @onlyling of course. Did you test if it resolves your issue?

solved.

modified the local node_module file and repackaged the application for testing.

**Comment by RonRadtke** [comment]
technically yes.
Do you want to add it directly? Then I would merge the PR and both are fixed

**Comment by onlyling** [comment]
> technically yes. Do you want to add it directly? Then I would merge the PR and both are fixed

The path starting with `content://` is not adapted in the normalizePath function, and the path starting with `file://` does not report an error. At the same time, I found that there are differences in usage between Android and iOS.

#124

Need you to fix it, or explain that the path cannot start with `file://`.

**Comment by RonRadtke** [comment]
A path starting with content:// often belongs to a media store and thus will make problems regardless since we would have to open these via a contentProvidor or copy the first into the internal storage.
