### ISSUE TITLE
Feature: read x bytes from file

### ISSUE THREAD

**Issue by fabervae** [RonRadtke/react-native-blob-util#121]
Hi! Thank you for continuing to maintain this library. Instead of reading a whole file, do you have plans for adding a method for reading a number of bytes from a local file at a given position? It would be similar to what [react-native-fs](https://github.com/itinance/react-native-fs/#readfilepath-string-length--0-position--0-encodingoroptions-any-promisestring) offers.

**Comment by RonRadtke** [comment]
Currently no, but it would be possible to extend e.g. readStream in that way

**Comment by fabervae** [comment]
Indeed, that would be the alternative. I will close the issue but feel free to open it if it becomes relevant again.

**Comment by draperunner** [comment]
I would really like a feature like this as well!

And another related feature request: Provide a `.close()` method on the read streams, just like on the write streams. This way we can stop reading the file if a certain chunk has been found.
