### ISSUE TITLE
`resp.text()` cause exception `Property 'base64' doesn't not exits`

### ISSUE THREAD

**Issue by zhuanghongji** [RonRadtke/react-native-blob-util#126]
react-native-blob-util: ^0.14.1

example code: 
```
export async function test() {
   try {
      const resp = await RNFetchBlob.fetch('GET', 'a-url')  
      const text = await resp.text()     // the line caused exception
   } catch(e) {
      console.log(e.message)            // Property 'base64' doesn't not exits
   }
}
```

If i goto `/node_modules/react-native-blob-util/class/ReactNativeBlobUtilBlobResponse.js` and add code below:
```
import base64 from 'base-64'
```
`resp.text()` worked.

So, is any wrong with `text()` implement ?

note: if it switch to 'rn-fetch-blob' and try the same example code, `text()` work fine.

**Comment by jaylensoeur** [comment]
I have the same problem, it looks like the dependency is missing.

**Comment by RonRadtke** [comment]
Thanks, I merged your PR @jaylensoeur
