### ISSUE TITLE
Upload throws `ReactNativeBlobUtil.writeFile` error

### ISSUE THREAD

**Issue by scgough** [RonRadtke/react-native-blob-util#131]
Hi, 
I'm migrating over from `rn-fetch-blob` and seem to have hit an error uploading. 
As soon as the upload attempts to start I get a crash with the following error: 
`ReactNativeBlobUtil.writeFile was called with 4 arguments but expects 5 arguments...` 

This occurs via `/fs.js` on line 246 (in the `appendFile` function):
`return ReactNativeBlobUtil.writeFile(path, encoding, data, true);` 

This is the syntax being used. If anyone can see anything obvious please do let me know! 

```
import RNBlobUtil from 'react-native-blob-util';
...
const fetcher = new RNBlobUtil.polyfill.Fetch({
  auto: true,
  binaryContentTypes: ['image/', 'video/', 'audio/'],
}).build();
const FileItem = RNBlobUtil.polyfill.File;
...
const body = new FormData();
  Object.keys(fields).forEach(key => {
    body.append(key,fields[key]);
  });

const fileName = 'filename_is_here';
  body.append(
    'file',
    await FileItem.build(
      fileName,
      RNBlobUtil.wrap(replace('file://', '', file.path || '')),
      { type: file.mime }
    ),
    fileName
);
...
const req = fetcher('upload_url_is_here', {
    method: 'POST',
    headers: {
      'Content-Type': 'multipart/form-data',
    },
   body,
  });
...
let response = await req; //<--error 
```

**Comment by RonRadtke** [comment]
Hi,
thank you very much!
That feature is new, so new it didn't even make it to npm yet.
But very good catch!
You're absolutely right, there is missing the new parameter for the transform. That one somehow managed to slip trough.

**Comment by scgough** [comment]
Great - glad to help. Thanks for the swift confirmation!
