### ISSUE TITLE
wrong characters returned

### ISSUE THREAD

**Issue by mrday86** [RonRadtke/react-native-blob-util#134]
Hello I'm Alessandro, I was doing some test and I found out some problem with "particular" chars:

please provide the version of installed library and RN project.
"react-native": "0.64.3"
"react-native-blob-util": "^0.15.0"
a sample code snippet/repository is very helpful to spotting the problem.

```
import React, {Node, useState} from 'react';
import { SafeAreaView, ScrollView, StatusBar, TextInput,Button, useColorScheme, View,} from 'react-native';
import ReactNativeBlobUtil from 'react-native-blob-util'

const App: () => Node = () => {
  const [text,setText] = useState("")
  return (
    <SafeAreaView>
    <Button title="test" onPress={()=>{downloadFile("https://www.i18nqa.com/debug/utf8-debug.html","mm.txt")}}></Button>
    <TextInput defaultValue={text} multiline={true}></TextInput>
    </SafeAreaView>
  );
  async function downloadFile(url,fileName) {
    const { config, fs } = ReactNativeBlobUtil;
    const downloads = fs.dirs.DownloadDir;
    let status = 0;
    try {
      const res = await config({
        fileCache: true,
      }).fetch('GET', url);
      status = res.info().status;
      if (status == 200) {
        // the conversion is done in native code
        let base64Str = res.base64().then((d)=>{console.log("done base64")});
        // the following conversions are done in js, it's SYNC
        res.text().then((t)=>{console.log("done text");setText(t);});
      } else {
        // handle other status codes
        console.log("EROR", status);
      }
    } catch (errorMessage) {
      // error handling
      console.log(errorMessage, status);
    }
  }
};
  export default App;
```
For example € appears as "â�¬"
Can you please take a look?
Thanks
Alessandro

**Comment by RonRadtke** [comment]
This is actually the correct behaviour.
Based on the implementation and standard for base64 only characters in the range U+0000 to U+00FF are supported. This does not include the € sign.
A workaround would e.g. be to first convert it to html representation, or to not relay on the base64 but e.g. use JSON to transport the data.

**Comment by mrday86** [comment]
Just to understand: `res.text() ` imply a base64 conversion of the downloaded content?

**Comment by RonRadtke** [comment]
Yes exactly.
See: https://github.com/RonRadtke/react-native-blob-util/blob/d52ba2ba5155252fd8a8e797dffd7684c59fcd17/class/ReactNativeBlobUtilBlobResponse.js#L79

**Comment by mrday86** [comment]
solved by changing the response type before to request the text
