### ISSUE TITLE
Security Issue: SSL Configuration Allows Insecure Connections

### ISSUE THREAD

**Issue by adnanal-hrbl** [RonRadtke/react-native-blob-util#135]
Hi,
We are facing SSL configuration issues on our app, and after digging through the repo code, we found that the following file is not having proper implementation, its just throwing exception.
**/react-native-blob-util-master/android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilUtils.java**

**Below are the description of issues and recommended fix:**
-->
The application contains code which overrides Android's built in certificate validation procedures and potentially allows HTTPS connections to be created without establishing trust properly. If this connection is created, remote attacker could intercept and modify that traffic to and from the app. This type of vulnerability can also be flagged as a blocker by the Android Play Store.

METHOD
--
Lcom/ReactNativeBlobUtil/ReactNativeBlobUtilUtils$1;,checkClientTrusted,([Ljava/security/cert/X509Certificate;Ljava/lang/String;)V
Lcom/ReactNativeBlobUtil/ReactNativeBlobUtilUtils$1;,checkServerTrusted,([Ljava/security/cert/X509Certificate;Ljava/lang/String;)V

-->Solution
**Recommended Fix**
If avoidable, do not create your own implementations of certificate validation - in this case removing the code which is overriding the default implementation will likely remediate this check, however that may not be an option for your app. If you have to implement your own make certain that checkServerTrusted properly handles exceptions as they indicate a problem with the certificate being evaluated. The Findings Evidence below gives the class and method of the code which is being flagged as insecure. More verbose data is available in the raw output of the debugging section.
Additional Guidance
Securely implementing SSL in Android https://developer.android.com/training/articles/security-ssl
Android Helpdesk resources on fixing custom implementations of TrustManager https://support.google.com/faqs/answer/6346016?hl=en

**-->Please reply as soon as possible as we are stuck on this.** @RonRadtke

**Comment by adnanal-hrbl** [comment]
@midunm-c tagging you here

**Comment by RonRadtke** [comment]
Likely you're using the ``trusty`` option.
Only if this option is used an own implementation of certificate validation is used. Otherwise, so without ``trusty`=true``, the default implementation is used.
And so far the app store only rejected / complained about apps which explicitly are using this option.

This option is solely for development purposes to be able to use not proper signed SSL-Certificates, e.g. in an internal network.

So please check if you're using the option, and if so, try without.

**Comment by RonRadtke** [comment]
I currently don't.
The only option would be to either remove the functionality or extend the functionality to change the implementation to match the required behavior.

It's actually the first time seeing this problem without trusty being set anywhere.
So just to make sure, you're no where in your app setting the trusty option?

**Comment by adnanal-hrbl** [comment]
no at only one place we are using this library and throughout the app we don't have nay "trusty" key used.

thanks for your help. will try to change the implementation.

**Comment by RonRadtke** [comment]
I'm considering removing it and releasing a 0.16.0. It's an old artifact and I'm personally not a big fan of it.
Maybe replacing it with an interface like for the transform...

**Comment by RonRadtke** [comment]
@adnanal-hrbl I just pushed a branch which is removing the custom trustmanager implementation so it would have to be given from outside of the lib.
Branch: https://github.com/RonRadtke/react-native-blob-util/tree/feature/trustmanager_removal
Feel feel to try it out. If it works fine for you I would merge it and release it

**Comment by adnanal-hrbl** [comment]
thanks and appreciate!!! i will try on it and will update you once the security scan is done

**Comment by RonRadtke** [comment]
@adnanal-hrbl any news here?

**Comment by adnanal-hrbl** [comment]
@RonRadtke thanks a lot. last week we got the report and due to weekends I was not able to reply. that solution worked. currently I am using this branch, but will wait for you to merge it to master, so that it will be good for future as well. 
thanks a lot!

**Comment by RonRadtke** [comment]
Released so closed
