### ISSUE TITLE
Library not found for -lreact-native-blob-util

### ISSUE THREAD

**Issue by arinconc** [RonRadtke/react-native-blob-util#140]
Hello.
I am trying to install react-native-blob-util and have run the following:
`npm install --save react-native-blob-util`
Then in the ios folder I executed
`pod install`

Finally when running the app on iOS it gives me the following error:
`library not found for -lreact-native-blob-util`

I have even added the following line to the podfile and installed pods:
```
pod 'react-native-blob-util',
    :path => '../node_modules/react-native-blob-util'

```
But nothing, I can't compile the app
Some help?

Thank you very much!

* "react-native": "0.66.1"
*  "react-native-blob-util": "^0.15.0"

**Comment by RonRadtke** [comment]
Sounds like you're trying to build on an old cache or like the pod install didn't work as it should.
I tried it on a clean environment and it works as it should the way you did it.
