### ISSUE TITLE
[Android] failed download file from url

### ISSUE THREAD

**Issue by robyhuzwandar** [RonRadtke/react-native-blob-util#141]
* please provide the version of installed library and RN project.
```
 "react-native": "0.66.3",
 "react-native-blob-util": "^0.15.0",
```

tried on :
```
- Android 11 (emulator)
- Android 9 (real device)
   
```
* a sample code snippet/repository is very helpful to spotting the problem.

the issue happens when I call this code.
```
const fileZipPath =
  Platform.OS === 'android'
    ? ReactNativeBlobUtil.fs.asset('/translations/resources.zip')
    : ReactNativeBlobUtil.fs.dirs.MainBundleDir + '/translations/resources.zip';

ReactNativeBlobUtil.config({
      overwrite: true,
      fileCache: true,
      path: fileZipPath,
    })
      .fetch('GET', url)
      .then(() => {
             ......
      })
      .catch(error => {
        console.error('ERROR : ', error);
      });
```

* issues lack of detailed information will be closed without any feedback
  
error message from catch :
` ERROR :  [Error: Unexpected FileStorage response file: null]
`

<img width="409" alt="image" src="https://user-images.githubusercontent.com/20414047/161184333-0ca136af-19a9-47e9-a80e-2b50da71e69a.png">

**What have I tried?** (but still facing the issue)
1. Link package manually 
2. Call package directly to the master
    ```  "react-native-blob-util": "git+https://github.com/RonRadtke/react-native-blob-util.git", ```
3. try other path for fileZipPath, e.g : `ReactNativeBlobUtil.fs.dirs.DocumentDir`  
4. add request permission
```
 PermissionsAndroid.request(
      PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE,
    );
```

**Comment by RonRadtke** [comment]
Are you still running in the problem?
It seems like an issue with the type cast due to an unexpected response type

**Comment by robyhuzwandar** [comment]
> RonRadtke

the problem is didn't call addAndroidDownloads

**Comment by priyanshi-zepto** [comment]
using `react-native-blob-util: 0.14.0` and getting the same issue, though sometimes it work
not sure what could be the issue
@robyhuzwandar were you able figure it out?

**Comment by RagavendraM** [comment]
@RonRadtke I tried debugging inside package, for specific request where file downloaded properly, 

Response :

**result = {ReactNativeBlobUtilFileResp@32301}** 
 bytesDownloaded = 0
 isEndMarkerReceived = false
 mPath = "/storage/emulated/0/Download/CashKaro_CashOut_703430.pdf"
 mTaskId = "8yiyepw5hou3gg5mvge9jc"
 ofStream = {FileOutputStream@32319} 
 **originalBody = {RealResponseBody@32320} okhttp3.internal.http.RealResponseBody@80900c6**
 rctContext = {ReactApplicationContext@32226} 
 reader = null
 shadow$_klass_ = {Class@32200} "class com.ReactNativeBlobUtil.Response.ReactNativeBlobUtilFileResp"
 shadow$_monitor_ = 0 

For Not downloadable Response: 

**result = {RealResponseBody@32538} okhttp3.internal.http.RealResponseBody@8e18f6b**
 contentLength = -1
 contentTypeString = "application/vnd.api+json"
 source = {RealBufferedSource@32555} buffer(okio.GzipSource@27e80e3)
 reader = null
 shadow$_klass_ = {Class@27820} "class okhttp3.internal.http.RealResponseBody"
 shadow$_monitor_ = -1998483605


so ClassCast Exception occurs.

**Comment by timosofokus** [comment]
I'm facing the same issue. Randomly some files return Error: Unexpected FileStorage response file: null

Was there a proper solution or a way to debug this more?
Testing with real Android 11 device, react-native 0.68.5 and react-native-blob-util 0.17.1. Tried to upgrade react-native-blob-util to later versions but did not help. Prod builds that were done before I entered into this particular project download all files correctly without any problems. Problems exist when I try to run this for development

Here's the part that uses blog-util

`async function streamFile(config: ReactNativeBlobUtilConfig, url: string, headers: any): Promise<FetchBlobResponse> {
  return new Promise((resolve, reject) => {
    RNFetchBlob.config(config)
      .fetch('GET', url, headers)
      .then(output => resolve(output))
      .catch(reject);
  });
}`

Url is a correct one and headers are empty. Config is as follows:

`const downloadConfig: ReactNativeBlobUtilConfig = {
          path: asset.tempDir,
          overwrite: false,
          fileCache: true,
          appendExt: extension,
};`

**Comment by itodevio** [comment]
Running to the exact same issue... looking through ReactNativeBlobUtilReq.java, the issue really seems to be the type cast from here:

```
try {
    ReactNativeBlobUtilFileResp = (ReactNativeBlobUtilFileResp) responseBody;
} catch (ClassCastException ex) {
```

and it's throwing an exception, which then checks:

```
try {
  boolean isBufferDataExists = responseBody.source().buffer().size() > 0;
  boolean isContentExists = responseBody.contentLength() > 0;
  
  if (isBufferDataExists && isContentExists) {
      responseBodyString = responseBody.string();
  }
} catch (IOException exception) {
  exception.printStackTrace();
}
```

I logged both `isBufferDataExists` and `isContentExists`, which were, in order, false and true.
The error happens with some files, then if I run again it may happen with others, so I guess it's not a problem with my files.

This issue was closed but how can I fix the error?

**Comment by YASH6004** [comment]
i am facing this issue again in 

 "react-native-blob-util": "^0.19.9",
  "react-native": "0.73.6",
  
  
  `export const exportClientData = async (type: 'all' | 'single', client_id?: string) => {
    let filepath = '';
    let url = '';

    if (type === 'all') {
        url = `https://...`;
    } else if (type === 'single') {
        url = `https:///.......`;
    }

    // Get the app's cache directory
    const { fs } = ReactNativeBlobUtil;
    const cacheDir = Platform.OS === 'ios' ? fs.dirs.DocumentDir : fs.dirs.LegacyDownloadDir;

    // Define the filename
    const filename = 'filename';

    // Construct the full filepath
    if (type === 'all') {
        filepath = `${cacheDir}/${filename}/ClientData.zip`;
    } else if (type === 'single') {
        filepath = `${cacheDir}/${filename}/${client_id}.zip`;
    }

    try {
        // // Ensure the directory exists
        // const dirPath = `${cacheDir}/${filename}`;
        // const isDir = await fs.isDir(dirPath); // Check if the directory exists

        // if (!isDir) {
        //     await fs.mkdir(dirPath); // Create the directory if it does not exist
        // }

        // Download the file and save it to the cache directory
        const configOptions:any = Platform.select({
            ios: {
                fileCache: true,
                path: filepath,
                appendExt: 'zip',
            },
            android: {
                fileCache: true,
                path: filepath,
                appendExt: 'zip',
            },
        });

        const response = await ReactNativeBlobUtil.config(configOptions).fetch('GET', url, {
            "Accept": "*/*",
            "Accept-Encoding": "*/*",
        });
        console.log('response==>>', JSON.stringify(response, undefined, 4));
        return response;
    } catch (error) {
        console.error('error in downloading==>', error);
        return error;
    }
};
  
  
  `
