### ISSUE TITLE
Android: lastModified header from res.info() mismatches final lastModified on device

### ISSUE THREAD

**Issue by michaelkoelewijn91** [RonRadtke/react-native-blob-util#142]
Hello,
I am running into an issue and i am unable to trace any information about this in the documentation or issue list.
On Android i am running a basic download function (see below) which fetches and moves the file to the device.
My finding is that the date-modified is not respected when the file is downloaded.

Logging the info of the response shows that the date-modified field is correct. Getting the date-modified directly after that using a fs.stat function shows the date the file has been downloaded.

Am i missing something or is this a bug in the code?

**Running:**
```
Android 9 on a real device
"react-native": "0.64.3",
"react-native-blob-util": "^0.15.0",
```

Using the code below results in the following output:
```
 LOG  Date last modified from response: Sun, 30 Jun 2019 05:58:06 GMT
 LOG  Date last modified from file on device: Fri Apr 08 2022 12:30:52 GMT+0200 (CEST)
 ```

```javascript
 useEffect(() => {
        const destination = `${ReactNativeBlobUtil.fs.dirs.SDCardDir}/test`
        ReactNativeBlobUtil
            .config({
                path: `${destination}/image.jpg`,
            })
            .fetch('GET', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Big_Buck_Bunny_first_23_seconds_1080p.ogv/320px--Big_Buck_Bunny_first_23_seconds_1080p.ogv.jpg')
                .then(res => {

                    console.log(`Date last modified from response: ${res.info().headers["last-modified"]}`)

                    ReactNativeBlobUtil.fs.stat(res.path())
                    .then((stats) => {
                        console.log(`Date last modified from file on device: ${Date(stats.lastModified)}`)
                    })
            })
        
    }, [])
```

**Comment by RonRadtke** [comment]
You're comparing the last modified of a file on the web server with a file on your device.
The file is created new on your device and than it's content being written into that file.
You're not copying the file form one harddrive to another, so it is correct that the modified date on your device is more or less equal to the creation time.

**Comment by michaelkoelewijn91** [comment]
Thanks for getting back to me @RonRadtke.
My client explicitly needs the date modified time from the server response as the date modified of the file on the device it gets downloaded to due to synchronisation to other devices.
Is this not possible then within the realms of this package?

**Comment by RonRadtke** [comment]
Currently that is not possible with this library, no.
Probably we could do so for media store by modifying the library or better implementing new possibilities to modify file attributes.
E.g. for media provider it is relatively simple to set this information:
https://github.com/RonRadtke/react-native-blob-util/blob/189e7664c831dc209495ec755baac9ffb5e02760/android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilMediaCollection.java#L91
