### ISSUE TITLE
IOS: How to configure the download and share options?

### ISSUE THREAD

**Issue by marry1822** [RonRadtke/react-native-blob-util#148]
Hey! My question is: can we somehow configure the list of options available for the file sharing and downloading?
For example, I only want to have "Save to files" option available when downloading the file. How to disable "Copy" and "Quick view" options?

Also I would like to disable "share with AirDrop" and all social networks. 
Is it possible?

Thanks!

![IMG_789D93C1D7FD-1](https://user-images.githubusercontent.com/63728225/165314899-b8273bf3-e174-4ffe-aa89-0faf176ae285.jpeg)

**Comment by RonRadtke** [comment]
There is no possibility to control the options available. These are defined by the OS based on installed apps, file type and preferences of the user

**Comment by marry1822** [comment]
> There is no possibility to control the options available via your app or this lib. These are defined by the OS based on installed apps, file type and preferences of the user

Thank's for the reply!

What are the preferences of the user?

I have an example: when I download the image, it is successfully saved "To files", but for some reason "Save image" option doesn't work, I can't see it in the gallery. What could be the reason?

**Comment by RonRadtke** [comment]
A user can add or remove certain options in the settings. So like adding facebook as a share option or so.

Not quite sure, do you get any error message or so? Don't really have any idea why it shouldn't work if you can otherwise save the file to your apps directory and open it from there (so the file itself being ok)

**Comment by marry1822** [comment]
> A user can add or remove certain options in the settings. So like adding facebook as a share option or so.

That's what I need, how can I do that? Is there a guide or something like that?

> Not quite sure, do you get any error message or so? Don't really have any idea why it shouldn't work if you can otherwise save the file to your apps directory and open it from there (so the file itself being ok)

There is an error. 
<img width="863" alt="1" src="https://user-images.githubusercontent.com/63728225/165700818-9e326625-87b4-4796-8949-35f9a46584db.png">


And I have another issue, when I see this window for the first time and there is the preview of the file I want to download, even if I don't press any button like "Save to files" or others, the file has already downloaded to the file system. It looks like the download happens at the moment when the window appears
![IMG_3301](https://user-images.githubusercontent.com/63728225/165701981-c7e61588-eb89-40f3-998b-14abb91c2957.jpg)

**Comment by RonRadtke** [comment]
> That's what I need, how can I do that? Is there a guide or something like that?
https://www.iphonelife.com/content/how-to-rearrange-app-icons-share-tab
> There is an error.
Sadly not really helpful to find the problem. Maybe you can see more when trying to investigate in xcode what exactly is throwing the error or what the error message is

> And I have another issue, when I see this window for the first time and there is the preview of the file I want to download, even if I don't press any button like "Save to files" or others, the file has already downloaded to the file system. It looks like the download happens at the moment when the window appears
Could you share your code? If you're using file cache a file is created for the image. And if you have sharing enabled then this cached file might show up in the files app

**Comment by marry1822** [comment]
> Could you share your code? If you're using file cache a file is created for the image. And if you have sharing enabled then this cached file might show up in the files app

`const downloadFile = async (fileUrl, fileExt, fileName) => {
    const {
      dirs: {DownloadDir, DocumentDir},
    } = ReactNativeBlobUtil.fs;
    const {config} = ReactNativeBlobUtil;
    const isIOS = Platform.OS == 'ios';
    const aPath = Platform.select({ios: DocumentDir, android: DownloadDir});
    const fPath = `${aPath}/${fileName}${fileExt}`;

    const configOptions = Platform.select({
      ios: {
        fileCache: true,
        path: fPath,
        notification: true,
      },
      android: {
        fileCache: false,
        addAndroidDownloads: {
          useDownloadManager: true,
          notification: true,
          path: fPath,
          description: 'Downloading...',
        },
      },
    });
    if (isIOS) {
      config(configOptions)
        .fetch('GET', fileUrl)
        .progress((received, total) => {
          console.log('progress', received / total);
        })
        .then(res => {
          setTimeout(() => {
            ReactNativeBlobUtil.ios.previewDocument(res.path());
          }, 300);
        })
        .catch(errorMessage => {
          console.log(errorMessage);
        });
    } else {
      config(configOptions)
        .fetch('GET', fileUrl)
        .then(res => {
          ReactNativeBlobUtil.android.actionViewIntent(res.path());
        })
        .catch((errorMessage, statusCode) => {
          console.log(errorMessage);
        });
    }
  };`


> https://www.iphonelife.com/content/how-to-rearrange-app-icons-share-tab

Thank you!

**Comment by RonRadtke** [comment]
You're using the fileCache for iOS.
Are you using
UIFileSharingEnabled and LSSupportsOpeningDocumentsInPlace?
If yes, the files generated for the file cache would be shared and thus be visible in the files app.

**Comment by marry1822** [comment]
> You're using the fileCache for iOS. Are you using UIFileSharingEnabled and LSSupportsOpeningDocumentsInPlace? If yes, the files generated for the file cache would be shared and thus be visible in the files app.

Should I set fileCache to false?

UIFileSharingEnabled - I don't use this option
LSSupportsOpeningDocumentsInPlace - this one ie set to YES in xcode

**Comment by RonRadtke** [comment]
It would be worth a try if you don't want the file to show up in the files app.

**Comment by marry1822** [comment]
> It would be worth a try if you don't want the file to show up in the files app.

Got it, thank you a lot!

**Comment by marry1822** [comment]
> It would be worth a try if you don't want the file to show up in the files app.

Hey! For some reason setting fileCache to false didn't help. The file appears in the folder before I download it.
Do you have any any other suggestions?
