### ISSUE TITLE
ReactNativeBlobUtil.copyToInternal is not a function on IOS

### ISSUE THREAD

**Issue by cloudworkpro-hassen** [RonRadtke/react-native-blob-util#149]
* please provide the version of installed library and RN project.
- "react-native-blob-util": "^0.15.0",
-  "react-native": "0.67.2",

* a sample code snippet/repository is very helpful to spotting the problem.
`  const dirToFiles = ReactNativeBlobUtil.fs.dirs.DocumentDir + '/' + file.name; `
`await ReactNativeBlobUtil.MediaCollection.copyToInternal(file.uri, dirToFiles);` 

console.log(file.uri) 
`'file:///private/var/mobile/Containers/Data/Application/CEA2ECD6-B04B-4700-B18C-41FBB3183403/tmp/com.cloudworkpro.mobile-Inbox/4dayseriousmass.pdf',`

* issues which have been tagged as 'needs feedback', will be closed after 2 weeks if receive no feedbacks.
* issues lack of detailed information will be closed without any feedback

Hello there, I am trying to use copyToInternal method on iOS.
On android, it seems to work as expected but on IOS I keep getting this error.

`TypeError: ReactNativeBlobUtil.copyToInternal is not a function. (In 'ReactNativeBlobUtil.copyToInternal(contenturi, destpath)', 'ReactNativeBlobUtil.copyToInternal' is undefined)`

**Comment by cloudworkpro-hassen** [comment]
That makes sense,
so what do you think is the best solution for IOS then?

**Comment by RonRadtke** [comment]
Depends on what you're wanting to do. In general you should not need such a functionality on iOS side.
On iOS you should not run into any problems using the fileURI you're getting e.g. form a picker. the issue on android is just that the URI might change, especially after app restart etc

**Comment by cloudworkpro-hassen** [comment]
so I am trying to do 2 things
1. Download documents when online, so we can have the path to those saved documents and have them available offline 
2. Upload documents to a temp folder while offline, so then we can send them through the api when back online

**Comment by RonRadtke** [comment]
1) These you can simply download using ``ReactNativeBlobUtil.fetch()``
2) using ``ReactNativeBlobUtil.fs.cp()`` should be sufficient for that on iOS. Assuming you want to copy the file from e.g. documents into your apps own storage (since uploading to a server won't work when offline)

**Comment by cloudworkpro-hassen** [comment]
So I was able to utilize fetch to download docs and it works great!
now my issue when trying to utilize fs.cp() I get an error
`Error: The file “Intro%20To%20Agile%20&%20Scrum%20ver%201.01.pdf” couldn’t be opened because there is no such file.`

this is how my method looks so far

`  const dirToFiles = ReactNativeBlobUtil.fs.dirs.DocumentDir + '/' + file.name;`
`  try {`
`    if (Platform.OS === 'ios') {`
`      await ReactNativeBlobUtil.fs.cp(file.uri, dirToFiles);`
`    } else {`
`      await ReactNativeBlobUtil.MediaCollection.copyToInternal(file.uri, dirToFiles);`
`    }`
`  } catch (e) {`
`    throw new Error(`saveToDirFiles error ${e}`);`
`  }`

**Comment by RonRadtke** [comment]
How do you get the file? Seems like the system can't find the file, not sure if that is a problem with the spaces and special signs in the name or if there is a general issue somewhere.
But the function call seems ok

**Comment by cloudworkpro-hassen** [comment]
Thats what I assumed too but then I tried a doc that had no spaces or special characters and I get the same error.
I am getting the File from my IOS device from the Files folder

**Comment by RonRadtke** [comment]
Please try to do a ``.replace('file://', '')'`` on the path for iOS to remove the ``file://`` prefix.

**Comment by cloudworkpro-hassen** [comment]
Dude you're a legend!!
it worked lol

**Comment by budo60** [comment]
Hello, Im tryin to do the same thing, but i can't find my file in the App Files of my Iphone

![image](https://user-images.githubusercontent.com/15154713/165539742-2cb738cf-28f1-4bb4-bb56-2813d07bf004.png)

i download with fetch from uri like this

http://myuri/F19072019063416.pdf (can't share real uri)

  downloadFile = async (file) => {
   
    ReactNativeBlobUtil.config({
      fileCache: true,
      //appendExt: 'pdf',
      // by adding this option, the temp files will have a file extension
      // appendExt: 'png'
    })
      .fetch('GET', file, {
        //some headers ..
      })
      .then(async (res) => {
        // the temp file path with file extension `png`

        console.log(res.path());
        //console.log(file);
        const dirTofiles =
          ReactNativeBlobUtil.fs.dirs.DocumentDir + '/testz.pdf';
        try {
          await ReactNativeBlobUtil.fs
            .cp(res.path(), dirTofiles);
        } catch (e) {
          console.log('error save --->', e);
        }
        
      });
  };

res.path() : 

/var/mobile/Containers/Data/Application/EBB6FE23-8126-42FC-B0E7-6DFF5E74D6E0/Documents/ReactNativeBlobUtil_tmp/ReactNativeBlobUtilTmp_n3fgqxifpdhj05yq61woqp

what am i doin wrong ?

**Comment by RonRadtke** [comment]
In order to see the files in the file app you need to share the files.
I explained it here: https://github.com/RonRadtke/react-native-blob-util/issues/62#issuecomment-1023583637

I teally have to write it up somewhere in the wiki once 😀

**Comment by RonRadtke** [comment]
No if you store the file in the documents directory you should be able to see it then.
Where are you storing the files within your app?

**Comment by budo60** [comment]
So this is what i have right now 

file == http://myuri/F19072019063416.pdf 

i have  this in info plist 

<key>LSSupportsOpeningDocumentsInPlace</key>
<true/>

<key>UIFileSharingEnabled</key>
<true/>

downloadFile = async (file) => {
    let dirs = ReactNativeBlobUtil.fs.dirs;

    await ReactNativeBlobUtil.config({
      fileCache: true,
      path: dirs.DocumentDir + '/monFichierz.pdf',
      appendExt: 'pdf',
      // by adding this option, the temp files will have a file extension
      // appendExt: 'png'
    })
      .fetch('GET', file, {
        //some headers ..
      })
      .then(async (res) => {
        // the temp file path with file extension `png`

        console.log(res.path());
        //console.log(file);
        const dirTofiles = dirs.DocumentDir + '/monFichz.pdf';
        try {
          let copy = await ReactNativeBlobUtil.fs.cp(res.path(), dirTofiles);
          console.log('copyyy', copy);
        } catch (e) {
          console.log('error save --->', e);
        }
      });
  };
i render this

 <TouchableOpacity
      key={3}
      onPress={() => {
        //console.log(1);
        //this.setState({canAccept: false});
        this.downloadFile(this.state.urlPdf);
       
      }}
      style={{
        ...
      }}>
      <Icon
        key={1 + '_ico'}
        name="download"
        style={{
          color: 'white',
          marginLeft: 10,
        }}
        size={20}
      />

      <Text
        style={{
          ...
        }}>
        {'Telecharger'}
      </Text>
  </TouchableOpacity>

what should i do to download my file from my uri (file in my example) when i click my button and be able to see it in App Files of the phone, is it possible to get a working example of what i need  ? please im stuck with this :'(

**Comment by RonRadtke** [comment]
In the thread  I liked is a working example of someone else:
https://github.com/RonRadtke/react-native-blob-util/issues/62#issuecomment-1023584653
