### ISSUE TITLE
Create a blob from file picked by ImagePicker

### ISSUE THREAD

**Issue by thelazyoxymoron** [RonRadtke/react-native-blob-util#150]
React Native version: `0.64.3`
Expo SDK: `44`
React-native-blob-util version: `0.15.0`

I'm trying to use `ReactNativeBlobUtil.fetch` to get the local video file picked by [ImagePicker](https://docs.expo.dev/versions/latest/sdk/imagepicker/) and then get the blob from the result. I was using React native's default `fetch` to do that, but facing the dreaded error `Network Request Failed` on android (see [#30176](https://github.com/facebook/react-native/issues/30176)).

Somebody recommended this library as an alternative and I'm trying to integrate this into the project but when I try to do the following function call, it fails with an error.

```
let uri = file:///data/user/0/com.testing.myproject/cache/ImagePicker/e2f19beb-fa6b-4ee3-9a78-8bf34f41ed9b.mp4
const result = await ReactNativeBlobUtil.fetch('GET', ReactNativeBlobUtil.wrap(uri))
```

**Error:** 
```
_stateChange is not a function. (In '_stateChange(info)', '_stateChange' is undefined)
at node_modules/react-native-blob-util/fetch.js:104:23 in fs.stat.then.then$argument_0
```

Am I doing something fundamentally wrong here? I took a look at the docs and saw that the 2nd argument needs to be `http` or `https`, but don't see anything regarding how to specify a local file address (the closest I got was doing a `wrap`). The following call used to work in React Native's default `fetch` for small files, but failed for files > 100 MB.

```
let uri = file:///data/user/0/com.testing.myproject/cache/ImagePicker/e2f19beb-fa6b-4ee3-9a78-8bf34f41ed9b.mp4
const result = await fetch(uri)
const blob = await result.blob() 
```

Any help here would be really appreciated!

**Comment by thelazyoxymoron** [comment]
Related [#633](https://github.com/joltup/rn-fetch-blob/issues/633)

**Comment by burzacoding** [comment]
Hi, I've been using this library and discovered two things:
- The fetch will fail on Android if you type any number, everything should be a string in the payload.
- ImagePicker appends `file://` at the start of the URI, in order for RNBlobUtil.wrap() to work just apply uri.replace("file://", "") and it should work as a `multipart/form-data` payload

**Comment by lclarkg18** [comment]
Thanks @burzacoding your comments were very helpful and guided my debugging process well. .replace("file://", "") was necessary but in the end I found that you don't really need to use react-native-blob-util once a file comes from react-native-image-picker or similar if you simply lay out the fields correctly with FormData as you [and others have mentioned](https://stackoverflow.com/questions/56235286/react-native-post-form-data-with-object-and-file-in-it-using-axios).
