### ISSUE TITLE
TypeError: null is not an object (evaluating 'ReactNativeBlobUtil.DocumentDir')

### ISSUE THREAD

**Issue by loupmasneri** [RonRadtke/react-native-blob-util#157]
I am using react-native-blob-util because rn-fetch-blob has not been updated since 5 years ago and I have this error which happens with rn-fetch-blob too:

`TypeError: null is not an object (evaluating 'ReactNativeBlobUtil.DocumentDir')`

I am using react-native 0.68.1 and this only happened on android and not iOS.

If someone has already faced the issue.

"react-native": "0.68.1",
"react-native-blob-util": "^0.16.0",

**Comment by filiptdz** [comment]
I'm also seeing this issue. Strangely, the problem only happens when I run `react-native run-android` for an emulator, but install the resulting build to another. Installing to the initial emulator works fine.

**Comment by rusty120** [comment]
I encountered this as well. It looks like auto linking isn't configured properly for android. I believe to fix this, `react` and `react-native` need to be added as dev and peer dependencies to this project. Something like this:

```
    "devDependencies": {
        ...
        "react": "16.13.1",
        "react-native": "^0.68.2"
    },
    "peerDependencies": {
        "react": "*",
        "react-native": "*"
    }
```

To work around this before it's fixed, you can configure [manually linking](https://github.com/RonRadtke/react-native-blob-util/wiki/Manually-Link-Package#index).  Of course, those instructions aren't quite right either. They reference the old class and package names. Rename `:react-native-fetch-blob` to `:react-native-blob-util` and `com.RNFetchBlob.RNFetchBlobPackage` to `com.ReactNativeBlobUtil.ReactNativeBlobUtilPackage` and you should be good.

**Comment by filiptdz** [comment]
fyi the repo I'm working on has an unconventional setup, but ai fixed this issue by running `react-native bundle`

**Comment by RonRadtke** [comment]
Can you confirm it's working with the peerDependencies? @rusty120  @filiptdz 
Porlbme is I wasn't able so far to reproduce it myself

**Comment by filiptdz** [comment]
@RonRadtke My best guess is this isn't a problem caused by this library, but instead any other issue that causes the React Native bundler not to resolve the native modules. A good solution might be to update it not to crash when the native module isn't found, so people aren't drawn to the conclusion that there may be a problem with this library

**Comment by rusty120** [comment]
@RonRadtke I can confirm the changes above resolve the issue for me. I pulled the repo and tested it locally. I ended up simply going with manual linking however to avoid having to fork the repo in the short term. If you use `npx create-react-native-library ...` to create a new node modules you'll notice the template includes `react` and `react-native` as peer dependencies, so I'm pretty sure they should be there.

I suspect the issue doesn't happen if you have `react-native` installed globally or use `npx react-native bundle` to build, which is maybe why not as many people have been tripped up by this?

**Comment by AlixH** [comment]
I have the same issue with react-native-blob-util 0.13.7 and react native 0.64.3
I don't understand why it occurs without updating anything. It was working before

**Comment by ethankong113** [comment]
I tried both adding `peerDependencies` and manually linking.. neither works for me. Maybe it's because I'm using expo

**Comment by RonRadtke** [comment]
The library doesn't work with expo since it is using native code

**Comment by 403access** [comment]
Hey together,

had some problems with react-native-pdf which is relying on this library as it seems.

Anyhow, whoever uses Expo might be interested in how to run native code - might help resolving your issues:
https://github.com/wonday/react-native-pdf/issues/624#issuecomment-1367842701

**Comment by alfergus0n** [comment]
This is still occurring, running on RN .70+ Just recently switched to this library from fetch, and i get undefined galore. I don't understand why not include RN dependencies if it is a RN package, if it resolves it?
