### ISSUE TITLE
ReactNativeBlobUtil.fs.stat() fails when passed a directory content URI

### ISSUE THREAD

**Issue by maciejewiczow** [RonRadtke/react-native-blob-util#160]
Hi ! Thank you for reporting an issue, but we would like to remind you, we have a trouble shooting page in our wiki. 
You may want to take a look on that page or find issues tagged "trouble shooting" :p (done)

* please provide the version of installed library and RN project. **react-native: 0.68.2, react-native-blob-util: 0.16.0**
* a sample code snippet/repository is very helpful to spotting the problem.

I am trying to stat a directory by its content uri to get its real path. Stat call fails with `failed to stat path "null" because it does not exist or it is not a folder`. The URI looks like this `content://com.android.externalstorage.documents/tree/primary:Movies/VLC`.

My code looks like this:
```ts
const opts: DocumentPickerOptions<SupportedPlatforms> = {
    presentationStyle: 'fullScreen',
    type: 'application/octet-stream',
};

try {
    if (Platform.OS === 'android') {
        const res = await PermissionsAndroid.requestMultiple([
            PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE,
            PermissionsAndroid.PERMISSIONS.READ_EXTERNAL_STORAGE,
        ]);

        if (Object.values(res).find(status => status !== 'granted')) {
            console.log('permission denied', res);
            return;
        }
    }
    
    const directory = await pickDirectory(opts);

    if (!directory)
        return;

    directory.uri = decodeURIComponent(directory.uri);

    console.log(directory);

    await ReactNativeBlobUtil.fs.stat(directory.uri);
} catch (e) {
    console.log(e)
}
```
The `pickDirectory` is a function from [react-native-document-picker](https://github.com/rnmods/react-native-document-picker)

I've added needed permission to the `AndroidManifest` file and also enabled `android:requestLegacyExternalStorage="true"`.
```xml
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
```

Please help, as I do not know any other way to get a directory real path. The stat call completes successfully when content 
URI points at a file.

**Comment by RonRadtke** [comment]
Fixed in the last release
