### ISSUE TITLE
IOS download document problem

### ISSUE THREAD

**Issue by MuratAkbaba006** [RonRadtke/react-native-blob-util#161]
Hi, I try to download file in ios but I can't see file. in Andriod everthing OK.
my versions:
"react-native": "^0.68.2",
"react-native-blob-util": "^0.16.0",

this my download function
`async function handleDownload(val) {
      try {
        const fileExtension = val.workorderDocumentUrl.split('.')[1];
        const fileName = `/${val.workorderDocumentName}.${fileExtension}`;

        const {workorderDocumentGuid, workorderDocumentName} = val;

        const configOptions = Platform.select({
          ios: {
            fileCache: true,
            path: ReactNativeBlobUtil.fs.dirs.DocumentDir + fileName,
            notification: true,
            IOSDownloadTask: true,
          },
          android: {
            fileCache: false,
            addAndroidDownloads: {
              useDownloadManager: true,
              notification: true,
              path: ReactNativeBlobUtil.fs.dirs.DownloadDir + fileName,
              description: 'Downloading...',
            },
          },
        });
        if (Platform.OS === 'ios') {
          ReactNativeBlobUtil.config(configOptions)
            .fetch(
              'GET',
              `${store.baseUrl}/docs?guid=${workorderDocumentGuid}`,
              {
                'accept-version': 'v3',
                'inavitas-tenant': store.tenant,
              },
            )
            .progress((received, total) => {
              console.log('PROGRESS', received, total);
            })
            .then(res => {
              setTimeout(() => {
                var filePath = res.path();
                ReactNativeBlobUtil.ios.presentPreview('file://' + filePath);
                console.log('RESIOS', res);
                //ReactNativeBlobUtil.ios.openDocument(res.data);
              }, 300);
              // the temp file path
              console.log('The file saved to ', res.path());
              setSuccessDownload(true);
              console.log('DIRS', ReactNativeBlobUtil.fs.dirs);
            })
            .catch(err => console.log('download Err', err));
        } else {
          ReactNativeBlobUtil.config(configOptions)
            .fetch(
              'GET',
              `${store.baseUrl}/docs?guid=${workorderDocumentGuid}`,
              {
                'accept-version': 'v3',
                'inavitas-tenant': store.tenant,
              },
            )
            .then(res => {
              ReactNativeBlobUtil.android.actionViewIntent(res.path());
              // the temp file path
              console.log('The file saved to ', res.path());
              setSuccessDownload(true);
              console.log('DIRS', ReactNativeBlobUtil.fs.dirs);
            })
            .catch(err => console.log('download Err', err));
        }
      } catch (err) {
        console.log(err);
      }
    }`

Here is my debug console, I can see directory && process 
<img width="814" alt="Screen Shot 2022-06-03 at 11 21 58" src="https://user-images.githubusercontent.com/44754934/171817429-d0844bdc-b2c6-44f7-bf45-4fe1c4867c55.png">

**Comment by RonRadtke** [comment]
On iOS you won't be able to see the files in the Files app unless you share them

**Comment by ddikodroid** [comment]
> For iOS, you can use `react-native-share` once you download the file to save it to files.
> 
> ```
>   .then((res) => {
>         // the temp file path
>         console.log('The file saved to ', res.path());
>         // in iOS, we want to save our files by opening up the saveToFiles bottom sheet action.
>         // whereas in android, the download manager is handling the download for us.
>         if (Platform.OS === 'ios') {
>           const filePath = res.path();
>           let options = {
>             type: 'application/pdf',
>             url: filePath,
>             saveToFiles: true,
>           };
>           Share.open(options)
>             .then((resp) => console.log(resp))
>             .catch((err) => console.log(err));
>         }
>       })
> ```

or use this 
```js
ReactNativeBlobUtil.ios.previewDocument(file.path());
```

**Comment by Pavel-Tasits** [comment]
@Saad-Bashar hello! I tried to do as you suggested. the files began to appear in the recent ios folder. but they don't open properly
![Screenshot at Dec 04 14-50-23](https://github.com/RonRadtke/react-native-blob-util/assets/68384110/41ebe570-b2a1-427c-bd50-506e219a0886)
here is my code 
const downloadFile = async (file: IFile) => {
    const isGranted = await getPermissionDownloadImage();

    if (!isGranted) {
      toast.current?.show("Отсутствует разрешение на загрузку документов");
      return;
    }

    const url = `${ConnectionStore.api}longreads/file/${file.id}`;
    const headers = { Authorization: `Bearer ${keycloak.token}` };
    await ReactNativeBlobUtil.config({
      fileCache: true,
      path: `${RNFS[IS_IOS ? "DocumentDirectoryPath" : "DownloadDirectoryPath"]}/${file.fileName}.${file.extension}`,
    })
      .fetch("GET", url, headers)
      .progress(() => {
        setIsLoading((prev) => [...prev, file.id]);
      })
      .then((res) => {
        if (IS_IOS) {
          const filePath = res.path();
          const options = {
            type: `application/${file.extension}`,
            url: filePath,
            saveToFiles: true,
          };
          Share.open(options)
            .then(() => changeDownloadState(file.id))
            .catch(() => changeDownloadState(file.id, false));
        } else {
          changeDownloadState(file.id);
        }
      })
      .catch(() => {
        changeDownloadState(file.id, false);
      })
      .finally(() => setIsLoading((prev) => prev.filter((item) => item !== file.id)));
  };
would you help me?

**Comment by anniewey** [comment]
@Saad-Bashar i had the same problem, appending `.pdf` to the path fixes the problem for me

path: `${dirs.DocumentDir}/${fileName}.pdf`,

```
LOG  The file saved to  /Users/xx/Library/Developer/CoreSimulator/Devices/FEBCC312-3D3A-4C60-A008-49A488000139/data/Containers/Data/Application/6DE346D7-CC55-4E21-B9F5-1D9766E977EB/Documents/Resources-1701931717558
LOG  The file saved to  /Users/xx/Library/Developer/CoreSimulator/Devices/FEBCC312-3D3A-4C60-A008-49A488000139/data/Containers/Data/Application/6DE346D7-CC55-4E21-B9F5-1D9766E977EB/Documents/Resources-1701931752795.pdf
```

**Comment by truongnat** [comment]
Is there an update on this? I tried downloading the file xlsx in iOS, but it always returns the path simulator.

**Comment by Pavel-Tasits** [comment]
> Is there an update on this? I tried downloading the file xlsx in iOS, but it always returns the path simulator.

I don't know if this is the right solution, but I managed to solve the problem using react-native-share

Share.open({
        url: urlPath,
        saveToFiles: true,
      })
urlPath is url returned by ReactNativeBlobUtil

**Comment by truongnat** [comment]
> > Is there an update on this? I tried downloading the file xlsx in iOS, but it always returns the path simulator.
> 
> I don't know if this is the right solution, but I managed to solve the problem using react-native-share
> 
> Share.open({ url: urlPath, saveToFiles: true, }) urlPath is url returned by ReactNativeBlobUtil

Thank you for your response,

I fixed the issue in iOS. I'm not sure why it didn't download, but I am using the react native file viewer to open it and it's working. The user will need to download a manual.

**Comment by jmada** [comment]
> For iOS, you can use `react-native-share` once you download the file to save it to files.
> 
> ```
>   .then((res) => {
>         // the temp file path
>         console.log('The file saved to ', res.path());
>         // in iOS, we want to save our files by opening up the saveToFiles bottom sheet action.
>         // whereas in android, the download manager is handling the download for us.
>         if (Platform.OS === 'ios') {
>           const filePath = res.path();
>           let options = {
>             type: 'application/pdf',
>             url: filePath,
>             saveToFiles: true,
>           };
>           Share.open(options)
>             .then((resp) => console.log(resp))
>             .catch((err) => console.log(err));
>         }
>       })
> ```

The only way I've made it worked was using this approach.


> > For iOS, you can use `react-native-share` once you download the file to save it to files.
> > ```
> >   .then((res) => {
> >         // the temp file path
> >         console.log('The file saved to ', res.path());
> >         // in iOS, we want to save our files by opening up the saveToFiles bottom sheet action.
> >         // whereas in android, the download manager is handling the download for us.
> >         if (Platform.OS === 'ios') {
> >           const filePath = res.path();
> >           let options = {
> >             type: 'application/pdf',
> >             url: filePath,
> >             saveToFiles: true,
> >           };
> >           Share.open(options)
> >             .then((resp) => console.log(resp))
> >             .catch((err) => console.log(err));
> >         }
> >       })
> > ```
> 
> or use this
> 
> ```js
> ReactNativeBlobUtil.ios.previewDocument(file.path());
> ```

I've tried this too but it didn't work for me.
Thank you @Saad-Bashar !
