### ISSUE TITLE
How to handling data encapsulated in an object with an unique name

### ISSUE THREAD

**Issue by MartynFitzgerald** [RonRadtke/react-native-blob-util#163]
Hello, 

I'm currently trying to download documents from an API and store it on Android and iOS devices, however, I'm a little confused about the documentation. When I fetch the document from the API I have an object returned that has an attribute named "Base64Content" that has the data for the actual file. Would this affect the process and if so, should I add a certain attribute to the config to notify the fetch where to look for the data? 

Installed library and RN project.
* react-native: "0.64.3"
* react-native-blob-util: "0.16.0"

```JavaScript
 await ReactNativeBlobUtil.config(configOptions)
      .fetch('GET', 'api/Document/Download', {
          'x-x-domain': item.x.domain
      })
      .then(eData => {
        // the temp file path
        console.log('eData', eData);
        console.log('The file saved to ', eData.path());
        console.log('DIRS', ReactNativeBlobUtil.fs.dirs);

        setTimeout(() => {
          if (Platform.OS == 'ios'){ 
            ReactNativeBlobUtil.ios.presentPreview('file://' + eData.path());
          } else {
            ReactNativeBlobUtil.android.actionViewIntent(eData.path(), mime.lookup(item.FileExtension));
          }
        }, 300);
      })
      .catch(err => console.log(`Download '${ item.Filename ?? 'N/A' }' file`, err));
    }
```

**Comment by RonRadtke** [comment]
Just so I get it right.  Your API is returning a JSON and somewhere in that JSON is data you want to write into a file?

If so, you can't use this approach. You can use the normal react-native fetch to call your API, parse the JSON and then use writeFile to write the file data into a file. You can't tell react-native-blob-utils fetch method where to extract the data from, it will wrtie the whole body data into a file.

So sth like this:
```
let resp = await fetch('apu/Document/Download'),
dat = await resp.json();
RNFetchBlob.fs.writeFile('path_to_file', dat, 'base64');
```
