### ISSUE TITLE
Android crashing on download on first time (java.lang.ArithmeticException: divide by zero)

### ISSUE THREAD

**Issue by Saad-Bashar** [RonRadtke/react-native-blob-util#164]
Having this strange issue on android that it is crashing when I try to download my remote PDF file first time. It downloads the file but then the app crashes. It only happens on the first run but on subsequent call it does not crash anymore. Please refer to the screenshot for the crash stack. I have been using [BrowserStack](browserstack.com) devices. 

![Screenshot 2022-06-21 at 11 46 12 AM](https://user-images.githubusercontent.com/13269141/174712151-7585f4a4-9015-4f91-a029-8f02c7eb70fc.png)

This is my download file,
```
 const downloadFile = () => {
    let dirs = ReactNativeBlobUtil.fs.dirs;
    ReactNativeBlobUtil.config({
      fileCache: true,
      appendExt: 'pdf',
      path: `${dirs.DocumentDir}/${fileName}`,
      addAndroidDownloads: {
        useDownloadManager: true,
        notification: true,
        title: fileName,
        description: 'File downloaded by download manager.',
        mime: 'application/pdf',
      },
    })
      .fetch('GET', fileUrl)
      .then((res) => {
        // the temp file path
        console.log('The file saved to ', res.path());
        // in iOS, we want to save our files by opening up the saveToFiles bottom sheet action.
        // whereas in android, the download manager is handling the download for us.
        if (Platform.OS === 'ios') {
          const filePath = res.path();
          let options = {
            type: 'application/pdf',
            url: filePath,
            saveToFiles: true,
          };
          Share.open(options)
            .then((resp) => console.log(resp))
            .catch((err) => console.log(err));
        }
      })
      .catch((err) => console.log('BLOB ERROR -> ', err));
  };
```

"react-native": "0.66.4",
"react-native-blob-util": "^0.16.0",

**Comment by Saad-Bashar** [comment]
Update - After digging a lot, it seems like on android the download is getting called twice somehow on the first run? That might be reason for the crash. As for the other times, I do not get logs 2 times and it does not crash as well.

**Comment by RonRadtke** [comment]
What size does the file you're downloading has?
For me it looks like the expected file size is 0 and thus we get an error here.

You could try to add a check here: https://github.com/RonRadtke/react-native-blob-util/blob/8edbfc80dea109ccb1fe94d95984b9cd27708210/android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilReq.java#L200

E.g. by changing it to
float progress = (total > 0) ? written / total : 0;

Please give me a quick hint if it helps or not. So we can dig further or create a fix

**Comment by Saad-Bashar** [comment]
Thanks for your kind response! The file size was not 0 for sure, it had few KB. I will add that check and give it a go today and will update you!

**Comment by Saad-Bashar** [comment]
@RonRadtke , I believe adding that check fixed the crash! I could not reproduce the same crash anymore! Would you be kind enough to release an update soon with this small fix? Thanks a lot!

**Comment by RonRadtke** [comment]
Yes I will.
I was planning on an update thisnweek or beginning of next week regardless
