### ISSUE TITLE
fetch() gives SSL error on iOS, use of own trust manager but none defined on Android

### ISSUE THREAD

**Issue by reeinohio** [RonRadtke/react-native-blob-util#166]
rn-fetch-blob isn't working anymore when I upgraded to RN 0.67.4 and target/compile for android 12 (SDK 31).   Now, I am trying react-native-blob-util to replace rn-fetch-blob, however it is giving me an error during fetch call. The error I got is similar for both android or iOS.
On iOS I get: 
`[Error: An SSL error has occurred and a secure connection to the server cannot be made.]`
On Android I get:
`[Error: ReactNativeBlobUtil request error: java.lang.IllegalStateException: Use of own trust manager but none definedjava.lang.IllegalStateException: Use of own trust manager but none defined]`

Any ideas what maybe causing this or suggested changes i should do? 
Any input will highly appreciated. Thank you!

*   Library versions and config
    react-native-blob-util 0.16.0
    react-native 0.67.4
    Android build.gradle: Compile and target SDK: 31 
* Sample code
```
import ReactNativeBlobUtil from "react-native-blob-util";
import { Platform, PermissionsAndroid } from "react-native";

...
let allPermissionsGranted = false;
if (Platform.OS === "android") {
   const granted = await PermissionsAndroid.requestMultiple([
            PermissionsAndroid.PERMISSIONS.READ_EXTERNAL_STORAGE,
            PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE,
        ]);
   allPermissionsGranted =
            granted["android.permission.READ_EXTERNAL_STORAGE"] === "granted" && granted["android.permission.WRITE_EXTERNAL_STORAGE"] === "granted";
}
try {
  const res = await ReactNativeBlobUtil.config({
                trusty: true,
                fileCache: false,
                path: directory + "/" + filename,
            }).fetch("GET", docUrl, headers);
  const status = res.info().status;
  if (status === 200) {
      if (Platform.OS === "ios") {
          ReactNativeBlobUtil.ios.openDocument(res.path());
       } else {
           if (allPermissionsGranted) {
               const android = ReactNativeBlobUtil.android;
               android.actionViewIntent(res.path(), mimetype);
           }
         }
      }
    } else {
       console.log("Error fetching file");
       throw new Error("...")
    }
} catch (e) {
    console.error(e);
}
```

**Comment by RonRadtke** [comment]
Yes you're using trusty = true.
The implementation changed so you need to specify your own trustmanager for that.
Please check the readme to see how you can do that.

**Comment by timothyerwin** [comment]
it's failing in iOS on the simulator (v16) no matter what is set for trusty.

**Comment by msbit** [comment]
@RonRadtke did you consider using a system provided trust manager (something like [this][1]) instead of requiring the user to provide it?

[1]: https://stackoverflow.com/questions/31920719/getting-the-trusted-x509certificate-for-a-java-sslsocket#answer-31966871

**Comment by RonRadtke** [comment]
> @RonRadtke did you consider using a system provided trust manager (something like [this](https://stackoverflow.com/questions/31920719/getting-the-trusted-x509certificate-for-a-java-sslsocket#answer-31966871)) instead of requiring the user to provide it?
> 
> EDIT:
> 
> Disregard this, I'm troubleshooting an issue a couple of levels of dependencies deep, and I see that an intermediate dependency is setting the `trusty` flag, causing the error I'm seeing ✌️

So your problem is solved?

The reason I require the user to set it, is that in the past we had reports about denied apps due to it.
Google does a static code analysis and recognized a trust manager that just allows everything. And by that the app got denied.

**Comment by RonRadtke** [comment]
> @RonRadtke Request: I think there needs to be added an import on top of `MainApplication.java` in order to specify the trustmanager. Can this be added to the README how to do that..? And/or mention here in ticket. Thanks!

Yes I will fix that in the readme. There is also another issue about the trustmanager in the readme i habe to fix.

**Comment by msbit** [comment]
> So your problem is solved?

Yep, solved, thanks for checking in.

> The reason I require the user to set it, is that in the past we had reports about denied apps due to it. Google does a static code analysis and recognized a trust manager that just allows everything. And by that the app got denied.

Interesting! and a good thing to know for future submissions to the app stores 👍

**Comment by fwdillema** [comment]
> it's failing in iOS on the simulator (v16) no matter what is set for trusty.

For me too. Local server with self-signed cert. Got it working fine on Android, but on iOS I get:

"The certificate for this server is invalid. You might be connecting to a server that is pretending to be “10.10.10.10” which could put your confidential information at risk."

Any ideas?

**Comment by danishhusain** [comment]
> @RonRadtke Request: I think there needs to be added an import on top of `MainApplication.java` in order to specify the trustmanager. Can this be added to the README how to do that..? And/or mention here in ticket. Thanks!

Bro simply add this in  **trustAllCerts={false}**  

 <Pdf
        trustAllCerts={false}
        ref={pdfRef}
        source={{
          uri: 'http://samples.leanpub.com/thereactnativebook-sample.pdf',
          cache: true,
        }} // Replace with your Quran PDF URL or local file
        style={styles.pdf}
        onError={(error) => {
          console.log('PDF Error:', error);
          Alert.alert('Error', 'Failed to load PDF.');
        }}
        onPageChanged={(page, total) => {
          console.log(`Current page: ${page}/${total}`);
          setTotalPages(total); // Set the total pages when PDF loads
        }}
        onLoadComplete={(numberOfPages) => {
          console.log(`PDF loaded with ${numberOfPages} pages`);
          setTotalPages(numberOfPages);
        }}
      />

**Comment by dirkpostma** [comment]
> > @RonRadtke Request: I think there needs to be added an import on top of `MainApplication.java` in order to specify the trustmanager. Can this be added to the README how to do that..? And/or mention here in ticket. Thanks!
> 
> Bro simply add this in **trustAllCerts={false}** it will fix certificate issue.
> 
> <Pdf trustAllCerts={false} ref={pdfRef} source={{ uri: 'http://samples.leanpub.com/thereactnativebook-sample.pdf', cache: true, }} // Replace with your Quran PDF URL or local file style={styles.pdf} onError={(error) => { console.log('PDF Error:', error); Alert.alert('Error', 'Failed to load PDF.'); }} onPageChanged={(page, total) => { console.log(`Current page: ${page}/${total}`); setTotalPages(total); // Set the total pages when PDF loads }} onLoadComplete={(numberOfPages) => { console.log(`PDF loaded with ${numberOfPages} pages`); setTotalPages(numberOfPages); }} />

My request concerned an improvement of README file. I just checked: readme now has better instruction on setting up android, the line with import is added.
