### ISSUE TITLE
Autolinking does not work with React Native 0.69.0

### ISSUE THREAD

**Issue by Naturalclar** [RonRadtke/react-native-blob-util#169]
## Issue
Due to change in react-native cli, https://github.com/react-native-community/cli/pull/1537
Autolinking is no longer working with React Native 0.69

## Expected Behavior
React Native autolinking to work with react-native-blob-util

## Repro Steps:
Create a new React Native Project version 0.69
install react-native-blob-util
run pod install in ios directory
Notice that RNNotifications is not included in the Podfile.lock

* please provide the version of installed library and RN project.
RN: 0.69.0
react-native-blob-util: 0.16.0

* a sample code snippet/repository is very helpful to spotting the problem.
[Naturalclar/react-native-notifications-repro](https://github.com/Naturalclar/react-native-notifications-repro)

* issues which have been tagged as 'needs feedback', will be closed after 2 weeks if receive no feedbacks.
* issues lack of detailed information will be closed without any feedback

**Comment by RonRadtke** [comment]
Same as: https://github.com/RonRadtke/react-native-blob-util/issues/165
