### ISSUE TITLE
Build Failed on MacOS M1

### ISSUE THREAD

**Issue by taatiq882** [RonRadtke/react-native-blob-util#171]
After installation its giving this error

duplicate symbol '_bridgeRef' in: /Users/talhaatiq/Library/Developer/Xcode/DerivedData/mustaqbill-fhemmipxsgoadjbxflibshapgaaz/Build/Products/Debug-iphoneos/react-native-blob-util/libreact-native-blob-util.a(ReactNativeBlobUtil.o) /Users/talhaatiq/Library/Developer/Xcode/DerivedData/mustaqbill-fhemmipxsgoadjbxflibshapgaaz/Build/Products/Debug-iphoneos/rn-fetch-blob/librn-fetch-blob.a(RNFetchBlob.o) duplicate symbol '_fsQueue' in: /Users/talhaatiq/Library/Developer/Xcode/DerivedData/mustaqbill-fhemmipxsgoadjbxflibshapgaaz/Build/Products/Debug-iphoneos/react-native-blob-util/libreact-native-blob-util.a(ReactNativeBlobUtil.o) /Users/talhaatiq/Library/Developer/Xcode/DerivedData/mustaqbill-fhemmipxsgoadjbxflibshapgaaz/Build/Products/Debug-iphoneos/rn-fetch-blob/librn-fetch-blob.a(RNFetchBlob.o) duplicate symbol '_commonTaskQueue' in: /Users/talhaatiq/Library/Developer/Xcode/DerivedData/mustaqbill-fhemmipxsgoadjbxflibshapgaaz/Build/Products/Debug-iphoneos/react-native-blob-util/libreact-native-blob-util.a(ReactNativeBlobUtil.o) /Users/talhaatiq/Library/Developer/Xcode/DerivedData/mustaqbill-fhemmipxsgoadjbxflibshapgaaz/Build/Products/Debug-iphoneos/rn-fetch-blob/librn-fetch-blob.a(RNFetchBlob.o) duplicate symbol '_fileStreams' in: /Users/talhaatiq/Library/Developer/Xcode/DerivedData/mustaqbill-fhemmipxsgoadjbxflibshapgaaz/Build/Products/Debug-iphoneos/react-native-blob-util/libreact-native-blob-util.a(ReactNativeBlobUtilFS.o) /Users/talhaatiq/Library/Developer/Xcode/DerivedData/mustaqbill-fhemmipxsgoadjbxflibshapgaaz/Build/Products/Debug-iphoneos/rn-fetch-blob/librn-fetch-blob.a(RNFetchBlobFS.o) duplicate symbol '_expirationTable' in: /Users/talhaatiq/Library/Developer/Xcode/DerivedData/mustaqbill-fhemmipxsgoadjbxflibshapgaaz/Build/Products/Debug-iphoneos/react-native-blob-util/libreact-native-blob-util.a(ReactNativeBlobUtilNetwork.o) /Users/talhaatiq/Library/Developer/Xcode/DerivedData/mustaqbill-fhemmipxsgoadjbxflibshapgaaz/Build/Products/Debug-iphoneos/rn-fetch-blob/librn-fetch-blob.a(RNFetchBlobNetwork.o) ld: 5 duplicate symbols for architecture arm64 clang: error: linker command failed with exit code 1 (use -v to see invocation)

"react-native": "0.67.3",
"react-native-blob-util": "^0.16.2",

**Comment by anoopbk1989** [comment]
In Xcode, below your ProjectName, you have Pods. Click on Pods, and you will get list of components under **TARGETS**. Go to Build settings of both the components(react-native-blob-util and rn-fetch-blob) and set `No Common Blocks=No`

**Comment by ManosChr** [comment]
Before deleting rn-fetch-blob, you need to search for other package dependencies, otherwise it will be deleted from package.json file but not from node_modules folder.
1. Press npm list --depth=2 at project root folder and search for packages with dependency on rn-fetch-blob
2. In my case was redux-persist-filesystem-storage
3. Update redux-persist-filesystem-storage to latest version which depends on react-native-blob-util
4. npm uninstall rn-fetch-blob
