### ISSUE TITLE
[Android] Error when uploading file and server returns empty body

### ISSUE THREAD

**Issue by jpalumickas** [RonRadtke/react-native-blob-util#173]
Hello,

When we try to upload a file to a Cloudflare Stream with multipart form, on success server returns empty body and 200 status. File is uploaded successfully, but on response we get this error:
```
ReactNativeBlobUtil failed to encode response data to BASE64 string.
```

I think this is because somehow it tries to decode empty body and fails.

Example code:
```js
  const res = await ReactNativeBlobUtil.fetch(
    'POST',
    url,
    {
      'Content-Type': 'multipart/form-data',
      'RNFB-Response': 'utf8', // with or without this option also not working 
    },
    [
      {
        name: 'file',
        filename: file.name,
        type: file.type,
        data: ReactNativeBlobUtil.wrap(file.uri),
      },
    ]
  );

```

**Comment by grzegorzDlugokecki** [comment]
Hey @jpalumickas  I know it might not be related to your question but how did You manage to upload videos from RN app to Cloudflare? Do You maybe have some working example? Im getting "Decoding error" all the time ;(

**Comment by RonRadtke** [comment]
Could you test if the following works?
```
ReactNativeBlobUtil
            .config({
                fileCache: false,
                transformFile: false,
                path: null,
                auto: false
            })
            .fetch(...);
```

**Comment by rayhk6** [comment]
@jpalumickas Could you resolve the issue?

**Comment by jpalumickas** [comment]
as I now no longer using this lib to upload videos to Cloudflare Stream, I will close this issue, because I cannot test the solution
