### ISSUE TITLE
Upload files from mediastore

### ISSUE THREAD

**Issue by mlecoq** [RonRadtke/react-native-blob-util#177]
Hi, I am on Android I would like to upload avatar from device contacts to my own server

The uri format of the avatar is the following one

`content://com.android.contacts/contacts/27/photo`

To upload I am using the following code 

```
 await ReactNativeBlobUtil.fetch(
              'PUT',
              result.data.upload.signedUploadUrl,
              {'Content-Type': file.fileType},
              ReactNativeBlobUtil.wrap(file.original.replace(/^file:[/]+/, '/')) 
            )
```

First I thought that my mistake was adding `ReactNativeBlobUtil-file` as prefix of my uri but even if I check that prefix 

```
 await ReactNativeBlobUtil.fetch(
              'PUT',
              result.data.upload.signedUploadUrl,
              {'Content-Type': file.fileType},
              file.original.startWith('file')
                ? ReactNativeBlobUtil.wrap(file.original.replace(/^file:[/]+/, '/'))
                : file.original.replace(/^content:[/]+/, 'ReactNativeBlobUtil-content:'),
            );
```

I does not work (and when I look in fetch.js code it's easy to know why) 

Is there currently any way to handle this use case with react-native-blob-util ?

**Comment by RonRadtke** [comment]
Did you try using the mediacollectionAPI the library is offering you?
I would suggest trying to either copy it to the internal and treat it as a normal file or use the getBlob() function to get the file content as a blob and send it that way

**Comment by mlecoq** [comment]
Hi @RonRadtke thanks for your quick answer, 

for the moment I copy the file and it works fine 👍 I will try with `getBlob()`
