### ISSUE TITLE
Error: Download manager failed to download from  `URL`. Status Code = 16

### ISSUE THREAD

**Issue by ddikodroid** [RonRadtke/react-native-blob-util#178]
Hi ! Thank you for reporting an issue, but we would like to remind you, we have a trouble shooting page in our wiki. 
You may want to take a look on that page or find issues tagged "trouble shooting" :p 

* please provide the version of installed library and RN project.
* a sample code snippet/repository is very helpful to spotting the problem.
* issues which have been tagged as 'needs feedback', will be closed after 2 weeks if receive no feedbacks.
* issues lack of detailed information will be closed without any feedback

hi @RonRadtke 
first of all, thank you for maintaining this package. i got problem when i want to download docx file on android. 
on ios it's working as intended.

hope i can get insight. thanks!

version:
* react-native: 0.67.2
* react-native-blob-util: 0.16.2

code snippet:
```js
const config = {
  overwrite: true,
  fileCache: true,
  appendExt: 'docx',
  addAndroidDownloads: {
    useDownloadManager: true,
    notification: true,
    title: `Exporting ${filename}`,
    path: ReactNativeBlobUtil.fs.dirs.DownloadDir + '/' + filename,
    description: 'Downloading blueprint...',
    mediaScannable: true,
    mime:
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document', //docx
  },
};
ReactNativeBlobUtil.config(config)
  .fetch('GET', url)
  .then(file => {
    ReactNativeBlobUtil.android.actionViewIntent(
      file.path(),
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document', //docx
    );
    console.log(file);
  })
  .catch(error =>
    console.log('[ERROR] on export: ', error),
  );

```

tested on: google pixel 3 xl running android 12

error log:
```
[Error: Download manager failed to download from  <URL>. Status Code = 16]
```

**Comment by ddikodroid** [comment]
solved by wrapping my url with `encodeURI(url)`

**Comment by quicksilverr** [comment]
This also doesn't work.

**Comment by RonRadtke** [comment]
This inidcates the download failed within the download manager.A reason might for example be missing authentication, more details would be listed in the COLUMN_REASON or if you inspect all network traffic in the status code (don't think you the lib is exposing the reson of the underlaying doenloadmanaher instance) Get Outlook for Android

**Comment by Priyanshu0007** [comment]
I faced the same issue. In my case the url was in some case redirecting to some other url. So in order to fix this I have my first fetched  image url using fetch(I am using fetch) or any other method and get url from that then download url. This works fine and I didn't find this issue again. 

FYI:
If the url has redirection then fetch will give redirected url if no direction then fetch return same url.
