### ISSUE TITLE
Change the language of the "download to" options

### ISSUE THREAD

**Issue by marry1822** [RonRadtke/react-native-blob-util#182]
Hey! How can I change the language here? Now everything is in English, I want all options (Copy, Save to files etc.) in Russian, for example.

![image](https://user-images.githubusercontent.com/63728225/185565271-9936316c-d97b-46d3-9143-ac3046b4eb26.png)

**Comment by RonRadtke** [comment]
Hey,That is controlled by the device language, nothing you can do with the library.So you have to change the language of your device to the language you want to deeGet Outlook for Android

**Comment by marry1822** [comment]
You can see that the Ipad language is Russian, but the language of the options inside the app is English
<img width="666" alt="image" src="https://user-images.githubusercontent.com/63728225/185619433-69b882ac-ecf8-4c74-bc77-6d4daef53915.png">
<img width="384" alt="image" src="https://user-images.githubusercontent.com/63728225/185619479-3a05000b-dc76-41c2-a147-d735aeef54ff.png">

**Comment by marry1822** [comment]
> Hey,That is controlled by the device language, nothing you can do with the library.So you have to change the language of your device to the language you want to deeGet Outlook for Android

Please, check the screenshots above

**Comment by pnthach95** [comment]
You're running in debug mode, change development localization to your language in project info, localizations section

![Screen Shot 2022-09-19 at 9 34 14 PM](https://user-images.githubusercontent.com/31266357/191042936-69c15dae-0acb-413e-802a-b956a9b083dd.png)
