### ISSUE TITLE
Save file downloaded by axios

### ISSUE THREAD

**Issue by matheuswr89** [RonRadtke/react-native-blob-util#185]
I'm using the Axios library because I need to keep the user session; seeing as I was scrapping a website and required to download a file, and it kind of gets saved "corrupted," I'm doing it the second way:
```
 const response = await axios(url, options);
  const file = '/' + response.headers['content-disposition'].split('"')[1];
  console.log(ReactNativeBlobUtil.fs.dirs.DownloadDir + file);
  ReactNativeBlobUtil.fs.writeFile(
    ReactNativeBlobUtil.fs.dirs.DownloadDir + file,
    response.data
  );
```
Is it possible to save the file without it getting corrupted?

**Comment by matheuswr89** [comment]
> What's the problem with the session?
Cookie based sessions shouldn't be an issue.

The issue is not with the session itself, but rather with the site that each session changes some elements of the page that is necessary to be mapped to mount the download link, and if I try to access from outside the axios that is storing the session, I can not download the file.

> I would assume the data in response.data is the problem.
What encoding does it have? You might have to set the encoding correctly.

Response.data returns the binary source code of the PDF ([example](https://pastebin.com/QFJc2Rxx)), and I can't think of a way to save the PDF correctly.

**Comment by valery-lavrik** [comment]
I managed to implement it like this

```

import { Buffer } from 'buffer'; // It is not necessary to install. Already in RN

const RES = await axios.get(url, {
				headers,
				responseType: 'arraybuffer',
				maxBodyLength: Infinity,
				maxContentLength: Infinity,
				transitional: {
					silentJSONParsing: false,
					forcedJSONParsing: false,
				},
			});

			await RNFetchBlob.fs.writeFile(
				path,
				Buffer.from(RES.data, 'binary').toString('base64'),
				'base64'
			);
```

**Comment by matheuswr89** [comment]
@valery-lavrik thanks for the help, i was able to download the files following your example.

But a caveat, it seems that in the most recent versions of RN it is necessary to do one more step to be able to use the Buffer library (this was my case, I don't know if this is correct), and for that I had to follow the step the step that is shown in this answer on stackoverflow: [https://stackoverflow.com/a/60789036](https://stackoverflow.com/a/60789036)

**Comment by vladimirevstratov** [comment]
> @valery-lavrik thanks for the help, i was able to download the files following your example.
> 
> But a caveat, it seems that in the most recent versions of RN it is necessary to do one more step to be able to use the Buffer library (this was my case, I don't know if this is correct), and for that I had to follow the step the step that is shown in this answer on stackoverflow: https://stackoverflow.com/a/60789036

Works without additional steps with RN v0.70.0
