### ISSUE TITLE
Why have the directories in fs.dirs changed?

### ISSUE THREAD

**Issue by valery-lavrik** [RonRadtke/react-native-blob-util#202]
Hi!  I'm switching from the **rn-fetch-blob** library to this one. The instructions say that they are fully compatible.
But I noticed that **dir** does not have the directories that were in **rn-fetch-blob**

In rn-fetch-blob:
```
CacheDir: "/data/user/0/com.my_app/cache",
DCIMDir: "/storage/emulated/0/DCIM",
DocumentDir: "/data/user/0/com.my_app/files",
DownloadDir: "/storage/emulated/0/Download",
LibraryDir: undefined,
MainBundleDir: "/data/user/0/com.my_app",
MovieDir: "/storage/emulated/0/Movies",
MusicDir: "/storage/emulated/0/Music",
PictureDir: "/storage/emulated/0/Pictures",
SDCardApplicationDir: "/storage/emulated/0/Android/data/com.my_app",
SDCardDir: "/storage/emulated/0",
```

But in react-native-blob-util
```
ApplicationSupportDir: ""
CacheDir: "/data/user/0/com.my_app/cache"
DCIMDir: "/storage/emulated/0/Android/data/com.my_app/files/DCIM"
DocumentDir: "/data/user/0/com.my_app/files"
DownloadDir: "/storage/emulated/0/Android/data/com.my_app/files/Download"
LibraryDir: ""
MainBundleDir: "/data/user/0/com.my_app"
MovieDir: "/storage/emulated/0/Android/data/com.my_app/files/Movies"
MusicDir: "/storage/emulated/0/Android/data/com.my_app/files/Music"
PictureDir: "/storage/emulated/0/Android/data/com.my_app/files/Pictures"
SDCardApplicationDir: "/storage/emulated/0/Android/data/com.my_app"
SDCardDir: "/storage/emulated/0/Android/data/com.my_app/files"
```

It is very important for me to keep the old path.  What should I do?

**Comment by RonRadtke** [comment]
Wait for my next update - likely after christmas -  I re-added the old paths as legacy paths again. But went lost with the last merge.
The reason it's changed is because of Scoped Storage and APIs that got deprecated in the process.
So I switched to the new APIs but these return different paths for security reasons and it might happen (I think based on the TargetVersion) that the legacy paths are null (because deprecation etc). So at some point you will have to accept to use only paths within your own app and thus the new paths.

**Comment by valery-lavrik** [comment]
What if I rigidly fix the path "/storage/emulated/0/Download" in the application?    Can it do any harm?

**Comment by valery-lavrik** [comment]
it turned out an interesting effect.
There are files in this folder uploaded via rn-fetch-blob.    But react-native-blob-util doesn't see them.
```
LS = await RNFetchBlob.fs.ls(DIR);
LS2 = await RNFetchBlob.fs.lstat(DIR);
```
they are not shown...   Why?

**Comment by valery-lavrik** [comment]
and even so:
I write via react-native-blob-util file.
I go to "About the application" and delete all the information. (the file remains at the same time).

And now ls() stops seeing the files, despite the fact that they are still in the folder...

**Comment by Sid-Turner-Ellis** [comment]
@RonRadtke do you know why the SD card related constants have been commented as deprecated?

https://github.com/RonRadtke/react-native-blob-util/blob/f2d7d8fe3099074abc5600a220fd08f1a4840c2d/fs.js#L24
