### ISSUE TITLE
High vulnerability issues with Veracode Scan in ReactNativeBlobUtilUtils.java and ReactNativeBlobUtilMediaCollection.java

### ISSUE THREAD

**Issue by rkaartikeyan** [RonRadtke/react-native-blob-util#208]
Kindly see the attached screenshots.

<img width="1413" alt="Screenshot 2023-01-18 at 3 37 10 PM" src="https://user-images.githubusercontent.com/3778591/213144271-ad0e05d4-d460-44a5-8153-fba29933d09e.png">

<img width="1413" alt="Screenshot 2023-01-18 at 3 38 43 PM" src="https://user-images.githubusercontent.com/3778591/213144308-33f1c7c1-431e-4ac1-b18c-0d60efaa0447.png">

<img width="1409" alt="Screenshot 2023-01-18 at 3 39 47 PM" src="https://user-images.githubusercontent.com/3778591/213144341-3ab3c378-e396-4777-a78c-0c4d68a03693.png">

**Comment by RonRadtke** [comment]
Hi,
thank you very much.
Based on the warnings, all 3 don't seem to be very relevant. The MD5 is just a checksum for the files downloadad and therefor not very relevant for security except for integrity of the file.
The other methods are all covered by try/catch so it is up to you to make sure not to expose any errors.
