### ISSUE TITLE
The podspec file name is not matching the project name

### ISSUE THREAD

**Issue by mickeylam** [RonRadtke/react-native-blob-util#21]
react-native-blob-util: '0.13.2'
react-native: '0.61.2'

Please either change the podspec file name or change the README.

**Comment by rezasazesh** [comment]
Same issue `[!] No podspec found for `react-native-blob-util` in `../node_modules/react-native-blob-util``

**Comment by RonRadtke** [comment]
Fixed with the newest release on npm - thanks for the issue, tested it on ios works fine for me now
