### ISSUE TITLE
ReactNativeBlobUtil.ios.openDocument dark theme is not taking in account

### ISSUE THREAD

**Issue by Aure77** [RonRadtke/react-native-blob-util#221]
I use react-native-blob-util@0.16.4 to open document after download it.
On iOS, seems `ReactNativeBlobUtil.ios.openDocument` having issue with dark mode, back button is not visible on document preview : white back arrow on white/lightgrey background header...

![openDocument_back](https://user-images.githubusercontent.com/1374354/218483839-c6db4cbd-71ea-4ebe-924d-e211e2cb0b26.png)

**Comment by RonRadtke** [comment]
Thank you. Since you can reproduce it on your device, any chance to fix it?
