### ISSUE TITLE
Android: Too many receiver, Total of 1000, registered for pid

### ISSUE THREAD

**Issue by Vasudevan-iOS** [RonRadtke/react-native-blob-util#225]
Hi,

The Android app getting crash, When I download more than 1000 image, but iOS works fine.

<img width="320" alt="Screenshot 2023-02-14 at 4 28 07 PM" src="https://user-images.githubusercontent.com/63036298/221657031-50d6e19b-7926-4aba-8c99-d66a1c20bd79.png">

 # Version of installed library and RN :

<img width="460" alt="Screenshot 2023-02-28 at 12 13 28 AM" src="https://user-images.githubusercontent.com/63036298/221654419-4c1e5725-3a68-424b-a116-893c6c4e3c8e.png">

# Code Snippet:

<img width="645" alt="Screenshot 2023-02-28 at 12 10 19 AM" src="https://user-images.githubusercontent.com/63036298/221653775-65d8b446-7458-44d8-831c-92c5e0d16df0.png">

Can someone please suggest what I made mistakes

**Comment by Vasudevan-iOS** [comment]
@RonRadtke any suggestions for this issue ..?

**Comment by RonRadtke** [comment]
Looks like we are limited on the amount of receivers per pid.
The Request class  I'm using internally extends BroadcastReceiver. Every download will create a new one.
So you somewhen will run in the limit there.
Does it help to wait till the requests are done before starting new downloads?

But unless we find a problem that the receivers are not cleaned up and this is causing the issue we won't be able to do much here.

**Comment by Vasudevan-iOS** [comment]
We are waiting till the previous execution gets over. We suspect the framework is not releasing the threads internally and that's how it is hitting the ceiling. Is there a way for us to call a function explicitly to clean up the threads used internally?  Please guide us as we need to download more than 1000 files one by one.

**Comment by RonRadtke** [comment]
No there isn't. I think there is more likely a problem that the receivers are not correctly destroyed/ unregistered.So that basically the request objects don't die after being finished and reported to the javascript side.Sent from Outlook for Android

**Comment by RonRadtke** [comment]
https://github.com/RonRadtke/react-native-blob-util/issues/226
I put it on my todo

**Comment by RonRadtke** [comment]
Should be fixed with the new event system
