### ISSUE TITLE
ANR on Downloading PDF on Android

### ISSUE THREAD

**Issue by cw-sanjeev** [RonRadtke/react-native-blob-util#230]
Getting Few ANRs on Crashlytics on download PDF

Version Used:
"react": "17.0.1",
"react-native": "0.64.4",
"react-native-blob-util": "^0.17.0"

Code:
```
downloadPDF(pdfUrl, pdfName) {
    const { dirs } = RNFetchBlob.fs;
    const android = RNFetchBlob.android;
    const iOS = RNFetchBlob.ios;
    const dirToSave = Platform.OS === 'android' ? dirs.DownloadDir : dirs.DocumentDir
    const configOptions = {
      fileCache: true,
    appendExt: 'pdf',
    path: destPath,
    addAndroidDownloads: {
      useDownloadManager: true,
      path: destPath,
      notification: true,
      title: pdfName + '.pdf',
      description: pdfName,
      mime: MIME_PDF,
      mediaScannable: true,
    },
    };

    RNFetchBlob.config(configOptions)
      .fetch("GET", pdfUrl, {})
      .then((res) => {
        if (res) {
          if (Platform.OS !== 'android' && res.data) {
            RNFetchBlob.fs.writeFile(configOptions.path, res.data, "base64");
            iOS.openDocument(configOptions.path);
          } else {
            if (res.path()) {
              android.actionViewIntent(res.path(), MIME_PDF);
            }
          }
        }
      })
      .catch((error) => {
        //Throw Exception
      });
  }
```

Few ANR screenshots from Crashlytics:
<img width="699" alt="image" src="https://user-images.githubusercontent.com/51712166/224181440-8a12e451-1f55-43b8-84c8-7155dde05543.png">
<img width="725" alt="image" src="https://user-images.githubusercontent.com/51712166/224181515-b1b3a03a-aff4-4f8c-be1a-98bbc33ffafd.png">
Can anyone help here

**Comment by SiberianJohnny** [comment]
@cw-sanjeev At least there is a version compatibility issue here.
![image](https://user-images.githubusercontent.com/53685733/224211097-ee2b09db-efc5-4c19-8c99-f00126c61ad7.png)

**Comment by cw-sanjeev** [comment]
Downgraded lib version to 0.16.4, still facing this
