### ISSUE TITLE
Notification Upon file created using createFile()

### ISSUE THREAD

**Issue by arunahuja94** [RonRadtke/react-native-blob-util#24]
Version [v0.13.4]
Device [Android Emulator pixel api 29]

Is there a way to receive notification upon file creation using createFile()

**Comment by RonRadtke** [comment]
Yes there is. createFile will resolve the promise upon file creation.
So you can use another library e.g. https://github.com/zo0r/react-native-push-notification to create a notification on promise resolve.

**Comment by arunahuja94** [comment]
Hi @RonRadtke Thanks,

Whenever I create a Directory using 

> ReactNativeBlobUtil.fs.mkdir(ReactNativeBlobUtil.fs.dirs.DocumentDir + '/foldername')

Directory is created and I am able to check that by  

> ReactNativeBlobUtil.fs.exists

But I am not able to see that directory in physical device

**Comment by RonRadtke** [comment]
The documentDir refers to the apps internal directory so you can't see it from any other app. You would need root access for that

**Comment by arunahuja94** [comment]
Is there a way to create file anywhere other than apps internal storage , as whenever I clear data of my app those files also gets deleted

**Comment by RonRadtke** [comment]
Yes, you can use the downloadDir or the external storage directly. But keep in mind that you might need to request additional permissions for that.

**Comment by arunahuja94** [comment]
Can you please share a snippet for that

**Comment by RonRadtke** [comment]
Tested it myself first. Seems like there are some problems with Android 10 / 11 at the moment.
For these Android versions all paths will be in the apps directory.
Some changes to use the media files api would be required here, so we can use predefined, global locations.
But I'm not sure yet when exactly I will get to implement this

**Comment by arunahuja94** [comment]
Okay thanks

**Comment by RonRadtke** [comment]
We will run into a problem here.
In general with Android 10 / 11, following Apps are not allowed to access files outside of their scope anymore.
So we would be able to store the files outside of the apps directory (e.g. in the public Download directory) but the App would not be able to access it without a user opening it over a file picker. 
Only exception would be using certain media file collections like the gallery for images.
One reason for this is exactly what you want to mitigate - that data the app created gets deleted when the app is uninstalled. The best probably would be to first store the file in the apps scope and then copy / move it to another, public location. But currently the app can't do the last part.

**Comment by RonRadtke** [comment]
0.14.0 was released yesterday implementing the possibility to store files in e.g. the download collection.
