### ISSUE TITLE
Android 10+ - Legacy Dirs coming empty

### ISSUE THREAD

**Issue by kovendhanS** [RonRadtke/react-native-blob-util#240]
For android api level 10 and above devices, I see the legacy dirs are setting empty
````
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
            res = ReactNativeBlobUtilFS.getSystemfolders(ctx);

            // Include legacy folders anyway, since on the new arch compatibility between the spec and the turbomodule is enforced
            res.put("LegacyDCIMDir", "");
            res.put("LegacyPictureDir", "");
            res.put("LegacyMusicDir", "");
            res.put("LegacyDownloadDir", "");
            res.put("LegacyMovieDir", "");
            res.put("LegacyRingtoneDir", "");
            res.put("LegacySDCardDir", "");
            
            return res;
        }
````
I see this was added in - https://github.com/RonRadtke/react-native-blob-util/pull/222. I tried to get the Legacy Dirs through native modules, but unable to get those for 10+ devices. 
Is there any reason for setting empty for the android 10+ devices and how to access legacy dirs on 10+ devices.

**Comment by RonRadtke** [comment]
The legacy dirs are using a deprecated API and technicallly where ment to access folders which are not accessible any more in Android 10+. So these being null is an expected behaviour but is nothing we can change.

**Comment by HyperNovax** [comment]
According to this post `Legacy` path are empty because use a deprecated API.
According to #202 the 'classic' path return a path with the application id.

So it's not possible to get the path without the application id ?
It's not blocking me, I use another package to get the path.
Using this package method work fine but the user don"t see the file in folder.

**Comment by RonRadtke** [comment]
Could you link me the package then I'll take a look and mybe I can adapt it.
But to be honest, I'm planing a new major release which will likely drop these paths regardless.

But out of curiosity, why do you still use these paths?

**Comment by HyperNovax** [comment]
I use [react-native-fs](https://github.com/itinance/react-native-fs) to get the path.  

I use this path to download file in download directory. With the actual path the download work fine but user can't find the file in download folder on the device.

**Comment by RonRadtke** [comment]
No but that is to be expected.
Android 10+ changed the storage interaction.
For Android 10+ you must use the mediastore.
I implemented it a while ago:
https://github.com/RonRadtke/react-native-blob-util/wiki/MediaStore
Should be backwards compatible too
