### ISSUE TITLE
 ERROR  TypeError: null is not an object (evaluating '_NativeBlobUtils.default.getConstants') in iOS

### ISSUE THREAD

**Issue by surezz-r** [RonRadtke/react-native-blob-util#244]
ERROR  TypeError: null is not an object (evaluating '_NativeBlobUtils.default.getConstants')
 WARN  Module RNFetchBlob requires main queue setup since it overrides `constantsToExport` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.

```
"react": "17.0.2",
"react-native": "0.68.0",
"react-native-fetch-blob": "^0.10.8",
"react-native-pdf": "^6.6.2",
"react-native-blob-util": "^0.17.3",

Xcode - 14.2 (14C18)
iOS SDK - 16.2
```

Getting this above error in iOS while integrating react-native-pdf into my react native project.  Just getting this while importing pdf library.  Do I missed anything?

**Comment by RonRadtke** [comment]
The first one is an issue on library side. Missing the requiresMainQueueSetup method here. But that should not cause any problems. 

The other one... did you try to reset the cache? Could be due to installing new libs and ending up with a currupted or wrong cache
