### ISSUE TITLE
Cannot read property 'Content-Type' of undefined

### ISSUE THREAD

**Issue by skizzo** [RonRadtke/react-native-blob-util#245]
### Versions
- React Native `0.71.7`
- [react-native-blob-util `0.17.3`](https://github.com/RonRadtke/react-native-blob-util/releases/tag/0.17.3)
- XCode `14.3 (14E222b)`

### Issue
When trying to download a file with the `fetch(GET, url)` functions and then calling the `.blob()` function for the response object of `fetch()`, the error **"Cannot read property 'Content-Type' of undefined"** is being thrown.

```
ReactNativeBlobUtil
.config({path: "<MyDocumentsFolder>/<MyImageName.png>"}) // placeholder for demonstrational purposes
.fetch("GET", "https://placehold.co/1920x1080.png") 
.then(response => {
  // everything okay so far

  response.blob()
  .then(blob => {
    // I never get so far on first launch
    const mimeType = blob.type // this is why I need the blob in the first place
    // ...
  })
  .catch(error => {
    console.error(error) // "Cannot read property 'Content-Type' of undefined"
  })
})
```

### Observations
- This **only happens after freshly installing my app** on the iOS simulator. When the app is reloaded in the debugger, everything works as expected.

- This happens with various image URLs, both on our own server and on the placeholder service mentioned in the code snippet.
 
- (EDIT): The error happens on [this line in `ReactNativeBlobUtilBlobResponse.js`](https://github.com/RonRadtke/react-native-blob-util/blob/132051c1204051f5148a0b4bfede00ed99f47c44/class/ReactNativeBlobUtilBlobResponse.js#L60):
    ```
    /**
     * Convert result to javascript ReactNativeBlobUtil object.
     * @return {Promise<Blob>} Return a promise resolves Blob object.
     */
    this.blob = (): Promise<Blob> => {
        let cType = info.headers['Content-Type'] || info.headers['content-type']; // <-- ERROR: info doesn't seem to be defined
        return new Promise((resolve, reject) => {
            switch (this.type) {
                case 'base64':
                    Blob.build(this.data, {type: cType + ';BASE64'}).then(resolve);
                    break;
                case 'path':
                    Blob.build(URIUtil.wrap(this.data), {type: cType}).then(resolve);
                    break;
                default:
                    Blob.build(this.data, {type: 'text/plain'}).then(resolve);
                    break;
            }
        });
    };
    ```

Thanks for your help.

**Comment by RonRadtke** [comment]
I assume it is connected to this issue: https://github.com/RonRadtke/react-native-blob-util/issues/236
leading to respInfo not being set and therefor the blob method is failing.
Could you try my feature branch as described in the other issue and see if that is fixing the problem?
