### ISSUE TITLE
Android 13 issue

### ISSUE THREAD

**Issue by jaexplorer** [RonRadtke/react-native-blob-util#247]
Hi!

I've built our app and ran it on multiple devices. When we go to download PDFs, it works on all Android versions but Android 13.
It used to work but since we have upgraded to React native 71.3 and we had to target API 33, Android 13 of this library doesn't work anymore. 

I tried searching issues and the wiki, is this a known issue?

**Comment by RonRadtke** [comment]
Hi,
Where do you want to save the pdf?
Do you get any error?
Downloads in general are in general wokting with android 13 and this api / react-native version, using it myself in production.
So question is what's your problem / error?
E.g. not showing in downloads or so

**Comment by jaexplorer** [comment]
> Hi, Where do you want to save the pdf? Do you get any error? Downloads in general are in general wokting with android 13 and this api / react-native version, using it myself in production. So question is what's your problem / error? E.g. not showing in downloads or so

This is the function we currently have. I've only tested it on real devices so far.

The issue is the file doesn't appear to download, on earlier versions Android you see in the status bar a download has occured, when you pull down you see in your notification tray the downloaded pdf. If you go to your downloads folder, the file is also there. On Android 13, this doesn't occur. 

I will try now to reproduce the error on the simulator and update on any findings.

```
 public getPdfFromUrl<T = void>(path: string, name: string): Promise<T> {
    const isIosDevice = Platform.OS === 'ios';
    Logging.debug(`ApiService.getPdf ${path}`, { path, name });
    const fileName = this.getFileName(path, null, name);
    const filePath = isIosDevice
      ? `${RNFetchBlob.fs.dirs.DocumentDir}/${fileName}`
      : `${RNFetchBlob.fs.dirs.DownloadDir}/${fileName}`;

    return new Promise<T>((resolve, reject) => {
      RNFetchBlob.config({
        appendExt: 'pdf',
        fileCache: true,
        path: filePath,
        addAndroidDownloads: {
          useDownloadManager: true,
          notification: true,
          mediaScannable: true,
          mime: 'application/pdf',
        },
      })
        .fetch('GET', path)
        .then(
          (res: any) => {
            resolve(res);
          },
          (err) => {
            if (isIosDevice) {
              reject(err);
            } else {
              resolve(err);
            }
          },
        );
    });
  }
}

**Comment by RonRadtke** [comment]
Android changed with 10+ the storage api and introduced scoped storage.
But you store the file within the apps private scope. Therefor it won't show up in the downloads folder.
You can use the mediastore api (https://github.com/RonRadtke/react-native-blob-util/wiki/MediaStore) for that. But that won't work in combination with thr downloadmanager so you won't get a notification either... the notification part is still missing as a feature in the lib

**Comment by jaexplorer** [comment]
Oh okay, what do you suggest then? 
Is the notification part coming soon as a feature or is there another way to get the notification to work, as this will let the user know something is downloaded and they can tap on it in the notification tray. Is there public scope or something where it would work?

**Comment by RonRadtke** [comment]
I need to check. 
Theoretically downloadmanager should be able to store it to the correct place and send a notification also for Android +10. 

You technically should not need the part I said does not work yet for your scenario. Using obly the downloadmanager should be sufficient. 

But unsure yet why it does not work for you.
I'll try to reproduce it based on your code.  I will try to get to it this weeky but can't promise it.
So just to make sure.
You don't get a notification?
You don't see the files in the global downloads folder?

**Comment by jaexplorer** [comment]
Correct I don't get a notification, nor does it appear in the downloads folder. 

I've tested this on multiple Android devices, only Android 13 devices have this issue. Whereas my device for example (Android 11 is fine).

Thanks

**Comment by jaexplorer** [comment]
> I need to check. Theoretically downloadmanager should be able to store it to the correct place and send a notification also for Android +10.
> 
> You technically should not need the part I said does not work yet for your scenario. Using obly the downloadmanager should be sufficient.
> 
> But unsure yet why it does not work for you. I'll try to reproduce it based on your code. I will try to get to it this weeky but can't promise it. So just to make sure. You don't get a notification? You don't see the files in the global downloads folder?

Any luck?

**Comment by RonRadtke** [comment]
> > I need to check. Theoretically downloadmanager should be able to store it to the correct place and send a notification also for Android +10.
> > You technically should not need the part I said does not work yet for your scenario. Using obly the downloadmanager should be sufficient.
> > But unsure yet why it does not work for you. I'll try to reproduce it based on your code. I will try to get to it this weeky but can't promise it. So just to make sure. You don't get a notification? You don't see the files in the global downloads folder?
> 
> Any luck?

So, if I use your code I'll get a notification but the file does not appear in the downloads folder.
Last part is correct and I'm thinking how to fix it without breaking the ucrrent usage.

But in addition. You're not using this library here. You're using an old not maintained version I forked. So could be that on the old fork there is something broken about the notifications

**Comment by jaexplorer** [comment]
> > > I need to check. Theoretically downloadmanager should be able to store it to the correct place and send a notification also for Android +10.
> > > You technically should not need the part I said does not work yet for your scenario. Using obly the downloadmanager should be sufficient.
> > > But unsure yet why it does not work for you. I'll try to reproduce it based on your code. I will try to get to it this weeky but can't promise it. So just to make sure. You don't get a notification? You don't see the files in the global downloads folder?
> > 
> > 
> > Any luck?
> 
> So, if I use your code I'll get a notification but the file does not appear in the downloads folder. Last part is correct and I'm thinking how to fix it without breaking the ucrrent usage.
> 
> But in addition. You're not using this library here. You're using an old not maintained version I forked. So could be that on the old fork there is something broken about the notifications

Oh okay, I can change the implimentation. How do you do this in the current library?

**Comment by jaexplorer** [comment]
> > > I need to check. Theoretically downloadmanager should be able to store it to the correct place and send a notification also for Android +10.
> > > You technically should not need the part I said does not work yet for your scenario. Using obly the downloadmanager should be sufficient.
> > > But unsure yet why it does not work for you. I'll try to reproduce it based on your code. I will try to get to it this weeky but can't promise it. So just to make sure. You don't get a notification? You don't see the files in the global downloads folder?
> > 
> > 
> > Any luck?
> 
> So, if I use your code I'll get a notification but the file does not appear in the downloads folder. Last part is correct and I'm thinking how to fix it without breaking the ucrrent usage.
> 
> But in addition. You're not using this library here. You're using an old not maintained version I forked. So could be that on the old fork there is something broken about the notifications

FYI I am following the documentation in the wiki, code is the same. The named import simply doesn't have "Utils" in it.

**Comment by RonRadtke** [comment]
@jaexplorer yes exactly. It's jsut the import you have to adjsut basically.
I will likely add a new paramter to the android downloads which will enforce the file being written to the global downloads folder, regardless of the given path since this does not work anymore for Android >= 10. Or if possible being written to both destinations, but I don't think that's possible wihtout programming it in the library which I wouldn't do, since these possibilities are already available by just chaning the correct functions.

**Comment by jaexplorer** [comment]
@RonRadtke no you misunderstand.
I am importing correctly, whatever I decide to name the import doesn't matter. 
E.g Import ABC from 'react-native-blob-util' is exactly the same as Import ReactNativeBlobUtil from 'react-native-blob-util'. The code for .config is also the same in the docs, so I don't know what I need to change here. 

Can you please provide an example of the changes I need to make for this to work?
Am I correctly chaining the correct functions?

No I don't require special scoping, just downloading pdfs to the downloads folder or downloading and opening them.

**Comment by RonRadtke** [comment]
@jaexplorer 
I added a new parameter to addAndroidDownloads: storeInDownloads
It's boolean, jsut set it to true and the file will end up in downloads

**Comment by jaexplorer** [comment]
> @jaexplorer I added a new parameter to addAndroidDownloads: storeInDownloads It's boolean, jsut set it to true and the file will end up in downloads
> 
> See for more details: https://github.com/RonRadtke/react-native-blob-util/releases/tag/0.18.1

Please see my latest issue ticket. Installing doesn't work for 18

**Comment by jaexplorer** [comment]
> @jaexplorer I added a new parameter to addAndroidDownloads: storeInDownloads It's boolean, jsut set it to true and the file will end up in downloads
> 
> See for more details: https://github.com/RonRadtke/react-native-blob-util/releases/tag/0.18.1

No notification or in downloads either. Didn't work :(

**Comment by raymondjacobson** [comment]
This may not work for 
```
/**
     * Using this function to add an existing file to Downloads app.
     * @param options An object that for setting the title, description, mime, and notification of the item.
     */
    addCompleteDownload(options: AndroidDownloadOption): Promise<void>;
```

As the parameter doesn't exist in AndroidDownloadOption
