### ISSUE TITLE
Cannot find module 'types' from 'node_modules/react-native-blob-util/fetch.js'

### ISSUE THREAD

**Issue by UNIDY2002** [RonRadtke/react-native-blob-util#250]
Hi ! Thank you for reporting an issue, but we would like to remind you, we have a trouble shooting page in our wiki. 
You may want to take a look on that page or find issues tagged "trouble shooting" :p 

* please provide the version of installed library and RN project.
* a sample code snippet/repository is very helpful to spotting the problem.
* issues which have been tagged as 'needs feedback', will be closed after 2 weeks if receive no feedbacks.
* issues lack of detailed information will be closed without any feedback

Library version: 0.18.1
RN version: 0.71.8
Repo: https://github.com/thu-info-community/thu-info-app/tree/adf8d87d976b8fbf87aa5fc7cef9b60830cefd5e
Error: see https://github.com/thu-info-community/thu-info-app/actions/runs/5137898764/jobs/9246588014

```
    Cannot find module 'types' from 'node_modules/react-native-blob-util/fetch.js'

    Require stack:
      node_modules/react-native-blob-util/fetch.js
      node_modules/react-native-blob-util/polyfill/XMLHttpRequest.js
      node_modules/react-native-blob-util/polyfill/index.js
      node_modules/react-native-blob-util/index.js
      node_modules/react-native-pdf/index.js
      src/ui/home/invoicePDF.tsx
      src/components/Root.tsx
      src/App.tsx
      test/render.test.tsx


    However, Jest was able to find:
    	'./types.js'
```

I notice that in `fetch.js`, the first import statement is changed to `... from 'types'`. Is that intentional?

**Comment by RonRadtke** [comment]
No that was not intentional and got fixed in 0.18.2 5 minutes ago.
Thanks for the report.
