### ISSUE TITLE
18.1 Build not working

### ISSUE THREAD

**Issue by jaexplorer** [RonRadtke/react-native-blob-util#251]
Hi tried the new build, i'm getting this in the CI pipe

error Unable to resolve module types from /Users/vagrant/git/node_modules/react-native-blob-util/fetch.js: types could not be found within the project or in these directories:
  node_modules/react-native-blob-util/node_modules
  node_modules
> 1 | import {ReactNativeBlobUtilConfig} from 'types';
    |                                          ^
  2 | import URIUtil from './utils/uri';
  3 | import fs from './fs';
  4 | import getUUID from './utils/uuid';

**Comment by RonRadtke** [comment]
There is missing a ./ in front the types. I'll publish a fix. But strange that it worked in my device
