### ISSUE TITLE
Android: problem with task.cancel

### ISSUE THREAD

**Issue by Splicer97** [RonRadtke/react-native-blob-util#252]
I have an array of links to files that I need to download, each in its own component. The component allows you to download a file (with saving to an external folder Downloads), remove the file from there, or cancel the download of the file. Also in the component specifies the progress of downloading a file. Downloading and deleting works fine, progress too, but when I start downloading the first file, then cancel it in the process and start downloading the other one, in the end both files start downloading. React Native version 0.70, library version 0.18.2.

**Comment by RonRadtke** [comment]
Are you using downloadmanager?
Small code snippet would be great to test it

**Comment by Splicer97** [comment]
I found the problem, the documentation says that when you use progress and cancel on the same task, you need to put fetch separately. I did as it was written through let (const), but I needed to create ref link through useRef and everything worked!
Not use:  let task = ReactNativeBlobUtil.fetch('GET', 'http://example.com/file/1')
Use: const task = useRef(ReactNativeBlobUtil.fetch('GET','http://example.com/file/1')).current;


But there is another problem, after I cancel the download and want to load again, I get the following message
 ReactNativeBlobUtilCanceledFetch: canceled

**Comment by Splicer97** [comment]
@RonRadtke https://codepen.io/splicer97/pen/YzJmWda?editors=0010

**Comment by RonRadtke** [comment]
> I found the problem, the documentation says that when you use progress and cancel on the same task, you need to put fetch separately. I did as it was written through let (const), but I needed to create ref link through useRef and everything worked! Not use: let task = ReactNativeBlobUtil.fetch('GET', 'http://example.com/file/1') Use: const task = useRef(ReactNativeBlobUtil.fetch('GET','http://example.com/file/1')).current;
> 
> But there is another problem, after I cancel the download and want to load again, I get the following message ReactNativeBlobUtilCanceledFetch: canceled

useRef you only need if you might have a rerender inbetween. Since it creates a reference that is persitent

**Comment by Splicer97** [comment]
> > I found the problem, the documentation says that when you use progress and cancel on the same task, you need to put fetch separately. I did as it was written through let (const), but I needed to create ref link through useRef and everything worked! Not use: let task = ReactNativeBlobUtil.fetch('GET', 'http://example.com/file/1') Use: const task = useRef(ReactNativeBlobUtil.fetch('GET','http://example.com/file/1')).current;
> > 
> > But there is another problem, after I cancel the download and want to load again, I get the following message ReactNativeBlobUtilCanceledFetch: canceled
> 
> useRef you only need if you might have a rerender inbetween. Since it creates a reference that is persitent 
> 

I understand, but what should I do in my case? How do I create a link to the new shuffle after the cancellation, instead of referring to the previous one?

**Comment by RonRadtke** [comment]
I can't follow completely.
What do you mean with shuffle?

**Comment by Splicer97** [comment]
> I can't follow completely.
> What do you mean with shuffle?

Wrong translate))
How can I download the file again after canceling it? I suspect that I am referring to a task that was canceled, so I can not download it again, that is, I need to somehow throw in the useRef link to a new task with the same configuration as the previous one?

**Comment by RonRadtke** [comment]
> > I can't follow completely.
> > What do you mean with shuffle?
> 
> Wrong translate)) How can I download the file again after canceling it? I suspect that I am referring to a task that was canceled, so I can not download it again, that is, I need to somehow throw in the useRef link to a new task with the same configuration as the previous one?

Yes, you would need to start a new .fetch(....).
There is no way to restart the download.
So to restart it you have to call 
```
 const config = ReactNativeBlobUtil.config({
    fileCache: true,
  }).fetch('GET', file.url);
  const task = useRef(config).current;
```
again. But your config is not a config. It is the fetch task. But that's just a naming.

So all you need to do is, calling the fetch again.

**Comment by Splicer97** [comment]
> > > I can't follow completely.
> > > What do you mean with shuffle?
> > 
> > 
> > Wrong translate)) How can I download the file again after canceling it? I suspect that I am referring to a task that was canceled, so I can not download it again, that is, I need to somehow throw in the useRef link to a new task with the same configuration as the previous one?
> 
> Yes, you would need to start a new .fetch(....). There is no way to restart the download. So to restart it you have to call
> 
> ```
>  const config = ReactNativeBlobUtil.config({
>     fileCache: true,
>   }).fetch('GET', file.url);
>   const task = useRef(config).current;
> ```
> 
> again. But your config is not a config. It is the fetch task. But that's just a naming.
> 
> So all you need to do is, calling the fetch again.

Thanks! I found solution, we can use state for task and set new task in state when cancelling

```js
  const config = ReactNativeBlobUtil.config({
    fileCache: true,
  }).fetch('GET', file.url);
  const [task, setTask] = useState(config);

  const handleStop = () => {
    task.cancel(() => {
      setIsLoading(false);
      setTask(config);
    });
  };
```
