### ISSUE TITLE
Typo in folder name

### ISSUE THREAD

**Issue by cristianoccazinsp** [RonRadtke/react-native-blob-util#26]
https://github.com/RonRadtke/react-native-blob-util/tree/master/android/src/main/java/com/ReactNativeBloBUtil

`ReactNativeBloBUtil` should be ReactNativeBlobUtil.  I don't even know how this compiles, but caught with Android Studio!

**Comment by ttdatt** [comment]
It's still `ReactNativeBloBUtil` when do `yarn add react-native-blob-util` or `npm i react-native-blob-util`
