### ISSUE TITLE
Trust Manager Problem

### ISSUE THREAD

**Issue by MuratAkbaba006** [RonRadtke/react-native-blob-util#260]
Hello, I have a problem with ssl certificate and I try to add trust manager in my MainApplication.java file.  when I try to open app get error like this 
'illegal start of expression
    ReactNativeBlobUtilUtils.sharedTrustManager = **final** X509TrustManager x509TrustManager = new X509TrustManager() {
'
This issue is probably related to the package(ReactNativeBlobUtilUtils) not being able to be imported correctly. I imported X509TrustManager but I can't find how to import ReactNativeBlobUtilUtils and how to use in MainApplication.java file could you help me with this problem? 

here is my  MainApplication.java file
                           
`
        
    package com.myApplication;

    import android.app.Application;
    import com.facebook.react.PackageList;
    import com.facebook.react.ReactApplication;
    import com.facebook.react.ReactNativeHost;
    import com.facebook.react.ReactPackage;
    import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint;
    import com.facebook.react.defaults.DefaultReactNativeHost;
    import com.facebook.soloader.SoLoader;
    import java.util.List;
    import com.facebook.react.modules.network.OkHttpClientProvider;
    import javax.net.ssl.TrustManager;

    import javax.net.ssl.X509TrustManager;

    public class MainApplication extends Application implements ReactApplication {

    private final ReactNativeHost mReactNativeHost =
        new DefaultReactNativeHost(this) {
         @Override
         public boolean getUseDeveloperSupport() {
           return BuildConfig.DEBUG;re
         }

        @Override
        protected List<ReactPackage> getPackages() {
          @SuppressWarnings("UnnecessaryLocalVariable")
          List<ReactPackage> packages = new PackageList(this).getPackages();
          // Packages that cannot be autolinked yet can be added manually here, for example:
          // packages.add(new MyReactNativePackage());
          return packages;
        }

        @Override
        protected String getJSMainModuleName() {
          return "index";
        }

        @Override
        protected boolean isNewArchEnabled() {
          return BuildConfig.IS_NEW_ARCHITECTURE_ENABLED;
        }

        @Override
        protected Boolean isHermesEnabled() {
          return BuildConfig.IS_HERMES_ENABLED;
        }
      };

    @Override
     public ReactNativeHost getReactNativeHost() {
      return mReactNativeHost;
    }

    @Override
    public void onCreate() {
      super.onCreate();
      SoLoader.init(this, /* native exopackage */ false);
      ReactNativeBlobUtilUtils.sharedTrustManager = final X509TrustManager x509TrustManager = new X509TrustManager() {
      @Override
      public void checkClientTrusted(java.security.cert.X509Certificate[] chain, String authType) throws CertificateException {
      }

      @Override
      public void checkServerTrusted(java.security.cert.X509Certificate[] chain, String authType) throws CertificateException {
      }

      @Override
      public java.security.cert.X509Certificate[] getAcceptedIssuers() {
        return new java.security.cert.X509Certificate[]{};
      }
    };
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
      // If you opted-in for the New Architecture, we load the native entry point for this app.
      DefaultNewArchitectureEntryPoint.load();
    }
    ReactNativeFlipper.initializeFlipper(this, getReactNativeHost().getReactInstanceManager());
  }
}
`

**Comment by RonRadtke** [comment]
You seem to be missing the import.
The import should be
```import com.ReactNativeBlobUtil.ReactNativeBlobUtilUtils;```
I just can't test it right now.

**Comment by MuratAkbaba006** [comment]
I imported import com.ReactNativeBlobUtil.ReactNativeBlobUtilUtils; 
but same result
<img width="999" alt="Screen Shot 2023-06-18 at 12 10 49" src="https://github.com/RonRadtke/react-native-blob-util/assets/44754934/329bd4fb-d1ef-4adb-9bef-532dfafdfe54">

**Comment by RonRadtke** [comment]
You're combining a double assignment and declaration of a final variable in one line.
That doesn't work.
Change it to 

```ReactNativeBlobUtilUtils.sharedTrustManager = new X509TrustManager()```

Sorry that is a copy&past mistake in the readme

**Comment by MuratAkbaba006** [comment]
Hello, Now I can open my app. Thanks for clarification. 
Actually I want to download file from a website has not ssl valid certificate. is that possible? I added this lines and trusty parameter but I can't download file. 

Here is my mainApplication.java file
`
    
    package com.inavitaswfm;

    import android.app.Application;
    import com.facebook.react.PackageList;
    import com.facebook.react.ReactApplication;
    import com.facebook.react.ReactNativeHost;
    import com.facebook.react.ReactPackage;
    import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint;
    import com.facebook.react.defaults.DefaultReactNativeHost;
    import com.facebook.soloader.SoLoader;
    import java.util.List;
    import com.facebook.react.modules.network.OkHttpClientProvider;
    import javax.net.ssl.TrustManager;
    import javax.net.ssl.X509TrustManager;
    import com.ReactNativeBlobUtil.ReactNativeBlobUtilUtils;
    import java.security.cert.CertificateException;

    public class MainApplication extends Application implements ReactApplication {

    private final ReactNativeHost mReactNativeHost = new DefaultReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      @SuppressWarnings("UnnecessaryLocalVariable")
      List<ReactPackage> packages = new PackageList(this).getPackages();
      // Packages that cannot be autolinked yet can be added manually here, for
      // example:
      // packages.add(new MyReactNativePackage());
      return packages;
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }

    @Override
    protected boolean isNewArchEnabled() {
      return BuildConfig.IS_NEW_ARCHITECTURE_ENABLED;
    }

    @Override
    protected Boolean isHermesEnabled() {
      return BuildConfig.IS_HERMES_ENABLED;
    }
    };

    @Override
    public ReactNativeHost getReactNativeHost() {
     return mReactNativeHost;
    }

    @Override
    public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
    ReactNativeBlobUtilUtils.sharedTrustManager = new X509TrustManager() {
      @Override
      public void checkClientTrusted(java.security.cert.X509Certificate[] chain,
          String authType)
          throws CertificateException {
      }

      @Override
      public void checkServerTrusted(java.security.cert.X509Certificate[] chain,
          String authType)
          throws CertificateException {
      }

      @Override
      public java.security.cert.X509Certificate[] getAcceptedIssuers() {
        return new java.security.cert.X509Certificate[] {};
      }
    };
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
      // If you opted-in for the New Architecture, we load the native entry point for
      // this app.
      DefaultNewArchitectureEntryPoint.load();
    }
    ReactNativeFlipper.initializeFlipper(this, getReactNativeHost().getReactInstanceManager());
    }
    }

`

**Comment by RonRadtke** [comment]
You didn't post your javascript part so I'm unsure what you're doing.
But you should not need your own trustmanager for that.
All needed is adding either a networkconfig or usecleartexttraffic in the manifest.
See: https://flutter-developer.medium.com/android-how-to-allow-all-network-connection-types-http-and-https-bacac8809621

**Comment by MuratAkbaba006** [comment]
thank you I fixed my problem with this link:
[https://flutter-developer.medium.com/android-how-to-allow-all-network-connection-types-http-and-https-bacac8809621](url).
