### ISSUE TITLE
Unable tosave file to MediaStore

### ISSUE THREAD

**Issue by scipriani** [RonRadtke/react-native-blob-util#270]
Hi, I'm trying to save file in android in Download folder. 

I've read this issue #https://github.com/RonRadtke/react-native-blob-util/issues/62 , but I can't find a solution... 

My code is pretty simple: 

`ReactNativeBlobUtil
.config({
    fileCache: true
})
.fetch('GET', myUrl, {Cookie: authCookie})
.then(async (res) => {                 
    let pathnew = await ReactNativeBlobUtil.MediaCollection.createMediafile({name: attachment.name, parentFolder: '', mimeType: attachment.mimeType}, 'Download');
    await ReactNativeBlobUtil.MediaCollection.writeToMediafile(pathnew, res.path());
})`

The error is
`TypeError: Cannot read property 'createMediafile' of undefined
TypeError: Cannot read property 'createMediafile' of undefined
`

I have installed 
react-native: "0.71.7",
react-native-blob-util: "^0.13.18"

**Why MediaCollection is undefined?**

By the way in IOS everithing works fine, so this is not an issue with my url or something else.

**Comment by RonRadtke** [comment]
MediaStore api got inteoduced in 0.14.0. So you have to updste the lib
Why do you use such an old version of the library?

**Comment by scipriani** [comment]
> Why do you use such an old version of the library?

I don't know, it was the default version when I installed the library. 

However updating did the trick! Thank you very much.
