### ISSUE TITLE
new NativeEventEmitter() was called with a non-null argument without the required removeListeners method

### ISSUE THREAD

**Issue by billnbell** [RonRadtke/react-native-blob-util#274]
This happens  `node_modules/react-native/Libraries/EventEmitter/NativeEventEmitter.js`

```
const eventEmitter = new NativeEventEmitter(ReactNativeBlobUtil);

// register message channel event handler.
eventEmitter.addListener('ReactNativeBlobUtilMessage', (e) => {
    if (typeof e === 'string') e = JSON.parse(e);

    console.log('add listener')
    if (e.event === 'warn') {
        console.warn(e.detail);
    }
    else if (e.event === 'error') {
        throw e.detail;
    }
    else {
        console.log('ReactNativeBlobUtil native message', e.detail);
    }
});
```

Missing remove().

**Comment by billnbell** [comment]
Also getting this on New Arch on `node_modules/react-native-blob-util/class/ReactNativeBlobUtilReadStream.js`

```
const emitter = new NativeEventEmitter(ReactNativeBlobUtil);
```

**Comment by billnbell** [comment]
And...
`node_modules/react-native-blob-util/fetch.js`

```
const eventEmitter = new NativeEventEmitter(ReactNativeBlobUtil);
```

**Comment by billnbell** [comment]
You should probably move the eventEmitter into the class, and add a eventEmitter.remove onEnd. ?

I am not familiar with this code - but I get 4 WARN on startup and it is a good idea to remove the listeners

**Comment by RonRadtke** [comment]
These methods are technically there, but on the main class - and in the past that worked fine.
Which lib version are you using?
Need to check it locally then.

**Comment by billnbell** [comment]
fabric: true.
"react-native": "^0.72.3",
"react-native-blob-util": "^0.18.3",

```
NO_FLIPPER=1 USE_FRAMEWORKS=static RCT_NEW_ARCH_ENABLED=1 pod install && cd ..
yarn ios
```

I get it on start up every time is New Arch. And if you put into the class before addListener -- something like:

```
useEffect(() => {
const eventEmitter = new NativeEventEmitter(ReactNativeBlobUtil);
const listener = eventEmitter.addListener(...)
....
() => {
   listener.remove();
}, []);
```

This works better since it removes the listener on unmount.

**Comment by billnbell** [comment]
if you move the `const eventEmitter = new NativeEventEmitter(ReactNativeBlobUtil);` into the class/function I don't get the warning anymore. So that is probably the right direction.

**Comment by RonRadtke** [comment]
Thanks. Kinda expected that.
Just need to test that I can use it that way without any of the event handling breaking or other problems

**Comment by puregewaltdota** [comment]
in my App.test.tsx have my mock but my test fail and says Invariant Violation: `new NativeEventEmitter()` requires a non-null argument. 
Why is this happening and when will it be fixed?

**Comment by jimmy-sqe** [comment]
Me too, when will it be fixed? I am running it in Expo project.

**Comment by RonRadtke** [comment]
> in my App.test.tsx have my mock but my test fail and says Invariant Violation: `new NativeEventEmitter()` requires a non-null argument. Why is this happening and when will it be fixed?

In the library use or in a jest mock?
What I could find, jest might need
```jest.mock('react-native/Libraries/EventEmitter/NativeEventEmitter')``` correctly 

Otherwise still have to fix the issue with the eventlistener..otherwise if someone csn make a PR and test that it works wouls be great

**Comment by RonRadtke** [comment]
@billnbell but you don't get a warning about the addlistener?
I'm  digging trough the RCT code and am wodnering why you get one but not the other. Based on what i'm seeing the chck is on the native module, so on the Java side not in JS....

**Comment by billnbell** [comment]
For me the error happens when it is outside the class and does not have a remove....

```
const eventEmitter = new NativeEventEmitter(ReactNativeBlobUtil);
```

Do you have a PR and I can try it?

**Comment by RonRadtke** [comment]
> For me the error happens when it is outside the class and does not have a remove....
> 
> ```
> const eventEmitter = new NativeEventEmitter(ReactNativeBlobUtil);
> ```
> 
> Do you have a PR and I can try it?

No I don't yet.
But I assume it does not happen anymore because you don't create a new member of the class and therefor `new NativeEventEmitter ` is never called.
Did you try if you get the warning when you open a stream / fetch request?

**Comment by billnbell** [comment]
I am running `react-native-blob-util  ^0.18.6` and it still happens.

**Comment by billnbell** [comment]
https://github.com/RonRadtke/react-native-blob-util/blob/b6c7f6ff5e9e29f9996210df2b882b6119b2b3a8/class/ReactNativeBlobUtilReadStream.js#L10

**Comment by gaofeiyang2022** [comment]
add this for jest `__mocks__/react-native-blob-util.ts` dir should work:
`export default jest.mock('react-native-blob-util', () => {});
`
