### ISSUE TITLE
Invalid react-native-blob-util.podspec

### ISSUE THREAD

**Issue by Dannschz** [RonRadtke/react-native-blob-util#275]
React Native version: 0.65.3
react-native-blob-util version: 0.18.4

When try install pods with npx pod-install i'm getting this error:

![WhatsApp Image 2023-07-24 at 12 58 58 PM](https://github.com/RonRadtke/react-native-blob-util/assets/46688591/45ab8596-fb7b-4d81-af54-897183ebfcea)

When remove the line that contains "install_modules_dependencies(s)" from the "react-native-blob-util/react-native-blob-util.podspec" file all works correctly (pods install well):

![imagen](https://github.com/RonRadtke/react-native-blob-util/assets/46688591/bb43789f-82c1-4598-81a8-f29383cf0387)

**Comment by RonRadtke** [comment]
Does the library still work as expected then?
That change wqs made to support rn 0.72 and statuc frameworks on ios in the new arkitektur. I missed a safeguard here.
I assume you are using rn < 0.71?

**Comment by RonRadtke** [comment]
should be fixed
