### ISSUE TITLE
Fix pod spec for non New arch

### ISSUE THREAD

**Issue by billnbell** [RonRadtke/react-native-blob-util#277]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-blob-util@0.18.5` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-blob-util/react-native-blob-util.podspec b/node_modules/react-native-blob-util/react-native-blob-util.podspec
index 4aa0c11..bf8e901 100644
--- a/node_modules/react-native-blob-util/react-native-blob-util.podspec
+++ b/node_modules/react-native-blob-util/react-native-blob-util.podspec
@@ -18,6 +18,8 @@ Pod::Spec.new do |s|
 
   if fabric_enabled
     install_modules_dependencies(s)
+  else
+    s.dependency 'React-Core'
   end
 
 end
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by claudiozam** [comment]
@billnbell thanks!
