### ISSUE TITLE
Crash on Android API 20 and below

### ISSUE THREAD

**Issue by juanamd** [RonRadtke/react-native-blob-util#28]
Hi,

I noticed that after switching from rn-fetch-blob to this fork, my app started crashing on devices with android below API 21.
After some digging, I found out it is caused by requiring the latest Okhttp client on the [Android dependencies list](https://github.com/RonRadtke/react-native-blob-util/blob/master/android/build.gradle).

After removing the okhttp lines, it now works fine on all the devices I've tested on.
Is  there a reason for having those dependencies explicitly declared, or can they be removed to regain full compatibility?

I know that RN v 0.64 increased the min API version to 21, but I'm still using RN 63 for some projects, and keeping it compatible with API 16+ is needed.

Thanks

**Comment by RonRadtke** [comment]
Hi juanamd,

the okhttp3 client is currently used in some , so as long as you are using a okhttp3 version you should be fine. 
You would have to use okhttp 3.12.x which is included in RN 0.63, so removing the dependency should work fine..
But since the lib is using okhttp directly as an import I will keep the requirement in the lib.

**Comment by juanamd** [comment]
Fair enough.
Maybe adding a warning/guide for users who target API 20 and below in the readme file would be a good workaround.
I still believe that pinning the dependency to a specific version instead of ":+" is a better option.

**Comment by RonRadtke** [comment]
Yes there you are basically right. At least this will ensure certain compatibility.
Also a note in the readme might be a good idea. I will address this with an upcoming release

**Comment by RonRadtke** [comment]
Hi  @juanamd ,
after further checking I decided that that fixing the version to okhttp 3.12.+ should be fine. So you should be able to use the newest version without the need to modify it for your Android 5 devices :)

**Comment by juanamd** [comment]
Thanks!
