### ISSUE TITLE
I use react-native-pdf how do I point to this repo?

### ISSUE THREAD

**Issue by billnbell** [RonRadtke/react-native-blob-util#30]
\How do I install react-native-pdf and point it to here instead of rn-fetch-blob?

**Comment by RonRadtke** [comment]
First of all you need to install react-native-blob-util. Then the easiest probably would be  to change this line to require react-native-blob-util instead:
https://github.com/wonday/react-native-pdf/blob/93d2890bb25fbea96173d14ea6828bf54388d7f1/index.js#L26
The public interface of the lib didn't change so it should work without issues.
But in general I would recommend opening a pull-request to get the dependency exchanged in general. (Also for the windows support)

**Comment by RonRadtke** [comment]
You'll find a pull request for it here:
https://github.com/wonday/react-native-pdf/pull/578
