### ISSUE TITLE
Error: java.lang.SecurityException when registering a receiver - Android 14 

### ISSUE THREAD

**Issue by lorikgashi** [RonRadtke/react-native-blob-util#303]
Getting this issue on Android 14, 

Version: 0.19.1

Stack trace:

Fatal Exception: java.lang.SecurityException
com.test.test.test: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts

android.os.Parcel.createExceptionOrNull (Parcel.java:3057)
android.os.Parcel.createException (Parcel.java:3041)
android.os.Parcel.readException (Parcel.java:3024)
android.os.Parcel.readException (Parcel.java:2966)
android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature (IActivityManager.java:5684)
android.app.ContextImpl.registerReceiverInternal (ContextImpl.java:1852)
android.app.ContextImpl.registerReceiver (ContextImpl.java:1792)
android.app.ContextImpl.registerReceiver (ContextImpl.java:1780)
android.content.ContextWrapper.registerReceiver (ContextWrapper.java:755)
com.ReactNativeBlobUtil.ReactNativeBlobUtilReq.run (ReactNativeBlobUtilReq.java:295)
com.ReactNativeBlobUtil.ReactNativeBlobUtilImpl.fetchBlob (ReactNativeBlobUtilImpl.java:322)
com.ReactNativeBlobUtil.ReactNativeBlobUtil.fetchBlob (ReactNativeBlobUtil.java:199)

https://developer.android.com/about/versions/14/behavior-changes-14#runtime-receivers-exported

**Comment by lorikgashi** [comment]
Hi there, ntil the next version with the fix for Android 14, here's a hotfix:

`-                appCtx.registerReceiver(this, new IntentFilter(DownloadManager.ACTION_DOWNLOAD_COMPLETE));
+                if(Build.VERSION.SDK_INT >= 34 ){
+                    appCtx.registerReceiver(this, new IntentFilter(DownloadManager.ACTION_DOWNLOAD_COMPLETE), Context.RECEIVER_EXPORTED);
+                }else{
+                    appCtx.registerReceiver(this, new IntentFilter(DownloadManager.ACTION_DOWNLOAD_COMPLETE));
+                }
`

FYI @RonRadtke ☮️

**Comment by fcaldarelli** [comment]
@RonRadtke I've created a PR based on @lorikgashi code. Can you merge?

**Comment by RonRadtke** [comment]
> @RonRadtke I've created a PR based on @lorikgashi code. Can you merge?

I will

**Comment by ruipaulo** [comment]
Hi @fcaldarelli and @RonRadtke for me the "fix" crashes the build project with:

```
Error: Command failed: ./gradlew app:installCinuruDebug -PreactNativeDevServerPort=8081
/.../app/node_modules/react-native-blob-util/android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilReq.java:296: error: cannot find symbol
                    appCtx.registerReceiver(this, new IntentFilter(DownloadManager.ACTION_DOWNLOAD_COMPLETE), Context.RECEIVER_EXPORTED);
                                                                                                                     ^
  symbol:   variable RECEIVER_EXPORTED
  location: class Context
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
````

This might be an error in my setup, as I am currently upgrading the app, but it was introduced from `0.19.1` to `0.19.2`

**Comment by amanrathore18** [comment]
Hello @ruipaulo,

Hope you're doing well

I'm also facing the same issue. Any update?

**Comment by ruipaulo** [comment]
Hi @amanrathore18, unfortunately I have no solution, except pinning the version to 0.19.1.

**Comment by fcaldarelli** [comment]
@ruipaulo Context.RECEIVER_EXPORTED has been introduced in Api 33
https://developer.android.com/reference/android/content/Context#RECEIVER_EXPORTED

Starting from 2023-08-31, Android 33 is the minimun required version:
https://developer.android.com/google/play/requirements/target-sdk?hl=en

So if you target your project to Android 33, the error disappears.

**Comment by thachsteven** [comment]
> @ruipaulo Context.RECEIVER_EXPORTED has been introduced in Api 33 https://developer.android.com/reference/android/content/Context#RECEIVER_EXPORTED
> 
> Starting from 2023-08-31, Android 33 is the minimun required version: https://developer.android.com/google/play/requirements/target-sdk?hl=en
> 
> So if you target your project to Android 33, the error disappears.

You save my day. Tks

**Comment by vaibhavgadekarapptware** [comment]
Still having same issue for Android 34, Any update?

**Comment by kaishleyTE** [comment]
Same issue here for Android 34 😕

**Comment by NoahSimajji** [comment]
> Same issue here for Android 34 😕

My Current React native version 
"react-native": "0.71.14",

Hey I upgraded my library to "react-native-blob-util": "0.19.11" from "react-native-blob-util": "0.19.1" and it worked fine after that. I think you can try that as well. My Android and IOS working fine now.

**Comment by kaishleyTE** [comment]
> > Same issue here for Android 34 😕
> 
> My Current React native version "react-native": "0.71.14",
> 
> Hey I upgraded my library to "react-native-blob-util": "0.19.11" from "react-native-blob-util": "0.19.1" and it worked fine after that. I think you can try that as well. My Android and IOS working fine now.

Hi, my `react native` version is "0.72.7" and I am already using `react-native-blob-util` version 0.19.11 (latest). The android app works fine when `compileSdkVersion` and `targetSdkVersion` is set to `33`. However when changing the SDK version to `34`, we get that error. In addition, [as from August 31 2024](https://support.google.com/googleplay/android-developer/answer/11926878), apps being pushed to playstore will need to target SDK version `34`. 
 
 Which SDK version are you targetting? Try targetting version 34 and let me know if you get that error.
 Thank you for helping

**Comment by kaishleyTE** [comment]
I was able to solve the issue by following the below guide.

https://medium.com/@md.Azeem/reac-native-android-app-crash-after-upgrade-targetsdkversion-34-e521f0dd0e19

**Comment by Tarun24RN** [comment]
Why is the check Build.VERSION.SDK_INT >= 34 and not 33? [According to Android](https://developer.android.com/about/versions/13/features#runtime-receivers) non exported broadcast receivers should be available to +33 without requiring androidx.
I'm asking because we got a security scanner flagging "Context Registered Broadcast Receivers Not Protected with Permissions", so it would be a good idea from a security standpoint to apply this to 33 as well.
