### ISSUE TITLE
How to save files in android/media folder (Like how WhatsApp does)

### ISSUE THREAD

**Issue by victorkvarghese** [RonRadtke/react-native-blob-util#305]
Hi,

Thanks for supporting this library.

Im trying to download and save files in the file system like how WhatsApp does it.

WhatsApp stores files inside `android/media/com.whatsapp/`

I was able to download and save the file inside` /data/user/0/com.packagename/files `using this library. I tried `DocumentDir` and `PictureDir`.

```
let dirs = ReactNativeBlobUtil.fs.dirs
ReactNativeBlobUtil
        .config({
            // response data will be saved to this path if it has access right.
            path: dirs.DocumentDir + '/path-to-file.anything'
        })
        .fetch('GET', 'http://www.example.com/file/example.zip', {
            //some headers ..
        })
        .then((res) => {
            // the path should be dirs.DocumentDir + 'path-to-file.anything'
            console.log('The file saved to ', res.path())
        })

```
is there a way i can save them inside **media** folder instead of **data**?

I checked **mediastore** and other areas, but couldn't find a decent answer

**Comment by RonRadtke** [comment]
Yes you have to use the mediastore.
WhatsApp is just creating its own subfolder e.g. for images. You can do that too using the mediastore api

**Comment by victorkvarghese** [comment]
@RonRadtke Thanks for the reply.


I tried all paths in dir. But it all pointed to android/data not media. Maybe I'm doing it the wrong way 

Can you please share a link to documentation. I'm not familiar with mediastore. Will try again.

**Comment by RonRadtke** [comment]
https://github.com/RonRadtke/react-native-blob-util/wiki/MediaStore
Here, if you take a look at w.g. the createMediaFile you see the specific parentFolder parameter.
The copyToMediafile is probably exactly what you need

**Comment by victorkvarghese** [comment]
Hi @RonRadtke ,

i tried with this piece of code. but its getting saved inside `Download/MyApp/Images.`

What i need is `android/media/com.myapp/MyApp/Images`. Not sure if i'm doing some thing wrong.


```
 const onSavePressed = () => {
    ReactNativeBlobUtil.config({
      fileCache: true,
    })
      .fetch(
        'GET',
        'https://storage.googleapis.com/gweb-uniblog-publish-prod/original_images/HeroHomepage_2880x1200.jpg',
        // {Accept: 'application/octet-stream'},
        // JSON.stringify(dat),
      )
      .then(async res => {
        let result = await ReactNativeBlobUtil.MediaCollection.copyToMediaStore(
          {
            // name: filename, // name of the file
            name: 'HeroHomepage.jpg',
            parentFolder: 'MyApp/Images', // subdirectory in the Media Store, e.g. HawkIntech/Files to create a folder HawkIntech with a subfolder Files and save the image within this folder
            mimeType: 'image/png', // MIME type of the file
          },
          'Download', // Media Collection to store the file in ("Audio" | "Image" | "Video" | "Download")
          path, // Path to the file being copied in the apps own storage
        );

        console.log('result test......', result);
      });
  };
```

**Comment by RonRadtke** [comment]
For that you would need the permission "MANAGE_EXTERNAL_STORAGE" and it is unlikely google will acceot your app in the app stire with this permission. But also this library would not support accessing files stored there
