### ISSUE TITLE
Please remove <application> tag in AndroidManifest.xml

### ISSUE THREAD

**Issue by AlixH** [RonRadtke/react-native-blob-util#307]
Why using an application tag inside a library ? It's causing merging issues with the label attribute

**Comment by RonRadtke** [comment]
I can't. The provider part of the application Tag is nedded in order for the library to be allowed to access files stored / owned by the app that is using the lib

**Comment by RonRadtke** [comment]
Okay, nut I think I van remove the android:name from the application tag without it causing any problems.
That also should fix your problems but keeps the lib functional. I just must test that first to be sure
