### ISSUE TITLE
Getting processDebugManifest build error on Android

### ISSUE THREAD

**Issue by anniewey** [RonRadtke/react-native-blob-util#322]
Suspecting it's gradle related problem. Cox it was working fine on ios but couldn't get past build in android even after gradle clean.

"react-native-blob-util": "^0.19.6",
"react-native": "0.67.4",

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-blob-util:processDebugManifest'.
> Error while evaluating property 'packageOverride' of task ':react-native-blob-util:processDebugManifest'
   > Failed to calculate the value of task ':react-native-blob-util:processDebugManifest' property 'packageOverride'.
      > Failed to query the value of property 'applicationId'.
         > Package Name not found in /Users/xx/dev/my-app/node_modules/react-native-blob-util/android/src/main/AndroidManifest.xml
```

**Update 1:**
Tried to upgrade from `4.2.2` to `classpath("com.android.tools.build:gradle:7.1.3")` but getting different error instead.

```
/Users/xx/dev/my-app/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:41: error: package undefined does not exist
import undefined.ReactNativeBlobUtilPackage;
                ^
/Users/xx/dev/my-app/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:140: error: cannot find symbol
      new ReactNativeBlobUtilPackage(),
          ^
  symbol:   class ReactNativeBlobUtilPackage
  location: class PackageList
Note: /Users/xx/dev/my-app/android/app/src/debug/java/com/myapp/ReactNativeFlipper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

**Update 2:**
Build success with original config after downgrade library version to `v0.19.4`

**Comment by marcshilling** [comment]
FWIW I had the same/similar problem on 0.19.6...was getting an error on `import undefined.ReactNativeBlobUtilPackage`. Downgrading to 0.19.4 also fixed for me. Indicative of an issue in either 0.19.5 or 0.19.6 @RonRadtke!

**Comment by jmada** [comment]
I've tried 0.19.8 and still happened to me. Locking to 0.19.4 fixed for me.

**Comment by JJSLIoT** [comment]
I am facing the same issue on 0.19.9 as well

**Comment by RubenPM-dev** [comment]
FYI for anyone landing on this thread:

> [@Ammar-Abid92](https://github.com/Ammar-Abid92) from 0.21.x onwards I moved to a new base class to ensure compatibility with 0.77 and onwards. Sadly that means incompatibility with RN < 0.74 and you are using 0.73. so you will have to upgrade RN or keep using the 0.19.x But I forgot to write that in the docs, sorry. Will update the docs

https://github.com/RonRadtke/react-native-blob-util/issues/399#issuecomment-2569171396
