### ISSUE TITLE
Is it possible to download file from app cache using Download Manager

### ISSUE THREAD

**Issue by konchak007** [RonRadtke/react-native-blob-util#324]
I'm doing POST api call, send data
And receive from backend file(base64) pdf 
If I use Download Manager in config = receive an error 16
Mb there is solution to save this file inside cache and  after that to download to user folder ?

I

```
const res = await RNFetchBlob.config({
      addAndroidDownloads: {
        useDownloadManager: true,
      },
    }).fetch(
      'POST',
      url,
      {
        'Transfer-Encoding': 'Chunked',
        'access-token': token || '',
        'Content-Type': 'application/json',
      },
      JSON.stringify({
        type: 'daily',
        createdDateStart: moment(createdTime).format('YYYY-MM-DD'),
        fileType: 'pdf',
      }),
    )
```

error message: " Error: Download manager failed to download from  https:... Status Code = 16 "

**Comment by GabrielGomesBarbosa** [comment]
Please provide a complete error log

**Comment by konchak007** [comment]
> Please provide a complete error log

Error: Download manager failed to download from  https.... Status Code = 16

**Comment by GabrielGomesBarbosa** [comment]
Probably your application can't reach the URL that you want to get file, check the URL and all headers and params that you are passing.

**Comment by RonRadtke** [comment]
You can download it to file cache and then use the media store API to move it in the downloads, sure.
But that won't resolve issues with the download if these are on server side
