### ISSUE TITLE
After reinstalling the application, the images recorded by the library are no longer available

### ISSUE THREAD

**Issue by valery-lavrik** [RonRadtke/react-native-blob-util#326]
I ran into a problem...  I download the images and save them to a folder.  Everything works. Everything is fine with the images.   

`
			await config({
				path,
				fileCache: true,
				indicator: false,
				overwrite: true,
			}).fetch('GET', url, headers);
`

But if I reinstall the application, then these images will no longer be readable.  I get the error: "Permission Denied"
![image](https://github.com/RonRadtke/react-native-blob-util/assets/8047999/165da9be-d0af-4e93-886f-46b686e1179e)

I think that the problem is with the file access rights that are set to it when writing. But I can't find in the documentation how to set 777 file permissions.

How do I change the access rights to a file while downloading it to the Downloads folder?

**Comment by RonRadtke** [comment]
This is actually due to https://developer.android.com/about/versions/11/privacy/storage
And therefor this is an intended beahviour of newer android versions.
If you want your files to persist use e.g. mediastorage. But then you'll also need a document picker to get access to the files again.
Why do you want files to persist trough reinstallation of the app? The problem is, with reinstalling the app all internal files will be deleted and the app looses access to everything. Also all permissions.

**Comment by valery-lavrik** [comment]
@RonRadtke   But after all, I save files to the Downloads folder.  That's why I want to access the files again after reinstalling the application.  Shouldn't it work?

```
config({
    fileCache: true,
    indicator: true,
    overwrite: true,
    path: `${DownloadDir}/${file_name}`, // Download folder
    addAndroidDownloads: {
        useDownloadManager: true,
        notification: true,
        path: `${DownloadDir}/${file_name}`,
        description: 'download...',
        mediaScannable: true,
        title: file_name,
    },
})
    .fetch('GET', FILE_URL)
    .then(res => {
        ....
    })
```

**Comment by RonRadtke** [comment]
No it's one of the restrictions of the new scoped storage.
Apps only have access to files in their own internal storage /your app owns. And this one changes whith every install.
And when uninstalling / reinstalling your app looses ownership to all files or, for app internal storage, the files are deleted.

**Comment by valery-lavrik** [comment]
@RonRadtke    But then how do applications like total commander work that can open any files in Downloads that are clearly not created by them?

**Comment by RonRadtke** [comment]
These applications are using a special permission which allows them general file access. (Manage external storage)
But this one counts as high risk permission and therefor google is strict about apps using it. So you using it could lead to your app not being approved.
https://support.google.com/googleplay/android-developer/answer/10467955?hl=en
