### ISSUE TITLE
TypeError: null is not an object

### ISSUE THREAD

**Issue by davepaiva** [RonRadtke/react-native-blob-util#33]
**env**
`os`: macOS 10.15.7
`mobile device `: Motorolla power one, running stock android10
`react-native-blob-util version`: `0.13.7`
`react-native`: 0.61.5

**AndroidManifest.xml**
```
...
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
....
<application
    ...
    android:requestLegacyExternalStorage="true"
>
...
```

**code**
```
import ReactNativeBlobUtil from 'react-native-blob-util'


const tempImageUri = await ReactNativeBlobUtil.config({ fileCache: true }).fetch(`${image_url}`)
```
**error**
```
TypeError : null is not an object (evaluating 'ReactNativeBlobUtil.DocumentDir')
```

Any idea where I might be going wrong?

**Comment by GuilhermeBergamoBR** [comment]
Same thing here, any progress?

**Comment by RonRadtke** [comment]
are you using expo or a plain simple react-native project?

**Comment by GuilhermeBergamoBR** [comment]
It is an expo based project, but I already ejected

**Comment by davepaiva** [comment]
> are you using expo or a plain simple react-native project?

in my case this is not an expo project, it is a plain simple react-native project

**Comment by imranMnts** [comment]
@RonRadtke Do we have any update? 
I have the same issue and I'm using it in a React native CLI 0.63.4 project

**Comment by RonRadtke** [comment]
Sadly not. So far I am still failing in reproducing the problem on my devices / machines.
Using it myself with RN 63.3 in production, so I doubt it's the RN version...
It's also working fine on a new project for me

Could you please try to run a gradlew clean and also clean npm modules / reinstall them?

It sounds like something is off when  trying to load the reacht-native-blob-util.

**Comment by RonRadtke** [comment]
I actually managed to get this error now once too.
But I could find any reason for it. Resetting the build caches and reinstalling the NPM modules solved it for me.

**Comment by arunim2405** [comment]
@RonRadtke I am still facing this issue, reinstalling node_modules did not work for me, even tried npm start -- --reset-cache

**Comment by DonBranson** [comment]
> @RonRadtke I am still facing this issue, reinstalling node_modules did not work for me, even tried npm start -- --reset-cache

I was facing this problem with RN65, redux-persist-filesystem-storage 4.0.0, which uses react-native-blob-util 0.13.12. Manually removing 0.13.12 and `yarn add react-native-blob-util` installed 0.13.16, which fixed this problem for me.

**Comment by DonBranson** [comment]
> > @RonRadtke I am still facing this issue, reinstalling node_modules did not work for me, even tried npm start -- --reset-cache
> 
> I was facing this problem with RN65, redux-persist-filesystem-storage 4.0.0, which uses react-native-blob-util 0.13.12. Manually removing 0.13.12 and `yarn add react-native-blob-util` installed 0.13.16, which fixed this problem for me.

Okay, correction, this fixed Android. iOS:

```
❌  duplicate symbol '_bridgeRef' in
> libreact-native-blob-util.a(ReactNativeBlobUtil.o)
> librn-fetch-blob.a(RNFetchBlob.o)


❌  duplicate symbol '_fsQueue' in
> libreact-native-blob-util.a(ReactNativeBlobUtil.o)
> librn-fetch-blob.a(RNFetchBlob.o)


❌  duplicate symbol '_commonTaskQueue' in
> libreact-native-blob-util.a(ReactNativeBlobUtil.o)
> librn-fetch-blob.a(RNFetchBlob.o)


❌  duplicate symbol '_fileStreams' in
> libreact-native-blob-util.a(ReactNativeBlobUtilFS.o)
> librn-fetch-blob.a(RNFetchBlobFS.o)


❌  duplicate symbol '_expirationTable' in
> libreact-native-blob-util.a(ReactNativeBlobUtilNetwork.o)
> librn-fetch-blob.a(RNFetchBlobNetwork.o)


❌  ld: 5 duplicate symbols for architecture x86_64
```

**Comment by RonRadtke** [comment]
I fixed sth that could cause it, so probably you got that fix now.
I'm glad it's now working for you

**Comment by anujmpec** [comment]
I am facing issue in it "react-native-blob-util": "^0.13.16",
inside "react-native-pdf": "^6.4.0",
 "react-native": "0.63.4",

**Comment by AGIsmail** [comment]
This package is a dependency of `redux-persist-filesystem-storage`. Force upgrading the nested dependency to `0.13.17` allowed the app to start without errors.

Thank you!

**Comment by CoreyBovalina** [comment]
I'm also having the same issue with react-native-pdf 6.4 since they switch to react-native-blob-util from rn-fetch-blob.  Any way to fix this? I've added the latest react-native-blob-util and still broke.

**Comment by AGIsmail** [comment]
@CoreyBovalina If you're using `yarn` then can you try this?

1. Add this to `package.json`
```

    "resolutions": {
        "react-native-blob-util": "0.13.17"
    },
```
2. Add react-native-blob-util@0.13.17 as a dependency
3. Delete `node_modules` and run `yarn install` again

**Comment by CoreyBovalina** [comment]
>  "react-native-blob-util": "0.13.17"

in addition to doing having it as an added package as well? 

when I tried doing this and it didn't fix it before: yarn add react-native-pdf react-native-blob-util fbjs

**Comment by CoreyBovalina** [comment]
ok I tried with what you said and I get this:
`error: Error: Unable to resolve module react-native-blob-util from /Users/Corey/Code/cerebrum/vid/node_modules/react-native-pdf/index.js: react-native-blob-util could not be found within the project or in these directories:
  node_modules/react-native-pdf/node_modules
  node_modules
  ../node_modules`

**Comment by AaronDsilvaOpfuse** [comment]
Facing this issues on react native: "0.66.1"
react-native-blob-util: "0.13.17".

**Comment by RonRadtke** [comment]
- Delete node_modules folder (or make sure to delete rn-ftech-blob)
- Install react-native-blob-util as a standard dependency for your project
That's all, it should work. It sounds like your app is trying to find the library within of react-native-pdf. But there it won't be installed

**Comment by silverax** [comment]
Got the same issue here, I'm trying to use react-native-pdf.
I tried adding direct dependencies to react-native-blob-util versions .16, .17 and .18 to no avail
![image](https://user-images.githubusercontent.com/26744799/150990861-07c59798-4081-446e-86bd-bba892062ba0.png)

**Comment by SzymonGlab** [comment]
Same problem, updated `react-native-pdf` to newest version and according to their docs I installed `react-native-blob-util` - version 0.13.18. 

Android works fine but on iOS i get this error mentioned in the question:
`TypeError: null is not an object (evaluating 'ReactNativeBlobUtil.DocumentDir')`.

**Comment by chadzxrex** [comment]
For those who still face this issue, make sure you have linked the library in Podfile, and run npx pod-install again after linking it. 
`pod 'react-native-blob-util', :path => '../node_modules/react-native-blob-util'`

**Comment by yingwei1025** [comment]
Facing this same issues on
react native: "0.68.2"
react-native-pdf: "6.5.0",
react-native-blob-util: "0.13.18".
expo: "45.0.0"

how to make it work on expo
