### ISSUE TITLE
Errors in react-native-web

### ISSUE THREAD

**Issue by gavrilikhin-d** [RonRadtke/react-native-blob-util#335]
Using this library in `react-native-web` causes error
<img width="463" alt="image" src="https://github.com/RonRadtke/react-native-blob-util/assets/75179902/b8535469-d7dc-4f7c-bb58-c1466abf5827">

```
"react-native-blob-util": "^0.19.6"
```

**Comment by gavrilikhin-d** [comment]
In this code:
```ts
  await RNBlobUtil.fetch(
    "POST",
    `${BASE_URL}${url}`,
    {
      Authorization: `Bearer ${idToken}`,
      ["Content-Type"]: "application/octet-stream"
    },
    base64FromDataUri(sample.uri)
  )
```

**Comment by RonRadtke** [comment]
how are you importing it?

**Comment by gavrilikhin-d** [comment]
> how are you importing it?
```ts
import RNBlobUtil from "react-native-blob-util"
```

**Comment by RonRadtke** [comment]
You sre using react native for Web right?
This lib is using a lot of native code to offer the functionality. Unfortunately there is no implementation for react native for web and therefor you can't use the lib
