### ISSUE TITLE
Is it possible to create a blob from a local image uri?

### ISSUE THREAD

**Issue by BraveEvidence** [RonRadtke/react-native-blob-util#336]
* I am using `"react-native-blob-util": "^0.19.6"` and `"react-native": "0.73.4"`

* I am using react-native-image-picker to pick images. Once i get and image and have the image uri, i am not able to figure it out how to convert it to blob

```
 const response = await fetch(uri!);
      const imageBlob = await response.blob();

        const response = await ReactNativeBlobUtil.fs.readFile(uri!, 'base64');
        const blob = ReactNativeBlobUtil.polyfill.Blob([response], {
          type: 'image/jpeg',
        });
 
```

**Comment by BraveEvidence** [comment]
Here is my further debugging 


  ```
const blobData = await ReactNativeBlobUtil.fetch('GET', uri!);
  const blob = await blobData.blob(type!, 1024);
```


But I get error
![Simulator Screenshot - iPhone Xs - 2024-02-19 at 12 36 17](https://github.com/RonRadtke/react-native-blob-util/assets/24708929/035ca7b3-da9c-43de-a0a3-e3772aecf80f)
 saying

**Comment by emclab** [comment]
facing exactly the same problem. Tried to readFile the image into base64 first but hasn't figured out how to convert base64 to blob. React Native 0.70. ReactNativeBlobUtil 0.19.6

Tried the code below but the response doesn't have a blob
```
const response = await ReactNativeBlobUtil
        .config({ fileCache: true })
        .fetch('GET', `data:${_contentType};base64,${_base64}`);  //<< _base64 is the image data string in base64. _contentType is image/jpeg.
```

**Comment by emclab** [comment]
Found a closed issue here:  https://github.com/RonRadtke/react-native-blob-util/issues/297

Not sure if the solution (formData and XHRHttprequest by @RonRadtke) provided is working here as well.

**Comment by emclab** [comment]
Here is the conversion working on my RN 0.70.x:

import {decode, encode} from 'base-64';  //<<==yarn add base-64 if not available
// Convert base64 to blob 
    function base64ToUint8Array(base64) {
      try {      
        const binaryString = decode(base64); // Decode base64
        const len = binaryString.length;
        const bytes = new Uint8Array(len);
        for (let i = 0; i < len; i++) {
          bytes[i] = binaryString.charCodeAt(i);
        }
        return bytes;  //<<==bytes is the blob which is to be used directly in fetch PUT
      } catch (err) {
        return null;
      };
    }

**Comment by pritish-thub** [comment]
@emclab  Genius

**Comment by BraveEvidence** [comment]
@emclab Genius. Thank you
