### ISSUE TITLE
iOS privacy manifest

### ISSUE THREAD

**Issue by gabrielguilhoto** [RonRadtke/react-native-blob-util#342]
Starting May 1, Apple will require iOS submissions to the App Store to have privacy manifests describing the use of required reason APIs: https://developer.apple.com/news/?id=3d8a9yyh.

I used [a script](https://github.com/Wooder/ios_17_required_reason_api_scanner) to find required reason APIs in our project and it pointed to 4 uses by `react-native-blob-util`, at least in version 0.13.17:

* `NSFileSystemFreeSize` in `ReactNativeBlobUtilFS.m`
* `NSFileSystemSize` in `ReactNativeBlobUtilFS.m`
*  `NSURLContentModificationDateKey` in `ReactNativeBlobUtilFS.m`
* `lstat(` in `ReactNativeBlobUtil.h`

Could you please add the required privacy manifest?

**Comment by RonRadtke** [comment]
Pr for it is merged. I hope we hit everything.
