### ISSUE TITLE
dest.exists() check fails in writeStream() in files of type content://

### ISSUE THREAD

**Issue by sam-maverick** [RonRadtke/react-native-blob-util#347]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-blob-util@0.19.8` for the project I'm working on.

On files of type content:// (these are the files served through a [FileProvider](https://developer.android.com/training/secure-file-sharing/share-file)), dest.exists()  yields false and an error is thrown: 

> Error: Failed to create parent directory of 'content://...

So I made the modifications below to fix that. No sure how this may impact other kinds of files, though.

```diff
diff --git a/node_modules/react-native-blob-util/android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilStream.java b/node_modules/react-native-blob-util/android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilStream.java
index ef1e357..1f81a2b 100644
--- a/node_modules/react-native-blob-util/android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilStream.java
+++ b/node_modules/react-native-blob-util/android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilStream.java
@@ -148,11 +148,16 @@ public class ReactNativeBlobUtilStream {
      * @param callback Callback
      */
     void writeStream(String path, String encoding, boolean append, Callback callback) {
+        String resolved = ReactNativeBlobUtilUtils.normalizePath(path);
+
+        if (resolved != null)
+            path = resolved;
+
         try {
             File dest = new File(path);
             File dir = dest.getParentFile();
  
-            if (!dest.exists()) {
+            if (resolved != null && !dest.exists()) {
                 if (dir != null && !dir.exists()) {
                     if (!dir.mkdirs()) {
                         callback.invoke("ENOTDIR", "Failed to create parent directory of '" + path + "'");
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by RonRadtke** [comment]
Thank you I applied the chagnes locally. It would be awesome if you could use a pull request next time. It's just way too easy to make a small mistake when applying the changes manually.
