### ISSUE TITLE
Using writeStream() with content:// Uris

### ISSUE THREAD

**Issue by sam-maverick** [RonRadtke/react-native-blob-util#348]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-blob-util@0.19.8` for the project I'm working on.

I am working with files of type content:// (those are files shared through a [FileProvider](https://developer.android.com/training/secure-file-sharing/share-file), in Android).

While I did not have any issues with readStream(), I could not get writeStream() to work. The symptom was that it got stuck reading the file, never returning. It was the same symptom as with expo-file-system's readAsStringAsync (although for expo-file-system I don't complain because [they state that they do not suport content:// Uris](https://docs.expo.dev/versions/latest/sdk/filesystem/)). Also, it is the same symptom as with react-native-fs (I think they do not state whether they support content:// files). In any case, I decided to use react-native-blob-util, as suggested in [this post](https://stackoverflow.com/questions/46278019/how-do-i-read-file-with-content-uri-in-react-native-on-android).

So I made the modifications below to make it work. They are pretty much inspired (almost a copy-paste) on what is already being done in readStream().

- - - - - - - - - - - - - - - - -
**IMPORTANT**: **You will need to first apply my patch:** https://github.com/RonRadtke/react-native-blob-util/issues/347 before this one.
- - - - - - - - - - - - - - - - -

```diff
diff --git a/node_modules/react-native-blob-util/android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilStream.java b/node_modules/react-native-blob-util/android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilStream.java
index ef1e357..0987aa0 100644
--- a/node_modules/react-native-blob-util/android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilStream.java
+++ b/node_modules/react-native-blob-util/android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilStream.java
@@ -168,7 +168,18 @@ public class ReactNativeBlobUtilStream {
                 return;
             }
 
-            OutputStream fs = new FileOutputStream(path, append);
+            OutputStream fs;
+
+            if (resolved != null && path.startsWith(ReactNativeBlobUtilConst.FILE_PREFIX_BUNDLE_ASSET)) {
+                fs = ReactNativeBlobUtilImpl.RCTContext.getAssets().openFd(path.replace(ReactNativeBlobUtilConst.FILE_PREFIX_BUNDLE_ASSET, "")).createOutputStream ();
+            }
+            // fix issue 287
+            else if (resolved == null) {
+                fs = ReactNativeBlobUtilImpl.RCTContext.getContentResolver().openOutputStream(Uri.parse(path));
+            } else {
+                fs = new FileOutputStream(path, append);
+            }
+
             this.encoding = encoding;
             String streamId = UUID.randomUUID().toString();
             ReactNativeBlobUtilStream.fileStreams.put(streamId, this);
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by RonRadtke** [comment]
Same as for your other issue 
If applyed both, so I hope this works :)
Thank you I applied the chagnes locally. It would be awesome if you could use a pull request next time. It's just way too easy to make a small mistake when applying the changes manually.
