### ISSUE TITLE
 Stuck at start screen, can't close splash screen after install (Only ios)

### ISSUE THREAD

**Issue by NguyenPhatBG** [RonRadtke/react-native-blob-util#36]
env
os: macOS 10.15.6
devices: iphone 8, 11, ...

Dependencies:
"react": "17.0.1", 
"react-native": "0.64.0",
 "react-native-blob-util": "^0.13.7",
"react-native-bootsplash": "~3.2.0",

Example code:
const configOptions: ReactNativeBlobUtilConfig = {
	path: dirs.DownloadDir + `/${downloadName}`,
	trusty: true,
	fileCache: true,
	appendExt: 'xlsx' || 'pdf' || 'docx',
};
if (Platform.OS === 'android') {
	configOptions['addAndroidDownloads'] = {
		useDownloadManager: true,
		notification: true,
		title: strSuccess,
	}
}
ReactNativeBlobUtil.config(configOptions)
  .fetch('GET', downloadUrl, {
      Accept: 'application/json',
      'Content-Type': 'application/json',
      Authorization: Token,
    }).then().catch();

**Comment by RonRadtke** [comment]
Do you get any error?

**Comment by NguyenPhatBG** [comment]
@RonRadtke Currently, I'm not find any error on console debugger-ui, When I reverse commit history, everything working find, It's only not working on ios platform!

**Comment by OmedMilat** [comment]
I have the same issue with Android 8 & 10, using react-native version 0.63.3. I get this error: 

`Error: Requiring unknown module "undefined". If you are sure the module exists, try restarting Metro. You may also want to run `yarn` or `npm install`., js engine: hermes`

I am coming from rn-fetch-blob, 0.12.0 where everything was working.

**Comment by RonRadtke** [comment]
@OmedMilat please open a new issue for such things. Don't see how these two problems should be related.
But it sounds like either you are importing the module wrong or you dind't run a "npm install" first...
Please install the lib first, you might have to run a gradlw clean and then start the app.
If this doesn't help please check all your imports if your importing the lib correctly. And if any of your other libs might relay on rn-fetch-blob

**Comment by Yandamuri** [comment]
@RonRadtke You are right, `react-native-pdf `depends on `rn-fetch-blob`.

**Comment by RonRadtke** [comment]
Newer versions of react-native-pdf don't depend on rn-fetch-blob anymore but on this lib here. So updating should fix the issue (and removing rn-fetch-blob)
