### ISSUE TITLE
Android: Task :app:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by wygkzqa** [RonRadtke/react-native-blob-util#374]
I'm using versions 0.19.16 and 0.19.19，prompt “import undefined. ReactNativeBlobUtilPackage;”, but version 0.19.14 works fine.

<img width="438" alt="image" src="https://github.com/RonRadtke/react-native-blob-util/assets/7590234/8033c602-2963-4ba2-8c9b-6445bae51968">

**Comment by charlespalmerbf** [comment]
Yep, getting the same.
