### ISSUE TITLE
Issue with "Fetch Replacement"

### ISSUE THREAD

**Issue by khanhduy160397** [RonRadtke/react-native-blob-util#376]
Hi today I try to do a "Fetch Replacement"  here: https://github.com/RonRadtke/react-native-blob-util?tab=readme-ov-file#drop-in-fetch-replacement

Try to do a simple fetch replacement like docs: https://github.com/RonRadtke/react-native-blob-util/wiki/api#fetch-replacement

But I see some error and can not use like docs => So can I ask that this docs is **out-dated** or am I doing **wrong** at which step ?

Here is error I encounter: 

![image](https://github.com/user-attachments/assets/dfb094eb-e851-4794-890c-8f9c607f4177)

version **react-native-fetch-blob**: [0.10.8](https://www.npmjs.com/package/react-native-fetch-blob/v/0.10.8)
version **react-native**: [0.72](https://reactnative.dev/docs/0.72/getting-started)

Thank guys.

**Comment by RonRadtke** [comment]
Hi,
Please show the import and the const assignment. I assume something is off here

**Comment by khanhduy160397** [comment]
Hi @RonRadtke, here is the import and assignment

![image](https://github.com/user-attachments/assets/e7630924-fcdb-4344-8d0a-28b1eb414e13)

Step I do:

1. yarn add react-native-fetch-blob

2. yarn add @types/react-native-fetch-blob <== ( because I saw error as below )
3. Try replace window.fetch = global.fetch but still have same issue.

![image](https://github.com/user-attachments/assets/33a18111-d440-4973-a000-43d36991a739)

**Comment by RonRadtke** [comment]
Okay but this library here is react-native-blob-util.

**Comment by khanhduy160397** [comment]
Thank @RonRadtke, I think I will close this issue due to outdated library (react-native-fetch-blob)
