### ISSUE TITLE
Android download progress

### ISSUE THREAD

**Issue by scgough** [RonRadtke/react-native-blob-util#39]
Hi, first of all thanks for taking up this project! I have more of a question rather than an issue. 

Over on the `joltup` version of this there has been an ongoing issue w/ download progress on Android not working. It seems to be that if `useDownloadManager: true` no progress events fire back at all. 

I'm just wondering if this has been fixed or if not, is it on the radar? I'm happy to help test/give more info if I can!

**Comment by RonRadtke** [comment]
If think you're talking about this one: https://github.com/joltup/rn-fetch-blob/issues/697

No it's not fixed yet. And honestly I kinda forgot about this. The issues on the old repo are a huge mess... So it's pretty hard to see what needs fixing and what not. There are over 350 open issues. So if you know about more problems that should be fixed, please report them here so I can take a look at. I already fixed a bunch of urgent stuff already, and will again try to go through the issues and take over what is needed. But feel free to help if you have time for :)

So, I have it on the radar now, thanks

**Comment by Med-Ahmed-Kilani** [comment]
any updates on this bug ? or any other alternatives ?

**Comment by RonRadtke** [comment]
Fixed: https://github.com/RonRadtke/react-native-blob-util/pull/143
