### ISSUE TITLE
RNFetchBlob.session(...).remove(path) not removing path from session list

### ISSUE THREAD

**Issue by varemel** [RonRadtke/react-native-blob-util#393]
Hello,

Thanks for your contribution.

Found bug with session remove method. It doesn't remove item from list.

`i` will be item (=path string) and not index of element. This code will never find item to delete, because `list[i]` will always be `undefined`.

https://github.com/RonRadtke/react-native-blob-util/blob/07ac60c66dc7603e7f1de52713a28e95e654ec55/class/ReactNativeBlobUtilSession.js#L42
```
  remove(path:string):RNFetchBlobSession {
    let list = sessions[this.name]
    for(let i of list) {
      if(list[i] === path) {
        sessions[this.name].splice(i, 1)
        break;
      }
    }
    return this
  }
```

I suggest fix. Do you want me to create a PR?
```
  remove(path:string):ReactNativeBlobUtilSession {
    let list = sessions[this.name];
    for (let i = 0; i < list.length; i++) {
      if (list[i] === path) {
        sessions[this.name].splice(i, 1);
        break;
      }
    }
    return this;
  }
```

**Comment by RonRadtke** [comment]
Hi, thank you for the report.
Yes please create a PR and I will merge it

**Comment by varemel** [comment]
@RonRadtke Hi,
I created PR. But I couldn't setup jest to write tests. Is it ok to not include test?

**Comment by RonRadtke** [comment]
Yes no problem. Thank you for the PR.
