### ISSUE TITLE
Sync Windows impl to latest

### ISSUE THREAD

**Issue by asklar** [RonRadtke/react-native-blob-util#43]
Hey @RonRadtke would it be possible to do these two things?
- sync the copy of the code in this repo to the latest in [avmoroz's PR](https://github.com/joltup/rn-fetch-blob/pull/701)? I see there have been at least a couple of commits since your message in the PR, so it would be good to sync.
- add `#include <windows.h>` to the module's pch.h to fix the issue described at the bottom of microsoft/react-native-windows#7970

**Comment by asklar** [comment]
Also @RonRadtke, you should join the react native maintainers discord server, I have a link for you to do that, feel free to reach out to me [on twitter](http://twitter.com/alexsklar)

**Comment by RonRadtke** [comment]
Hey,
the repo here is up to date with [avmoroz's PR.](https://github.com/joltup/rn-fetch-blob/pull/701)
I kept merging the changes there to my repo here :)
