### ISSUE TITLE
Windows status

### ISSUE THREAD

**Issue by tritao** [RonRadtke/react-native-blob-util#47]
Hello,

Does anyone know the status of Windows implementation in this repository?

I tried using it but was met with some compilation errors, more specifically:

The `fetchBlob` method is defined like this: `winrt::fire_and_forget RNFetchBlob::fetchBlob`. 

There are also multiple references to `RNFetchBlobState `.

But these classes declaration do not exist anymore, they were renamed to `ReactNativeBlobUtilState` and `ReactNativeBlobUtil`.

Seems like there was an automatic rename done but the code was left broken.

**Comment by RonRadtke** [comment]
Hey,
the status is, there are some people using it. So I'm a bit surprised.
If hopefully have time to check next week and fix broken things if needed.
Otherwise if you are up for, you're welcome to help improving it and creating a pull request with a fix.
I appreciate every help :)

**Comment by RonRadtke** [comment]
@tritao I made a commit on master fixing the wrong RNFetchBlobState.
Did a regex search, I hope I got all places.
Maybe you can test it with this commit? I'm currently on vacation and thus don't have access to my development environment.

**Comment by jaimecbernardo** [comment]
Hi @RonRadtke ,
Which commit do you mean?
The last commit on master was 16 hours ago.

**Comment by RonRadtke** [comment]
@jaimecbernardo Sorry one should also push and not just commit....
Now it's pushed too (535484d6)

**Comment by jaimecbernardo** [comment]
Thank you.
I've just tested it.

In the commit you've pushed, `RNFetchBlob::fetchBlob` was changed to `ReactNativeBlobUtilState::fetchBlob`.
It should've been changed to `ReactNativeBlobUtil::fetchBlob` instead.

After applying this change, it worked for me.
Thank you for the fixes.

**Comment by RonRadtke** [comment]
Great! Thank you very much @jaimecbernardo . I fixed that and am creating a new version for it
