### ISSUE TITLE
Typo in folder name

### ISSUE THREAD

**Issue by ttdatt** [RonRadtke/react-native-blob-util#50]
Folder name in android folder is still ReactNativeBloBUtil when doing `yarn add react-native-blob-util` or `npm i react-native-blob-util`
https://github.com/RonRadtke/react-native-blob-util/issues/26

**Comment by RonRadtke** [comment]
In both git, and the zip you can download for the releases it seems to be ok:
https://github.com/RonRadtke/react-native-blob-util/tree/master/android/src/main/java/com/ReactNativeBlobUtil

I'll have to check what is wrong there. Thanks for the info

**Comment by ttdatt** [comment]
Confirm fix in 0.13.11
