### ISSUE TITLE
Custom Fetch Wrapper

### ISSUE THREAD

**Issue by andurman** [RonRadtke/react-native-blob-util#54]
I want to ask about creating a custom fetch wrapper. I used to use my custom fetch when I use rn-fetch-blob (sample code is blow). 
![image](https://user-images.githubusercontent.com/26191085/127331101-4f6aa52b-cb3e-4a38-ada2-8e3ae7a6f72b.png)

When I tried to replace it with rn-fetch-blob-util, it didn't work. I couldn't get error message. I have searched documentations on the Internet. Couldn't see what I searched.

Is there any changes in rn-fetch-blob-util? What should I do? Can somebody help me?

**Comment by RonRadtke** [comment]
There are already plenty of changes.
We would need to get the error message to see what is happening.
When exactly to you get an error? During object creation or when using it? If the later, which function call?

You might have to use logcat (https://developer.android.com/studio/command-line/logcat) to get the error message, if you're developing for android.

**Comment by andurman** [comment]
When I replaced RNFetchBlob to RNFetchBlobUtil, fetch request gave error (in the picture below).
![image](https://user-images.githubusercontent.com/26191085/127495835-a9eb596e-fdc7-4e6b-a444-0af3d715c26f.png)
I followed Fetch.js:64, it goes node_modules/react-native-blob-util/polyfill/Fetch.js line 64. @RonRadtke

**Comment by RonRadtke** [comment]
Do you have a minimal example so I can reproduce the issue?
Preferable embedded as code and not as a screenshot.

**Comment by andurman** [comment]
I have created my own fetch function and replaced it with GLOBAL fetch. You can see sample codes below.

with rn-fetch-blob (this one works fine)

```
import RNFetchBlob from 'rn-fetch-blob';

const Fetch = RNFetchBlob.polyfill.Fetch;
// replace built-in fetch
const myFetch = new Fetch({
  auto: false,
  trusty: false,
  binaryContentTypes: [
    'image/',
    'video/',
    'audio/',
    'foo/',
  ],
}).build();

GLOBAL.tmpFetch = myFetch;
GLOBAL.fetch = function(uri, options, ...args) {
  let d = new Date();
  const startTime = d.getTime();
  return GLOBAL.tmpFetch(uri, options, ...args)
    .then(response => {
      d = new Date();
      const endTime = d.getTime();
      console.log(`Fetch => ${uri} {${endTime - startTime} ms}`, {
        request: {
          uri,
          options,
          ...args,
        },
        response,
      });
      return response;
    })
    .catch(error => {
      console.log('Fetch error: ', error);
    });
};
```

with rn-fetch-blob-util

```
import ReactNativeBlobUtil from 'rn-fetch-blob-util';

const Fetch = ReactNativeBlobUtil.polyfill.Fetch;
// replace built-in fetch
const myFetch = new Fetch({
  auto: false,
  trusty: false,
  binaryContentTypes: [
    'image/',
    'video/',
    'audio/',
    'foo/',
  ],
}).build();

GLOBAL.tmpFetch = myFetch;
GLOBAL.fetch = function(uri, options, ...args) {
  let d = new Date();
  const startTime = d.getTime();
  return GLOBAL.tmpFetch(uri, options, ...args)
    .then(response => {
      d = new Date();
      const endTime = d.getTime();
      console.log(`Fetch => ${uri} {${endTime - startTime} ms}`, {
        request: {
          uri,
          options,
          ...args,
        },
        response,
      });
      return response;
    })
    .catch(error => {
      console.log('Fetch error: ', error);
    });
};
```

When I build my project with second example, it is catching error ;
```
 Fetch error:  TypeError: ReactNativeBlobUtil.config is not a function
    at Fetch.js:64
    at tryCallOne (core.js:37)
    at core.js:123
    at JSTimers.js:274
    at _callTimer (JSTimers.js:130)
    at _callImmediatesPass (JSTimers.js:181)
    at MessageQueue.callImmediates [as _immediatesCallback] (JSTimers.js:441)
    at MessageQueue.__callImmediates (MessageQueue.js:387)
    at MessageQueue.js:135
    at MessageQueue.__guard (MessageQueue.js:364)
```

**Comment by RonRadtke** [comment]
Thanks.
I pushed a commit that hopefully will fix the issue.
Could you please cross check it? It's no published yet, so just run a `npm install RonRadtke/react-native-blob-util` to get the latest commit.

**Comment by andurman** [comment]
It works well. Thank you for your helps.

**Comment by andurman** [comment]
Hello,

I want to ask you an error about this issue. In documentation, it says i can handle statusCode on catch block.
![image](https://user-images.githubusercontent.com/26191085/214038452-0f1dd909-f690-4520-91b1-2f129b27d317.png)

But when i try to handle statusCode, it always return undefined. I have a timeout exception but I couldn't handle it. It becomes in catch block and error is not an object. It return a string and this string is localized. I mean it writes in local language. How can i handle timeout exceptions?
