### ISSUE TITLE
Get error when download file on Huawei p30 pro and p30

### ISSUE THREAD

**Issue by weishisi** [RonRadtke/react-native-blob-util#55]
react-native: 0.63.3
"react-native-blob-util": "^0.13.11",

device info:
![image](https://user-images.githubusercontent.com/34361947/126258827-0d79fc80-d822-4d5d-b501-d12099fc573e.png)

![image](https://user-images.githubusercontent.com/34361947/126258420-ec08c596-fbd9-484e-8be8-b33510ee9fe5.png)

the error:
![image](https://user-images.githubusercontent.com/34361947/126258382-32825b4e-4cef-4b66-bf89-536546da75b8.png)

**Comment by RonRadtke** [comment]
Do you have the error message too?
There is no chance for me to find line 1124 in your app bundle, since it's specific to your app and might change every time you rebuild the app.

**Comment by Foveluy** [comment]
the code for this is 
`
u(new Error(h,p)):((f.path||f.fileCache||f.addAndroidDownloads||f.key||f.auto&&'blob'===p.respType)
`
you can find the same code in `index.android.bundle`.
the error thows from this line of code.
