### ISSUE TITLE
Linking Error due to Missing File

### ISSUE THREAD

**Issue by yfng96** [RonRadtke/react-native-blob-util#57]
react-native: 0.64.2
react-native-blob-util: ^0.13.11"

Hi, when i run react-native link react-native-blob-util, it returned: 
`Error: Cannot find module 'C:\Projects\..........\node_modules\react-native-blob-util\scripts\prelink.js'`

is there anyway to solve this issue?

I also tried to install the package through the command below, but error still occur
`npm install --save github:RonRadtke/react-native-blob-util#<branch_name>`

**Comment by RonRadtke** [comment]
There was a mistake in the npmignore.
I published an update right now with a few bugfixes. Including the new npmignore. So the new update should fix your problem.
But in general you should not have to link the lib manually.

**Comment by yfng96** [comment]
I see, thank you very much
