### ISSUE TITLE
Require cycle: node_modules/react-native-blob-util/index.js

### ISSUE THREAD

**Issue by yfng96** [RonRadtke/react-native-blob-util#58]
Hi, when compiling the app, the following warning is being displayed:
`Require cycle: node_modules/react-native-blob-util/index.js -> node_modules/react-native-blob-util/polyfill/index.js -> node_modules/react-native-blob-util/polyfill/Fetch.js -> node_modules/react-native-blob-util/index.js`

I found a solution from this repo, can we fix it with this?
> [joltup/rn-fetch-blob#183 (comment)](https://github.com/joltup/rn-fetch-blob/issues/183#issuecomment-450826541)

**Comment by RonRadtke** [comment]
Have to take a look into it.
The fix you mentioned was removed two days ago since it was leading to the next issue: https://github.com/RonRadtke/react-native-blob-util/issues/54
