### ISSUE TITLE
Empty PDF file on IOS

### ISSUE THREAD

**Issue by AlixH** [RonRadtke/react-native-blob-util#60]
* please provide the version of installed library and RN project. : RN 0.64.2, RNBlobUtil 0.13.7
* a sample code snippet/repository is very helpful to spotting the problem.
<img width="860" alt="Screenshot 2021-08-26 at 11 27 05" src="https://user-images.githubusercontent.com/32574035/130938336-462e8be1-b560-46f0-980f-d46ab0d16faf.png">

When downloading a PDF file through the above method, it works on Android but on IOS, an empty files opens and nothing is to be found inside the iPhone filesystem

**Comment by RonRadtke** [comment]
What is your `downloadedFilePath` ?
Did you try changing it? In iOS only DocumentDir and CacheDir will work.

**Comment by AlixH** [comment]
> What is your `downloadedFilePath` ?
> Did you try changing it? In iOS only DocumentDir and CacheDir will work.

I am using this:
const downloadedFilePath = ReactNativeBlobUtil.fs.dirs.DownloadDir + '/' + fileName;

**Comment by AlixH** [comment]
Ok it works with documentDir ! But is there a way to download a file without opening/displaying it like on Android ?

**Comment by RonRadtke** [comment]
What do you mean without displaying?
You don't have to call "openDocument". It would be possible to simply save the file to disk without opening it.

**Comment by AlixH** [comment]
When I dont use openDocument, I don't find any file on the iPhone (to have the file on the iPhone while using openDocument, I have to click on 'save to files')

**Comment by RonRadtke** [comment]
The file is saved within the apps directory, since all apps on iOS live in their own sandbox.
There is currently no possibility to save it directly to downloads / photos / ...

**Comment by AlixH** [comment]
Oh I see !
So then, how can the app access the saved documents (to delete them for exemple, or open them for the user)

**Comment by AlixH** [comment]
Oh I see ! Thanks a lot

**Comment by AlanWen2016** [comment]
In my case,  The file path contains more than 255 characters
