### ISSUE TITLE
Not getting continuous upload progress in iOS 

### ISSUE THREAD

**Issue by akhilsanker** [RonRadtke/react-native-blob-util#61]
Hi,

In iOS the upload progress is not continuous whereas in android is getting continuous progress.

Sample code:
```
import RNFetchBlob from 'react-native-blob-util';

 const apiPostdata = [
    {
      data: RNFetchBlob.wrap(imageUri),
      filename: imageUri.replace(/^.*[\\\/]/, ''),
      name: imageField,
      type: 'image/jpg'
    },
    ...apiBodyUpdated
  ];

  const apiHeader: Record<string, any> = header || {
    Authorization: `Bearer ${accessToken}`,
    'Content-Type': 'multipart/form-data'
  };

  return RNFetchBlob
    .config({ IOSBackgroundTask: true })
    .fetch('POST', apiUrl, apiHeader, apiPostdata)
    .progress((received, total) => {
      if (progress) {
        progress(received / total);
      }
    })
    .uploadProgress(
      { interval: 1 }, (written, total) => {
        console.log(written / total, 'written / total'); // => always returns 1 in iOS but in android its progress from 0 to 1

        if (progress) {
          progress(written / total);
        }
      }
    )
    .then((res) => {
      if (res.respInfo.status === 201) {
        return res.json();
      }
      return res;
    })
    .catch((error) => Promise.reject(error));
```
Here in  `.progress()`, written/ total  always return 1 in iOS while uploading but in android value ranges from 0 to 1 thus getting a continuous progress.

Versions using:

react-native-blob-util:  0.13.13
react-native: 0.64.0
react: 17.0.1
Android Studio: 4.1 AI-201.8743.12.41.7199119
Xcode: 12.5.1/12E507

In iOS

https://user-images.githubusercontent.com/32122016/131351354-11500773-2f54-4fe8-89f8-451c59e87c7a.mov

In Android

https://user-images.githubusercontent.com/32122016/131351582-badd4cee-d9c2-4a51-ac3b-9e01fcb5a92c.mov

Is there anything that is missing or is it the default behaviour in iOS ?

Thanks.

**Comment by cristianoccazinsp** [comment]
Can you hook into XCode and debug the lines around here? https://github.com/RonRadtke/react-native-blob-util/blob/master/ios/ReactNativeBlobUtilRequest.m#L321 (download) and https://github.com/RonRadtke/react-native-blob-util/blob/master/ios/ReactNativeBlobUtilRequest.m#L436 (upload)

Does the download handler work as expected?  I have a feeling this code hasn't been updated in a long time and lots of deprecated/outdated functions are in use.  I haven't tested this myself, but It looks like the bug shouldn't be hard to spot.

**Comment by akhilsanker** [comment]
Hi @cristianoccazinsp ,

Thanks for the reply. Will have a try and let you know.

Thanks

**Comment by akhilsanker** [comment]
Hi @cristianoccazinsp ,

Download progress also works like the same as upload progress.

Any solution for this behaviour in iOS ?

Thanks

**Comment by filipef101** [comment]
What happens when you remove  .config(.. ?

**Comment by alessandro-bottamedi** [comment]
Same here, upload progress in iOS will only trigger two times, around 0.9 and then around completion... i do not have .config parameters...

**Comment by afilp** [comment]
I have the same problem in iOS.

**Comment by YanaSyritskaya** [comment]
The same problem in iOS.

**Comment by liukai-2p** [comment]
有解决办法吗

**Comment by skizzo** [comment]
Facing this too in iOS / react-native `0.71.7` / react-native-blob-util `0.17.3`. Any updates?

**Comment by filipef101** [comment]
@skizzo I would start by checking this
> Can you hook into XCode and debug the lines around here? https://github.com/RonRadtke/react-native-blob-util/blob/master/ios/ReactNativeBlobUtilRequest.m#L321 (download) and https://github.com/RonRadtke/react-native-blob-util/blob/master/ios/ReactNativeBlobUtilRequest.m#L436 (upload)
> 
> Does the download handler work as expected? I have a feeling this code hasn't been updated in a long time and lots of deprecated/outdated functions are in use. I haven't tested this myself, but It looks like the bug shouldn't be hard to spot.

**Comment by skizzo** [comment]
First of all, thanks for your quick reply, @filipef101! 

The [`didReceiveData()` function in ReactNativeBlobUtilRequest.mm](https://github.com/RonRadtke/react-native-blob-util/blob/132051c1204051f5148a0b4bfede00ed99f47c44/ios/ReactNativeBlobUtilRequest.mm#LL329C28-L329C28) is only called a single time for a downloaded file, with the `receivedBytes` value set to the total file size.

I thought this might have to do with the configuration of our server where the file is loaded from, but even when trying to download an image from a placeholder service (in my case, https://placehold.co/1920x1080.png), the progress event is fired only once with 100%.

**Comment by RonRadtke** [comment]
> Just one more question, may I ask for the reason why the values for `received` and `total` in the `.progress()` function are returned as Strings, and not Numbers?

That's a good question - but in general all events arepassed as string or dict to JS . For the future only strings. But likely the typecast is simply missing.

**Comment by dongbach69** [comment]
I have the same problem in iOS. have anyone fixed it?

**Comment by lijianow** [comment]
This is a serious bug, and it still exists

**Comment by akhilsanker** [comment]
@RonRadtke ,  why did you close the ticket. Still facing the issue.
