### ISSUE TITLE
when I  am create .aab in android application get crash on launch show following error

### ISSUE THREAD

**Issue by vishalcodiant** [RonRadtke/react-native-blob-util#63]
when I am creating .aab in the android application get crashes on launch App. 

npm is working fine if we generate release apk but now google play only takes .aab bundle. 

On app open show following error in android studio log.

This line is also added in AndroidManifest.xml
 `android:requestLegacyExternalStorage="true"
`

"react-native": "0.63.3",
"react-native-blob-util": "^0.13.14",
 Android version 8,10,11

![image](https://user-images.githubusercontent.com/73869553/132087097-933d4a64-57e1-4b49-aea2-e27b02b0d7e6.png)

If we change storage again we received this error.

![image](https://user-images.githubusercontent.com/73869553/132082507-397fe2b7-c4b7-47a8-a705-afc4979bc8d9.png)

**Comment by RonRadtke** [comment]
That error happens after we checked the path exists and that the path is a directory.
Does it work on other Android versions?
Are you using legacy storage?
Which path do you try to access?

**Comment by vishalcodiant** [comment]
Yes I have checked with Android 8, 10, and 11.

**Comment by RonRadtke** [comment]
You're calling the `lstat` method somewhere in your code. This one is leading to the crash.
Could you please post the code you're calling there? Especially the path you're calling.

**Comment by RonRadtke** [comment]
The bundling shouldn't change anything. App stores simply creates an apk for you when installing the app.
You said you changed the storage.
What did you change there?
Because it might be storage / permission related.
