### ISSUE TITLE
Incompatible with AGP 7 - Plugin with id 'maven' not found

### ISSUE THREAD

**Issue by kklopfenstein** [RonRadtke/react-native-blob-util#67]
When building with the newest version of the Android Gradle Plugin 7.0.1 (using Gradle 7.0.2) the following error occurs:

```
* What went wrong:
A problem occurred evaluating project ':react-native-blob-util'.
> Plugin with id 'maven' not found.
```

The `maven` gradle plugin is legacy and has been removed with 7.0.2.

https://docs.gradle.org/7.0/userguide/upgrading_version_6.html#removal_of_the_legacy_maven_plugin

The solution would be to use the newer `maven-publish` plugin which is compatible with Gradle 7.

Note that this is using `react-native-blob-util` version `0.13.15`.

**Comment by coreysnyder** [comment]
Bump. Very interested in whether this will get upgraded for Android 12 support.

**Comment by kklopfenstein** [comment]
https://github.com/RonRadtke/react-native-blob-util/pull/68

I put up a PR to fix the build.gradle file so that it is compatible with Gradle 7.

**Comment by RonRadtke** [comment]
@coreysnyder Yes definitely.
@kklopfenstein thank you very much for your PR. Was gonna ask if someone could help out since I'm currently very busy. I'll have a look at it today or tomorrow and will directly merge / release a new version if it looks ok
