### ISSUE TITLE
android build error after upgrading RN to 0.66.1 

### ISSUE THREAD

**Issue by keremoge** [RonRadtke/react-native-blob-util#72]
After upgrading RN from 0.64.3 to 0.66.1 I got these issues while gradle build;

`FAILURE: Build failed with an exception.

* Where:
Build file '/Users/ogge/gitlab/client/mobile-branch/node_modules/react-native-blob-util/android/build.gradle' **line: 71**
https://github.com/RonRadtke/react-native-blob-util/blob/06f8c707e56331e587da0b4b65aebac9411265d0/android/build.gradle#L71

* What went wrong:
A problem occurred configuring project ':react-native-blob-util'.
> Could not resolve all files for configuration ':react-native-blob-util:debugCompileClasspath'.
   > Failed to transform react-native-0.66.1.aar (com.facebook.react:react-native:0.66.1) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for AarToClassTransform: /Users/ogge/.gradle/caches/transforms-3/fd230f9f99ee8d8aba366ad28e366264/transformed/jetified-react-native-0.66.1.aar.
         > /Users/ogge/.gradle/caches/transforms-3/fd230f9f99ee8d8aba366ad28e366264/transformed/jetified-react-native-0.66.1.aar (No such file or directory)
   > Failed to transform infer-annotation-0.18.0.jar (com.facebook.infer.annotation:infer-annotation:0.18.0) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for IdentityTransform: /Users/ogge/.gradle/caches/transforms-3/22b5f77369671d9580db39078b8ddafa/transformed/jetified-infer-annotation-0.18.0.jar.
         > File/directory does not exist: /Users/ogge/.gradle/caches/transforms-3/33c44f5fe84672f869db208467880345/transformed/jetified-jsr305-3.0.2.jar
   > Failed to transform jsr305-3.0.2.jar (com.google.code.findbugs:jsr305:3.0.2) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for IdentityTransform: /Users/ogge/.gradle/caches/transforms-3/33c44f5fe84672f869db208467880345/transformed/jetified-jsr305-3.0.2.jar.
         > File/directory does not exist: /Users/ogge/.gradle/caches/transforms-3/33c44f5fe84672f869db208467880345/transformed/jetified-jsr305-3.0.2.jar
   > Failed to transform kotlin-annotations-jvm-1.3.72.jar (org.jetbrains.kotlin:kotlin-annotations-jvm:1.3.72) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for IdentityTransform: /Users/ogge/.gradle/caches/transforms-3/613d7c7f9bf82af4930cc79507a5ce5b/transformed/jetified-kotlin-annotations-jvm-1.3.72.jar.
         > File/directory does not exist: /Users/ogge/.gradle/caches/transforms-3/33c44f5fe84672f869db208467880345/transformed/jetified-jsr305-3.0.2.jar
   > Failed to transform proguard-annotations-1.19.0.jar (com.facebook.yoga:proguard-annotations:1.19.0) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.version=7, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for IdentityTransform: /Users/ogge/.gradle/caches/transforms-3/5aa05c299b265108d886e0cf68c99250/transformed/jetified-proguard-annotations-1.19.0.jar.
         > File/directory does not exist: /Users/ogge/.gradle/caches/transforms-3/33c44f5fe84672f869db208467880345/transformed/jetified-jsr305-3.0.2.jar
   > Failed to transform javax.inject-1.jar (javax.inject:javax.inject:1) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for IdentityTransform: /Users/ogge/.gradle/caches/transforms-3/56dbb217dc85f32971f2748632655d11/transformed/jetified-javax.inject-1.jar.
         > File/directory does not exist: /Users/ogge/.gradle/caches/transforms-3/33c44f5fe84672f869db208467880345/transformed/jetified-jsr305-3.0.2.jar
   > Failed to transform autofill-1.1.0.aar (androidx.autofill:autofill:1.1.0) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for AarToClassTransform: /Users/ogge/.gradle/caches/transforms-3/c0f09cf12b8e21b8b61c77272a0e9f7d/transformed/jetified-autofill-1.1.0.aar.
         > /Users/ogge/.gradle/caches/transforms-3/c0f09cf12b8e21b8b61c77272a0e9f7d/transformed/jetified-autofill-1.1.0.aar (No such file or directory)
   > Failed to transform fresco-2.5.0.aar (com.facebook.fresco:fresco:2.5.0) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for AarToClassTransform: /Users/ogge/.gradle/caches/transforms-3/bfd87dce7f0f45a8fad452478ee5ddf2/transformed/jetified-fresco-2.5.0.aar.
         > /Users/ogge/.gradle/caches/transforms-3/bfd87dce7f0f45a8fad452478ee5ddf2/transformed/jetified-fresco-2.5.0.aar (No such file or directory)
   > Failed to transform fbcore-2.5.0.aar (com.facebook.fresco:fbcore:2.5.0) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for AarToClassTransform: /Users/ogge/.gradle/caches/transforms-3/21ebd7982dcb5c18d6062c2341579796/transformed/jetified-fbcore-2.5.0.aar.
         > /Users/ogge/.gradle/caches/transforms-3/21ebd7982dcb5c18d6062c2341579796/transformed/jetified-fbcore-2.5.0.aar (No such file or directory)
   > Failed to transform soloader-0.10.1.aar (com.facebook.soloader:soloader:0.10.1) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for AarToClassTransform: /Users/ogge/.gradle/caches/transforms-3/367d31367351654fa737409b3bf42339/transformed/jetified-soloader-0.10.1.aar.
         > /Users/ogge/.gradle/caches/transforms-3/367d31367351654fa737409b3bf42339/transformed/jetified-soloader-0.10.1.aar (No such file or directory)
   > Failed to transform annotation-0.10.1.jar (com.facebook.soloader:annotation:0.10.1) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for IdentityTransform: /Users/ogge/.gradle/caches/transforms-3/1de81763ff23ccf6c21a1e3b5e8e5684/transformed/jetified-annotation-0.10.1.jar.
         > File/directory does not exist: /Users/ogge/.gradle/caches/transforms-3/33c44f5fe84672f869db208467880345/transformed/jetified-jsr305-3.0.2.jar
   > Failed to transform nativeloader-0.10.1.jar (com.facebook.soloader:nativeloader:0.10.1) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for IdentityTransform: /Users/ogge/.gradle/caches/transforms-3/5a2b6eb034dd42ce3e42b5e032cc5667/transformed/jetified-nativeloader-0.10.1.jar.
         > File/directory does not exist: /Users/ogge/.gradle/caches/transforms-3/33c44f5fe84672f869db208467880345/transformed/jetified-jsr305-3.0.2.jar
   > Failed to transform ui-common-2.5.0.aar (com.facebook.fresco:ui-common:2.5.0) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for AarToClassTransform: /Users/ogge/.gradle/caches/transforms-3/ef18b333dc28485cd4ebfd1a067f791e/transformed/jetified-ui-common-2.5.0.aar.
         > /Users/ogge/.gradle/caches/transforms-3/ef18b333dc28485cd4ebfd1a067f791e/transformed/jetified-ui-common-2.5.0.aar (No such file or directory)
   > Failed to transform drawee-2.5.0.aar (com.facebook.fresco:drawee:2.5.0) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for AarToClassTransform: /Users/ogge/.gradle/caches/transforms-3/a32319ae963e1fc640980c95cc8677d0/transformed/jetified-drawee-2.5.0.aar.
         > /Users/ogge/.gradle/caches/transforms-3/a32319ae963e1fc640980c95cc8677d0/transformed/jetified-drawee-2.5.0.aar (No such file or directory)
   > Failed to transform imagepipeline-2.5.0.aar (com.facebook.fresco:imagepipeline:2.5.0) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for AarToClassTransform: /Users/ogge/.gradle/caches/transforms-3/dfb6d4890b87db3ac7a1eee5ef3c8a75/transformed/jetified-imagepipeline-2.5.0.aar.
         > /Users/ogge/.gradle/caches/transforms-3/dfb6d4890b87db3ac7a1eee5ef3c8a75/transformed/jetified-imagepipeline-2.5.0.aar (No such file or directory)
   > Failed to transform imagepipeline-base-2.5.0.aar (com.facebook.fresco:imagepipeline-base:2.5.0) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for AarToClassTransform: /Users/ogge/.gradle/caches/transforms-3/96c822867203f47958e7f15a1ef7b04c/transformed/jetified-imagepipeline-base-2.5.0.aar.
         > /Users/ogge/.gradle/caches/transforms-3/96c822867203f47958e7f15a1ef7b04c/transformed/jetified-imagepipeline-base-2.5.0.aar (No such file or directory)
   > Failed to transform imagepipeline-native-2.5.0.aar (com.facebook.fresco:imagepipeline-native:2.5.0) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for AarToClassTransform: /Users/ogge/.gradle/caches/transforms-3/4f5ebc8e3c7280b5a3e98b1c7702752d/transformed/jetified-imagepipeline-native-2.5.0.aar.
         > /Users/ogge/.gradle/caches/transforms-3/4f5ebc8e3c7280b5a3e98b1c7702752d/transformed/jetified-imagepipeline-native-2.5.0.aar (No such file or directory)
   > Failed to transform memory-type-ashmem-2.5.0.aar (com.facebook.fresco:memory-type-ashmem:2.5.0) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for AarToClassTransform: /Users/ogge/.gradle/caches/transforms-3/024563af9087f4bd0f19430b0edf5d6d/transformed/jetified-memory-type-ashmem-2.5.0.aar.
         > /Users/ogge/.gradle/caches/transforms-3/024563af9087f4bd0f19430b0edf5d6d/transformed/jetified-memory-type-ashmem-2.5.0.aar (No such file or directory)
   > Failed to transform memory-type-native-2.5.0.aar (com.facebook.fresco:memory-type-native:2.5.0) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for AarToClassTransform: /Users/ogge/.gradle/caches/transforms-3/8a59e12db255f05cb0ed32e6acba4713/transformed/jetified-memory-type-native-2.5.0.aar.
         > /Users/ogge/.gradle/caches/transforms-3/8a59e12db255f05cb0ed32e6acba4713/transformed/jetified-memory-type-native-2.5.0.aar (No such file or directory)
   > Failed to transform memory-type-java-2.5.0.aar (com.facebook.fresco:memory-type-java:2.5.0) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for AarToClassTransform: /Users/ogge/.gradle/caches/transforms-3/4aa20566f9424dbb8d7798b1a676c6a9/transformed/jetified-memory-type-java-2.5.0.aar.
         > /Users/ogge/.gradle/caches/transforms-3/4aa20566f9424dbb8d7798b1a676c6a9/transformed/jetified-memory-type-java-2.5.0.aar (No such file or directory)
   > Failed to transform nativeimagefilters-2.5.0.aar (com.facebook.fresco:nativeimagefilters:2.5.0) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for AarToClassTransform: /Users/ogge/.gradle/caches/transforms-3/2737686cbd40f028d7ca253f81efdfbe/transformed/jetified-nativeimagefilters-2.5.0.aar.
         > /Users/ogge/.gradle/caches/transforms-3/2737686cbd40f028d7ca253f81efdfbe/transformed/jetified-nativeimagefilters-2.5.0.aar (No such file or directory)
   > Failed to transform nativeimagetranscoder-2.5.0.aar (com.facebook.fresco:nativeimagetranscoder:2.5.0) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for AarToClassTransform: /Users/ogge/.gradle/caches/transforms-3/d6044e9ef33529ab28d097a96a9691fd/transformed/jetified-nativeimagetranscoder-2.5.0.aar.
         > /Users/ogge/.gradle/caches/transforms-3/d6044e9ef33529ab28d097a96a9691fd/transformed/jetified-nativeimagetranscoder-2.5.0.aar (No such file or directory)
   > Failed to transform imagepipeline-okhttp3-2.5.0.aar (com.facebook.fresco:imagepipeline-okhttp3:2.5.0) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for AarToClassTransform: /Users/ogge/.gradle/caches/transforms-3/9ea698d40500b970ee7da351fece7e7a/transformed/jetified-imagepipeline-okhttp3-2.5.0.aar.
         > /Users/ogge/.gradle/caches/transforms-3/9ea698d40500b970ee7da351fece7e7a/transformed/jetified-imagepipeline-okhttp3-2.5.0.aar (No such file or directory)
   > Failed to transform okhttp-urlconnection-4.9.1.jar (com.squareup.okhttp3:okhttp-urlconnection:4.9.1) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api, org.jetbrains.kotlin.localToProject=public, org.jetbrains.kotlin.platform.type=jvm}.
      > Execution failed for IdentityTransform: /Users/ogge/.gradle/caches/transforms-3/cad4978a301d22becb3850462a7feffa/transformed/jetified-okhttp-urlconnection-4.9.1.jar.
         > File/directory does not exist: /Users/ogge/.gradle/caches/transforms-3/33c44f5fe84672f869db208467880345/transformed/jetified-jsr305-3.0.2.jar
   > Failed to transform okhttp-4.9.1.jar (com.squareup.okhttp3:okhttp:4.9.1) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api, org.jetbrains.kotlin.localToProject=public, org.jetbrains.kotlin.platform.type=jvm}.
      > Execution failed for IdentityTransform: /Users/ogge/.gradle/caches/transforms-3/b2a3ace5110d379955793c4b7bb55d1f/transformed/jetified-okhttp-4.9.1.jar.
         > File/directory does not exist: /Users/ogge/.gradle/caches/transforms-3/33c44f5fe84672f869db208467880345/transformed/jetified-jsr305-3.0.2.jar
   > Failed to transform okio-jvm-2.9.0.jar (com.squareup.okio:okio:2.9.0) to match attributes {artifactType=android-classes-jar, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api, org.jetbrains.kotlin.platform.type=jvm}.
      > Execution failed for IdentityTransform: /Users/ogge/.gradle/caches/transforms-3/c296df021c8d50649c8abbfac33e3e2b/transformed/jetified-okio-jvm-2.9.0.jar.
         > File/directory does not exist: /Users/ogge/.gradle/caches/transforms-3/33c44f5fe84672f869db208467880345/transformed/jetified-jsr305-3.0.2.jar
   > Failed to transform kotlin-stdlib-jdk8-1.4.10.jar (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.4.10) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for IdentityTransform: /Users/ogge/.gradle/caches/transforms-3/8338921157f3d3e261cae36c4e9aa433/transformed/jetified-kotlin-stdlib-jdk8-1.4.10.jar.
         > File/directory does not exist: /Users/ogge/.gradle/caches/transforms-3/33c44f5fe84672f869db208467880345/transformed/jetified-jsr305-3.0.2.jar
   > Failed to transform kotlin-stdlib-jdk7-1.4.10.jar (org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.4.10) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for IdentityTransform: /Users/ogge/.gradle/caches/transforms-3/f9eb32973940106e9b112e4b99545cb5/transformed/jetified-kotlin-stdlib-jdk7-1.4.10.jar.
         > File/directory does not exist: /Users/ogge/.gradle/caches/transforms-3/33c44f5fe84672f869db208467880345/transformed/jetified-jsr305-3.0.2.jar
   > Failed to transform kotlin-stdlib-1.4.10.jar (org.jetbrains.kotlin:kotlin-stdlib:1.4.10) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for IdentityTransform: /Users/ogge/.gradle/caches/transforms-3/ffd560b2f58ca3dedd248aff25ca202f/transformed/jetified-kotlin-stdlib-1.4.10.jar.
         > File/directory does not exist: /Users/ogge/.gradle/caches/transforms-3/33c44f5fe84672f869db208467880345/transformed/jetified-jsr305-3.0.2.jar
   > Failed to transform kotlin-stdlib-common-1.4.10.jar (org.jetbrains.kotlin:kotlin-stdlib-common:1.4.10) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for IdentityTransform: /Users/ogge/.gradle/caches/transforms-3/e87c819c797b9dc69f8efbd740f7b8c2/transformed/jetified-kotlin-stdlib-common-1.4.10.jar.
         > File/directory does not exist: /Users/ogge/.gradle/caches/transforms-3/33c44f5fe84672f869db208467880345/transformed/jetified-jsr305-3.0.2.jar
   > Failed to transform annotations-13.0.jar (org.jetbrains:annotations:13.0) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for IdentityTransform: /Users/ogge/.gradle/caches/transforms-3/c2e04f005763d1c36a380ec2e6c883ed/transformed/jetified-annotations-13.0.jar.
         > File/directory does not exist: /Users/ogge/.gradle/caches/transforms-3/33c44f5fe84672f869db208467880345/transformed/jetified-jsr305-3.0.2.jar
   > Failed to transform fbjni-java-only-0.2.2.jar (com.facebook.fbjni:fbjni-java-only:0.2.2) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for IdentityTransform: /Users/ogge/.gradle/caches/transforms-3/f8db01f3c7d9eb217180d63004ff1f2a/transformed/jetified-fbjni-java-only-0.2.2.jar.
         > File/directory does not exist: /Users/ogge/.gradle/caches/transforms-3/33c44f5fe84672f869db208467880345/transformed/jetified-jsr305-3.0.2.jar`

**Comment by keremoge** [comment]
same error for RN 0.65.1

**Comment by zxcpoiu** [comment]
Does #77 solves the problem?
