### ISSUE TITLE
Symbol collision with rn-fetch-blob

### ISSUE THREAD

**Issue by DonBranson** [RonRadtke/react-native-blob-util#75]
Our project uses redux-persist and ran into an issue on Android loading large state with AsyncStorage. Switching from AsyncStorage to redux-persist-filesystem-storage (which uses react-native-blob-util) works great to fix Android.

However, we ran into a problem with iOS because we also use react-native-pdf which requires rn-fetch-blob. The result is that react-native-blob-util and rn-fetch-blob are both declared, resulting in errors about duplicate symbols.

Is this something that could be addressed by changing the symbols in react-native-blob-util, and is that the best way to go?

```
❌  duplicate symbol '_bridgeRef' in
> libreact-native-blob-util.a(ReactNativeBlobUtil.o)
> librn-fetch-blob.a(RNFetchBlob.o)


❌  duplicate symbol '_fsQueue' in
> libreact-native-blob-util.a(ReactNativeBlobUtil.o)
> librn-fetch-blob.a(RNFetchBlob.o)


❌  duplicate symbol '_commonTaskQueue' in
> libreact-native-blob-util.a(ReactNativeBlobUtil.o)
> librn-fetch-blob.a(RNFetchBlob.o)


❌  duplicate symbol '_fileStreams' in
> libreact-native-blob-util.a(ReactNativeBlobUtilFS.o)
> librn-fetch-blob.a(RNFetchBlobFS.o)


❌  duplicate symbol '_expirationTable' in
> libreact-native-blob-util.a(ReactNativeBlobUtilNetwork.o)
> librn-fetch-blob.a(RNFetchBlobNetwork.o)
```

**Comment by RonRadtke** [comment]
The best way is to update react-native-pdf.
React-native-pdf got already updated to use this library here, instead of the old unmaintained.
Please update to the latest version of react-native-pdf to fix the problem. (https://github.com/wonday/react-native-pdf/releases/tag/v6.4.0)

**Comment by kvo1** [comment]
@RonRadtke 
I also got same issue. Followed the instruction in 6.4.0 but no luck at all.

**Comment by RonRadtke** [comment]
Did you uninstall rn-fetch-blob manually? Most likely you installed it manually and will have to uninstall it manually too. And afterwards try a clean build, it should fix the issue.
If not, please check if any other lib is liking to it.

**Comment by DonBranson** [comment]
> The best way is to update react-native-pdf. React-native-pdf got already updated to use this library here, instead of the old unmaintained. Please update to the latest version of react-native-pdf to fix the problem. (https://github.com/wonday/react-native-pdf/releases/tag/v6.4.0)

I tried that first, and it didn't work, so I probably did it wrong. :) I'll have another look.

**Comment by DonBranson** [comment]
@RonRadtke That fixed it. Thanks for your quick, helpful response!

**Comment by kvo1** [comment]
@RonRadtke -- I removed rb-fetch-blob manually and it works for me too. Thanks!

**Comment by ManosChr** [comment]
1.	Press npm list --depth=2 at project root folder and search for packages with dependency on rn-fetch-blob  
	2.	In my case was redux-persist-filesystem-storage
	3.	Update redux-persist-filesystem-storage to latest version which depends on react-native-blob-util
	4.	npm uninstall rn-fetch-blob
