### ISSUE TITLE
Missing android.support.FILE_PROVIDER_PATHS

### ISSUE THREAD

**Issue by cluth17** [RonRadtke/react-native-blob-util#76]
I started getting this error when downloading a PDF document to download folder on android after upgrading to target SDK 30 (although I'm not sure this was the cause of the issue). I was able to fix the problem by adding this to the application section of my AndroidManifest.xml:

`<provider
    android:name="com.ReactNativeBlobUtil.Utils.FileProvider"
    android:authorities="${applicationId}.provider"
    android:exported="false"
    android:grantUriPermissions="true">
    <meta-data
         android:name="android.support.FILE_PROVIDER_PATHS"
         android:resource="@xml/provider_paths" 
    />
</provider>`

And this to android > src > main > res > xml > provider_paths.xml:

`<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
    <external-path
        name="external_files"
        path="." />
    <files-path
        name="files-path"
        path="." /> 
    <cache-path
        name="cache-path"
        path="." /> 
</paths>`

I see these blocks are already defined in the blob-util library, I'm not sure why all the sudden my app was unable to pull it in from there. See:

https://github1s.com/RonRadtke/react-native-blob-util/blob/HEAD/android/src/main/AndroidManifest.xml

and:

https://github1s.com/RonRadtke/react-native-blob-util/blob/HEAD/android/src/main/res/xml/provider_paths.xml

I am using version 0.13.16 of react-native-blob-util and 0.64.1 of react-native.

**Comment by DeVoresyah** [comment]
is this already solved? @cluth17

**Comment by RonRadtke** [comment]
Can't reproduce and no further reports - thus closed. If the issue is still there, please create a new issue
