### ISSUE TITLE
[Android] actionViewIntent - activity won't start on Android 11+

### ISSUE THREAD

**Issue by Aure77** [RonRadtke/react-native-blob-util#78]
If your app target Android API 30+ (and use Android 11 device), 
using `ReactNativeBlobUtil.android.actionViewIntent(path, "application/pdf");` may do nothing.

After investing code, `startActivity` is not called because `resolveActivity` always return `null` here:
https://github.com/RonRadtke/react-native-blob-util/blob/93059e02fce7a97d30cc08e2ca6ff1c7b5ec0a49/android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtil.java#L135-L137

This is due to new [Android 11 package visibility](https://developer.android.com/about/versions/11/privacy/package-visibility).
I found a very interesting article that recommend do no not use _resolveActivity - startActivity_ pattern to avoid potential issues.
See: https://cketti.de/2020/09/03/avoid-intent-resolveactivity/

Why not using _try catch_ method for all Android version like here:
https://github.com/RonRadtke/react-native-blob-util/blob/93059e02fce7a97d30cc08e2ca6ff1c7b5ec0a49/android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtil.java#L145-L150
and that handle promise resolve/reject correctly.
(this workaround fix my issue with Android 11+ devices)

Full example to reproduce:

```javascript
// url = url to a pdf file
const PDF_PATH = `${ReactNativeBlobUtil.fs.dirs.CacheDir}/pdfs/Document.pdf`;
const res = await ReactNativeBlobUtil.config({
  fileCache: true,
  appendExt: "pdf",
  path: PDF_PATH
}).fetch("GET", url);
if (res) {
  ReactNativeBlobUtil.android.actionViewIntent(
    res.path(),
    "application/pdf"
  );
}

```

Further more, `actionViewIntent` promise is only resolved for Android SDK < 24
https://github.com/RonRadtke/react-native-blob-util/blob/93059e02fce7a97d30cc08e2ca6ff1c7b5ec0a49/android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtil.java#L147
Is this normal ?

**Comment by Aure77** [comment]
I created a patch if someone want to test fix:
https://gist.github.com/Aure77/5b0f75aee85fa897d6a3469146a197df

I can create a PR if confirmed.

**Comment by rutgervanwilligen** [comment]
Successfully applied and tested this patch in my project. Using `actionViewIntent` with a PDF file.

**Comment by rutgervanwilligen** [comment]
However, using the solution described in this closed [issue](https://github.com/RonRadtke/react-native-blob-util/issues/66#issuecomment-927663861) also fixes it for me. Not sure which of these is the way to go.

**Comment by RonRadtke** [comment]
@Aure77 would you be so kind to create a PR, I would merge it and create a new update for the lib then.
