### ISSUE TITLE
Android error: Error while casting ReactNativeBlobUtilFileResp

### ISSUE THREAD

**Issue by ricbermo** [RonRadtke/react-native-blob-util#88]
Hello, thanks for taking your time to maintain this library.
Somedays, ago, the "download" stopped working. I was able to track down and fix the issue (credits to @srbulovicdusan).

So, here's an image of the error
![image](https://user-images.githubusercontent.com/2601363/146596138-0e0f9e34-64df-4683-9025-d13fd4c18c1c.png)

The fix is,
1.  go to `ReactNativeBlobUtilFileResp.java` and add a new constructor like this:
```java
public ReactNativeBlobUtilFileResp(ResponseBody body) {
  super();
  this.originalBody = body;
}
```
then, in `ReactNativeBlobUtilReq.java` around line `607` replace how `ReactNativeBlobUtilFileResp` is instanciated.
```java
// remove or comment
ReactNativeBlobUtilFileResp = (ReactNativeBlobUtilFileResp) responseBody;
// use this
ReactNativeBlobUtilFileResp = new ReactNativeBlobUtilFileResp(responseBody);
```

Important information:

1. RN version:  `0.64.2`
2. lib. version: `0.13.18`

Note: I was not able to reproduce this issue on a "clean" RN project.

[Fix found here](https://github.com/joltup/rn-fetch-blob/issues/490#issuecomment-990899440)

**Comment by RonRadtke** [comment]
Thank you for the hint. In general the usage of a constructor is of course better than a cast. Even though I don't completely understand why the cast didn't work here.

**Comment by muhamad-rizki** [comment]
in my case this exception is happened on some device only, is there any workaround for this?

**Comment by RonRadtke** [comment]
So far, no. Unless we figure out why the cast isn't working or get it working with a costructor.
