### ISSUE TITLE
Readme links to anything in react-native-blob-util/wiki are broken

### ISSUE THREAD

**Issue by hapablap21** [RonRadtke/react-native-blob-util#91]
There are a number of features that I'd like to read more on, but all of the documentation in your wiki subfolder appears to be gone.  

Please either update the readme to point to the right place or put the right docs in place, thanks!

**Comment by DavidRieman** [comment]
This makes it hard to know the right steps to build+test (and thus hard to contribute).

**Comment by RonRadtke** [comment]
Thank you - and yes, I agree, basically the whole readme needs a remake
