### ISSUE TITLE
ReactNativeBlobUtil.fs.stat() is able to read only image path of image files, but fails to read path of .pdf, .docx, .ppt etc

### ISSUE THREAD

**Issue by Yandamuri** [RonRadtke/react-native-blob-util#93]
I am trying to pick a document by using [react-native-document-picker](https://github.com/rnmods/react-native-document-picker) from **Recents**(which opens by default in my mobile when I try to pick a document or image file) and result contains a `uri path` of the picked file. 

Following is the `uri path`(From **Recents**) of a image file,

    uri: "content://com.android.providers.media.documents/document/image%3A270542"

If I pass above uri path to `ReactNativeBlobUtil.fs.stat()`, getting following response successfully,

<img width="484" alt="Image Stat Res" src="https://user-images.githubusercontent.com/31983789/147628949-e18de592-526a-4bb9-b4ae-190108e7c2a1.png">

Following is the `uri path`(From **Recents**) of a .pdf file,

    uri: "content://com.android.providers.media.documents/document/document%3A748"

If I pass above uri path to `ReactNativeBlobUtil.fs.stat()`, getting following error,

<img width="595" alt="Screenshot 2021-12-29 at 12 08 15 PM" src="https://user-images.githubusercontent.com/31983789/147634049-4140c285-248e-431a-aafb-29001b5137ef.png">

Following is the `uri path`(From it's original location) of same `.pdf` (Which I tried to pick from **Recents**)

    uri: "content://media/external/file/272611"

Surprisingly this time `ReactNativeBlobUtil.fs.stat()` didn't give any error and result was as expected as shown below,

<img width="595" alt="Screenshot 2021-12-29 at 5 01 33 PM" src="https://user-images.githubusercontent.com/31983789/147657988-a9cda93a-4fd6-4ca2-a5cf-32dfdcd52b45.png">

Hence, This is evident that If any type(.jpg, .png, .pdf, .docx, .ppt) of file is picked from `it's original location`, then that path is readable by `ReactNativeBlobUtil.fs.stat()`. 

But If any file(.pdf, .docx, .ppt, ect) other than image file(.jpg, .png ect) is picked form **Recents**, then that path is not readable by `ReactNativeBlobUtil.fs.stat()`. 

**Environment Info:**

    "react": "17.0.2",
    "react-native": "0.66.4",
    "react-native-blob-util": "^0.13.18"

**Sample Code:**

        ReactNativeBlobUtil.fs.stat(path).then((stat) => {
            console.log('stat res', stat);
        });

May I know why `ReactNativeBlobUtil.fs.stat()` is unable to read the path of files like .pdf, .docx, .ppt, ect(other than image files like .jpg, .png) when they picked from **Recents**?

**Comment by RonRadtke** [comment]
Due to the nature of mediastore and the fact that you're expecting sth that can't hold true.
MediaStore is basically a database and you get one entry of that database. But a database entry can be a file but doesn't have to be a file. It can also be something else like it likely is for the "recently used" files.
The sta() method is returning the information it has, if the data doesn't include a file path, you can't get one.

Only reliable option is to use the functionality mediastore is offering, like opening a stream to the file.
And that will come with the upcoming release

**Comment by RonRadtke** [comment]
Version 0.14.0 is released and thus the mediastore API can be used. Please check the release notes for more information.
