### ISSUE TITLE
Unable to open read/write files on Android 11 - targetSdkVersion 30

### ISSUE THREAD

**Issue by brunofariasd** [RonRadtke/react-native-blob-util#95]
Hello guys,  I'm having problems using this library on Android 11, I can't read files in hidden folders. I'm trying acces '.../.Statuses' from Whatsapp path even with the necessary permissions and this dont work. Functions File access dont work. Any can solve this ?

ANDROID MANIFEST 

    <uses-permission
        android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission
        android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

"react-native": "0.66.3",
"react-native-blob-util": "^0.13.17",

**Comment by benjaminharringtonrose** [comment]
I just hit this issue last week - add this to your android manifest file:

    <queries>
        <intent>
            <action android:name="android.media.action.IMAGE_CAPTURE" />
        </intent>
        <intent>
            <action android:name="android.intent.action.GET_CONTENT" />
            <data android:mimeType="image/*" />
        </intent>
        <intent>
            <action android:name="android.intent.action.PICK" /> 
            <data android:mimeType="image/*" />
        </intent>
        <intent>
            <action android:name="android.intent.action.CHOOSER" />
        </intent>
    </queries>

Good luck!

**Comment by brunofariasd** [comment]
> I just hit this issue last week - @brunofariasd add this to your android manifest file:
> 
> ```
> <queries>
>     <intent>
>         <action android:name="android.media.action.IMAGE_CAPTURE" />
>     </intent>
>     <intent>
>         <action android:name="android.intent.action.GET_CONTENT" />
>         <data android:mimeType="image/*" />
>     </intent>
>     <intent>
>         <action android:name="android.intent.action.PICK" /> 
>         <data android:mimeType="image/*" />
>     </intent>
>     <intent>
>         <action android:name="android.intent.action.CHOOSER" />
>     </intent>
> </queries>
> ```
> 
> Good luck!

Thx for reply, but this doesn't worked. I can't read files only in hidden folders, in another folders this working fine.

note: this problem is only on android 11

**Comment by BrunoKarriqi** [comment]
I have the same problem. Any solution guys?

**Comment by RonRadtke** [comment]
Where is the file stored? Path?
And which version are you using?
If I remember correctly we had a fix for annissue there in 0.13.18

**Comment by brunofariasd** [comment]
> Where is the file stored? Path? And which version are you using? If I remember correctly we had a fix for annissue there in 0.13.18

Hello @RonRadtke , this issue only occurs in hidden folders. I'm already using the latest version of the package. 

I'm trying access this PATH: '/storage/emulated/0/Android/media/com.whatsapp/Whatsapp/Media/.Statuses'

Thx for reply.

**Comment by RonRadtke** [comment]
I think I found the solution:
https://stackoverflow.com/questions/70393591/cannot-access-hidden-folder-on-android-version-11-device-in-flutter

Maybe you can give it a try :)

**Comment by brunofariasd** [comment]
> I think I found the solution: https://stackoverflow.com/questions/70393591/cannot-access-hidden-folder-on-android-version-11-device-in-flutter
> 
> Maybe you can give it a try

I can use this permission, but i wouldn't be able to publish my app to play store. It is clearly stated in Google's policy unless you are a file manager app.

https://developer.android.com/training/data-storage/manage-all-files#all-files-access-google-play

**Comment by RonRadtke** [comment]
I don't what your app is. But the whatsapp status folder is in the private (scoped) storage of whatsapp. It's not located in any media collection so you can't access it without that permission.

Android made the policy even strikter with API 30, so that you can't access any file in an others app private external storage. See: https://developer.android.com/about/versions/11/privacy/storage
