### ISSUE TITLE
How to download file with custom name?

### ISSUE THREAD

**Issue by anniewey** [RonRadtke/react-native-blob-util#96]
Can I know how to save the file using custom name instead of `ReactNativeBlobUtilTmp_a67q49bf6lcukkzkwmuutb.png`?

I want to save the file name in format `${appName}-${timestamp}.png`. 
Is there a way save this file with custom name instead of specifying the {folder path/file name}?

```
 ReactNativeBlobUtil
    .config({fileCache : true, appendExt : 'png'})
    .fetch('GET', link)
    .then((res)=>{      
      console.log(res.path())
    })
    .catch((errorMessage)=>{
      console.log(errorMessage)
    })
```

**Comment by lehaidangdev** [comment]
Hi @anniewey, 

You can custom the path name using 'path' paremeter in config. Look at my example below.

` ReactNativeBlobUtil.config({
      fileCache: true,
      path: ReactNativeBlobUtil.fs.dirs.CacheDir + '/' + name + ext,
    })
      .fetch('GET', url)
      .then(res => {
        console.log(res.path());
      });`

Hope that help!

**Comment by anniewey** [comment]
@lehaidangdev yes, i understood the name can be set using the `path:{folder path/file name}`. As i mentioned in my question, is there other way to just rename the file without using the `path` as to use the default path?

> Is there a way save this file with custom name **instead of specifying the {folder path/file name}**?

**Comment by RonRadtke** [comment]
No, unless you rename the file afterwards manually
