### ISSUE TITLE
[Windows] Possible problems with paths with Umlaute/accentuated characters

### ISSUE THREAD

**Issue by creambyemute** [RonRadtke/react-native-blob-util#97]
Hello there :-)

I thought I may give you a heads-up about a possible problem with Umlaute/accentuated character in paths on the windows implementation.

Library Version: I'm currently using react-native-fs for Windows and rn-fetch-blob (old repo) for Android + iOS but plan on migrating in then near future.

RNFS with the windows implementation has a problem with paths that contain Umlaute/accentuated characters (ä, ö, ü, é, à etc).

As far as I've seen while glimpsing over the windows implementations the std::string --> std::filesystem::path conversion will probably result in similiar problems:

**Scenario / Repro Steps**
1. Create a windows user account that contains Umlaute/accentuated characters (ä, ö, ü, é, à etc), example: t.müstermann
2. Try to create a folder / read a file / write a file inside the application directory

I'm currently looking into it in RNFS and have made an example of changes here: https://github.com/itinance/react-native-fs/pull/952

Edit: See https://github.com/wwimmo/react-native-fs/pull/9 as an example PR on RN-FS

**Comment by creambyemute** [comment]
@RonRadtke We've used the above mentioned PR/Branch in our productive app since January and no new problems surfaced. I think it'd be safe to also change it for this library for Windows.

Do you maybe need a helping hand? I could do the changes in the following weeks after we've finished a MVP of a new product.

**Comment by RonRadtke** [comment]
@creambyemute it would be awesome if you could help out here and maybe create a PR for! Thank you very much for the offer

**Comment by RonRadtke** [comment]
@creambyemute how's it going? Didn't hear anything back anymore.
Do you think you can create a PR?
