### ISSUE TITLE
android.actionViewIntent 无法跳转

### ISSUE THREAD

**Issue by gonganruyi** [RonRadtke/react-native-blob-util#99]
在android中使用 android.actionViewIntent(res.path(), 'application/vnd.android.package-archive') 无法跳转到安装界面。

以上问题，我使用了以下方法得以解决，在AndroidManifest.xml 文件中加入以下代码：

<uses-permission android:name="android.permission.INSTALL_PACKAGES" />
<uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" />

**Comment by RonRadtke** [comment]
I need some more information in English please. I have no idea what the problem is.
